(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var H2=function(a){a.S("cardstatechange",g.nL(a)&&g.oL(a)?1:0)},qra=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.Hj&&a.dataset){if(g.uc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.Sc("pollChoiceIndex"))},rra=function(a){return Math.pow(a,3)},sra=function(a){return 3*a*a-2*a*a*a},I2=function(a,b){var c=g.io("use_default_events_client")?void 0:g.rq;
(0,g.y)(b,function(d){d={csn:a,ve:g.yr(d),eventType:4};var e={qk:g.Fr(a),Ci:a};"UNDEFINED_CSN"==a?g.Sr("visualElementShown",d,e):c?g.Hp("visualElementShown",d,c,e):g.sq("visualElementShown",d,e)})},J2=function(a,b){var c=g.io("use_default_events_client")?void 0:g.rq;
(0,g.y)(b,function(d){var e=void 0;e=void 0===e?!1:e;d={csn:a,ve:g.yr(d),eventType:e?16:8};e={qk:g.Fr(a),Ci:a,SE:e};"UNDEFINED_CSN"==a?g.Sr("visualElementHidden",d,e):c?g.Hp("visualElementHidden",d,c,e):g.sq("visualElementHidden",d,e)})},M2=function(a){a=g.Ra(a);
delete K2[a];g.A.isEmpty(K2)&&L2&&L2.stop()},ura=function(){L2||(L2=new g.J(function(){tra()},20));
var a=L2;a.isActive()||a.start()},tra=function(){var a=(0,g.I)();
g.A.forEach(K2,function(b){vra(b,a)});
g.A.isEmpty(K2)||ura()},N2=function(a,b,c,d){g.tn.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.w=a;this.J=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.H=0;this.F=null},vra=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.H=1E3/(b-a.F);a.F=b;wra(a,a.progress);1==a.progress?(a.o=0,M2(a),a.fd(),a.A()):1==a.o&&a.Et()},wra=function(a,b){g.Oa(a.G)&&(b=a.G(b));
a.coords=Array(a.w.length);for(var c=0;c<a.w.length;c++)a.coords[c]=(a.J[c]-a.w[c])*b+a.w[c]},xra=function(a,b){g.qe.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.H;this.state=b.o},O2=function(a,b,c,d,e){N2.call(this,b,c,d,e);
this.element=a},P2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
O2.call(this,a,b,c,d,e)},Q2=function(a){g.B.call(this);
this.u=a||window;this.o=[]},yra=function(a,b,c,d){c=(0,g.x)(c,d||a.u);
b=g.pp(b,"change",c,"iv-card-poll-choice-input");a.o.push(b)},R2=function(a){return a.baseUrl||null},S2=function(a,b){return(0,g.ce)((0,g.jc)(a,b,void 0),function(c){return!!c})},zra=function(a,b,c){function d(yb){var $a=yb.hovercardButton;
if(!$a)return null;$a=$a.subscribeButtonRenderer;if(!$a)return null;var vc=f($a.unsubscribedButtonText),ff=f($a.subscribedButtonText);if($a.subscribed){var gf=f($a.subscriberCountWithUnsubscribeText);var Ch=f($a.subscriberCountText)}else gf=f($a.subscriberCountText),Ch=f($a.subscriberCountWithSubscribeText);var hf=null;return yb.signinEndpoint&&(hf=g.A.Yh(yb,"signinEndpoint","webNavigationEndpointData","url"),!hf)?null:vc&&(ff||hf)?{subscribed:$a.subscribed,subscribeText:vc,subscribeCount:gf,unsubscribeText:ff,
unsubscribeCount:Ch,enabled:$a.enabled,signinUrl:hf,classic:yb.useClassicSubscribeButton}:null}
function e(yb){if(yb){var $a=[],vc=yb.videoId;vc&&$a.push("v="+vc);(vc=yb.playlistId)&&$a.push("list="+vc);(yb=yb.startTimeSeconds)&&$a.push("t="+yb);return"/watch?"+$a.join("&")}}
function f(yb){if(!yb)return null;var $a=yb.simpleText;return $a?$a:yb.runs?(0,g.jc)(yb.runs,function(vc){return vc.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var k=b.style,l=b.endpoint||{},m=null,n=null,q=null,t=null,u=null,z=null,D=!1,E=null,F=null,H=null,G=null,la=null;if("VIDEO"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,t=f(b.videoDuration);else if("PLAYLIST"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,u=f(b.playlistLength);else if("CHANNEL"==k){if(D=g.A.Yh(l,"browseEndpoint","browseId"))z=D,m="/channel/"+z;n=!1;q="new";(D=!!b.isSubscribe)?E=d(b):F=f(b.subscribersText)}else"WEBSITE"==
k?((H=g.A.Yh(l,"urlEndpoint","url"))&&(m=H),n=!0,q="new",H=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"==k&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(la=f(b.additionalFeesText)),(n=g.A.Yh(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=g.A.Yh(b,"title","accessibility","accessibilityData","label");var pa=b.endpoint?b.endpoint.clickTrackingParams:null,Rb="";if(b.metadata){var Lc=f(b.metadata);Lc&&(Rb=Lc)}return{id:"element-"+c,type:k,title:f(b.title),metadata:Rb,callToAction:f(b.callToAction),
Jw:b.image,iconUrl:H,left:parseFloat(b.left),width:parseFloat(b.width),top:parseFloat(b.top),aspectRatio:parseFloat(b.aspectRatio),startMs:parseInt(b.startMs,10),endMs:parseInt(b.endMs,10),videoDuration:t,playlistLength:u,channelId:z,subscribeButton:E,subscribersText:F,isSubscribe:D,targetUrl:m,tG:n,Nb:{itct:pa},kP:q,gk:a?a:null,xG:b.isPlaceholder,impressionUrls:S2(b.impressionUrls||[],R2),jG:S2(b.hovercardShowUrls||[],R2),clickUrls:S2(l.loggingUrls||[],R2),visualElement:g.wr(b.trackingParams),productPrice:G,
additionalFeesText:la}},T2=function(a,b){var c={};
c.startMs=parseInt(a.startMs,10);c.impressionUrls=S2(a.impressionUrls||[],R2);a.trackingParams&&(c.visualElement=g.wr(a.trackingParams));c.elements=S2(a.elements||[],function(d,e){return zra(b,d,e)});
return c},U2=function(a){g.LL.call(this,a);
this.A=this.u=null;this.o={};this.F={};this.C=this.w=null;this.H=[];a=a.N();this.J=g.my(a)||g.oy(a);this.P=!0;this.G=0;this.B=new g.P(this);g.C(this,this.B);this.B.L(this.player,g.ID("creatorendscreen"),this.kH);this.B.L(this.player,"crx_creatorendscreen",this.lH);this.B.L(this.player,"resize",this.Wy);this.B.L(window,"focus",this.hO);this.load();var b=g.Xd("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.ne(this,function(){g.be(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Ara=function(a){return a.player.getVideoData().zc?"current":a.J?"new":"current"},V2=function(a){return"creator-endscreen-editor"===a.player.N().playerStyle},W2=function(a,b,c){c=void 0===c?!0:c;
g.NQ(a.player.app,"creatorendscreen",void 0);a.w&&(a.w.dispose(),a.w=null,a.C.dispose(),a.C=null);for(var d in a.o)a.o[d].dispose();a.o={};a.F={};0<a.H.length&&(a.H.forEach(function(l){l.dispose()}),a.H.length=0);
a.G=0;if((a.u=b)&&b.elements){c&&Bra(a);c=[];d=new g.FD(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.N().o||(a.w=new g.S({D:"div",I:"ytp-ce-shadow"}),g.yL(a.player,a.w.element,4),a.C=new g.fM(a.w,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=Cra(a,e);a.o[e.id]=f;a.F[e.id]=e;g.yL(a.player,f.element,4);var k=new g.FD(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);Dra(a,f,e)}g.uL(a.player,c);
a.Wy()}},Bra=function(a){var b=g.Cr(),c=g.Er();
c&&b&&a.u.visualElement&&g.Yr(c,b,a.u.visualElement)},Cra=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={D:"div",Y:["ytp-ce-element","ytp-ce-video"],M:{tabindex:"0","aria-label":b.gk||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-covering-image",M:X2(b)},{D:"div",I:"ytp-ce-covering-shadow-top"},{D:"a",I:"ytp-ce-covering-overlay",M:{href:Y2(a,b.targetUrl),tabindex:"-1"},K:[{D:"div",Y:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],M:{dir:g.Nm(b.title||"")},W:b.title},{D:"div",I:"ytp-ce-video-duration",W:b.videoDuration}]}]};
c=new g.S(c);break;case "PLAYLIST":c={D:"div",Y:["ytp-ce-element","ytp-ce-playlist"],M:{tabindex:"0","aria-label":b.gk||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-covering-image",M:X2(b)},{D:"div",I:"ytp-ce-covering-shadow-top"},{D:"a",I:"ytp-ce-covering-overlay",M:{href:Y2(a,b.targetUrl),tabindex:"-1"},K:[{D:"div",Y:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],M:{dir:g.Nm(b.title||"")},W:b.title},{D:"div",I:"ytp-ce-playlist-count",K:[{D:"div",
I:"ytp-ce-playlist-icon"},{D:"div",I:"ytp-ce-playlist-count-text",W:b.playlistLength}]}]}]};c=new g.S(c);break;case "CHANNEL":c={D:"div",Y:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],M:{tabindex:"0","aria-label":b.gk||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",K:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",
K:[{D:"div",I:"ytp-ce-expanding-overlay-body",K:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{D:"a",Y:["ytp-ce-channel-title","ytp-ce-link"],M:{href:Y2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Nm(b.title||"")},W:b.title},b.subscribeButton?{D:"div",I:"ytp-ce-subscribe-container",K:[{D:"div",I:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{D:"div",I:"ytp-ce-channel-subscribers-text",W:b.subscribersText}:"",b.metadata?{D:"div",Y:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
W:b.metadata}:""]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",M:X2(b)}]};c=new g.S(c);var d=g.Jd(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.K(d,"ytp-ce-subscribe-button");if(a.player.N().o){var e=null;var f=b.Nb.itct}else e="endscreen",f=null;e=new g.cQ(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.H.push(e)}break;case "WEBSITE":c={D:"div",Y:["ytp-ce-element","ytp-ce-website"],M:{tabindex:"0","aria-label":b.gk||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",K:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",K:[{D:"div",I:"ytp-ce-expanding-overlay-body",
K:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",I:"ytp-ce-website-title",M:{dir:g.Nm(b.title||"")},W:b.title},{D:"div",I:"ytp-ce-website-metadata",W:b.metadata},{D:"a",Y:["ytp-ce-website-goto","ytp-ce-link"],M:{href:Y2(a,b.targetUrl),target:"_blank",tabindex:"-1"},W:b.callToAction}]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",M:X2(b)},{D:"div",I:"ytp-ce-expanding-icon",M:Era(b.iconUrl)}]};c=new g.S(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",I:"ytp-ce-merchandise-price-container",
K:[{D:"div",I:"ytp-ce-merchandise-price",W:b.productPrice}]},b.additionalFeesText&&c.K.push({D:"div",I:"ytp-ce-merchandise-additional-fees",W:b.additionalFeesText})),c={D:"div",Y:["ytp-ce-element","ytp-ce-merchandise"],M:{tabindex:"0","aria-label":b.gk||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",K:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",K:[{D:"div",
I:"ytp-ce-expanding-overlay-body",K:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",I:"ytp-ce-merchandise-title",M:{dir:g.Nm(b.title||"")},W:b.title},c,{D:"div",I:"ytp-ce-merchandise-metadata",W:b.metadata},{D:"a",Y:["ytp-ce-merchandise-goto","ytp-ce-link"],M:{href:Y2(a,b.targetUrl),target:"_blank",tabindex:"-1"},W:b.callToAction}]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",M:X2(b)},{D:"div",I:"ytp-ce-merchandise-invideo-cta-container",K:[{D:"div",I:"ytp-ce-merchandise-invideo-cta",
W:b.callToAction}]}]},c=new g.S(c)}b.xG&&g.K(c.element,"ytp-ce-placeholder");return c},X2=function(a){if(a.Jw)var b=a.Jw.thumbnails;
return Era(b?b[b.length-1].url:null)},Era=function(a){return a?{style:"background-image: url("+a+")"}:{}},Dra=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.ha("mouseenter",(0,g.x)(a.Es,a,b,c));b.ha("mouseleave",(0,g.x)(a.It,a,b,c));a.player.N().o||b.ha("click",(0,g.x)(function(l){g.K(l.element,"ytp-ce-element-hover")},a,b));
b.ha("click",(0,g.x)(a.FA,a,c));b.ha("keypress",(0,g.x)(a.FA,a,c));b.ha("focus",(0,g.x)(function(l,m){this.Es(l,m)},a,b,c));
b.ha("blur",(0,g.x)(function(l,m){this.It(l,m)},a,b,c));
b.ha("touchstart",(0,g.x)(a.Es,a,b,c));var f=g.Ld("ytp-ce-expanding-overlay-hider",b.element);f&&b.L(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.rn(b.element,"ytp-ce-element-hover");g.rn(b.element,"ytp-ce-force-expand")});
b.ha("keydown",(0,g.x)(function(l,m){this.P=9==m.keyCode&&!m.shiftKey},a,b));
var k=(0,g.x)(function(l,m,n){this.G+=n;0<this.G?(g.K(l.element,"ytp-ce-force-expand"),Z2(this,m.id,!0)):(g.rn(l.element,"ytp-ce-force-expand"),g.rn(l.element,"ytp-ce-element-hover"),Z2(this,m.id,!1))},a,b,c);
c=(0,g.x)(function(l,m){m&&(l.ha("blur",g.Sa(function(){"none"!=m.style.display&&a.P&&m.focus()})),l.L(m,"focus",d),l.L(m,"blur",e))},a,b);
c(g.Ld("ytp-sb-subscribe",b.element));c(g.Ld("ytp-sb-unsubscribe",b.element));b.ha("focus",d);b.ha("blur",e)},Y2=function(a,b){var c=a.player.N();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.Oy(c)+b}else return"";return b},Z2=function(a,b,c){a.w&&(c?a.C.show():a.C.hide());
for(var d in a.o)d!=b&&g.L(a.o[d].element,"ytp-ce-element-shadow-show",c)},$2=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||0==b.length||V2(a))c&&c();else{b=Fra(a,b);var e=0,f=!1,k=new g.J(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.Cq(b[a],d)}},a3=function(a,b,c){$2(a,b.clickUrls,c);
(a=g.Er())&&b.tG&&g.Vr(a,b.visualElement)},Fra=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(Gra(b[e],c));return d},Gra=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Hra=function(a){return g.Ma(a)&&a.length?a[0]:a},b3=function(a){return"string"===typeof a?a:""},c3=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},Jra=function(a){var b=Ira;
if(null==a)return null;if(g.Na(a)){var c=[];(0,g.y)(a,function(d){(d=b(d))&&c.push(d)});
return c}return(a=b(a))?[a]:[]},Kra=function(a){this.externalId=a},Lra=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},d3=function(a){if(!a)return null;
var b=g.dc(b3(a.value));b=g.bc(b);if(!b)return null;var c=c3(a.target,Mra,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Lra(b,c,"true"==d||"false"==d?"true"==d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},e3=function(a){return a.value?a.value:null},Nra=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},Ira=function(a){if(!a)return null;
var b=c3(a.type,Ora),c=c3(a.trigger,Pra),d=Hra(a.url);d=d3(d?d:null);a=Hra(a.subscribeData);var e=a?a:null;e?(a=b3(e.external_user_id),e=b3(e.subscription_token),a=a&&e?new Kra(a):null):a=null;return b?new Nra(b,c,d,a):null},Qra=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.o=d||[];this.data=e},Sra=function(a){return(a=Rra(a,function(b){return"openUrl"==b.type&&null!=b.url}))?a.url:null},Rra=function(a,b){return g.Za(a.o,b,void 0)},Tra=function(a,b){return a.id.replace(/[^a-z0-9-]/gi,"-")+"-"+b.toString()},Ura=function(a,b){this.merchant=a;
this.price=b},Vra=function(a){this.o=a},Wra=function(a,b,c){b&&(c?f3(a,(0,g.jc)(b,g.Sa(function(d,e){return g.Lm(e,d)},c))):f3(a,b))},f3=function(a,b,c,d){var e=1,f=-1;
if(c){var k=!1;var l=function(){e--;e||k||(clearTimeout(f),k=!0,c())};
f=setTimeout(function(){k=!0;c()},1E3)}(0,g.y)(b||[],function(m){e++;
g.Cq(m,l)});
d&&(e++,0!=d&&a.o.sendVideoStatsEngageEvent(d,l))},Xra=function(a,b,c,d,e,f,k){this.o=a;
this.w=b;this.Wa=c;this.videoData=d;this.logger=e;this.aa=f;this.u=k},g3=function(a,b){this.o=a;
this.w=b},$ra=function(a,b){var c=[];
(0,g.y)(b.choices,function(k){c.push(Yra(b,k))},a);
var d={D:"ul",M:{role:"radiogroup"},K:c},e={};b.Gi&&(e["aria-label"]=g.LM("$POLL_TITLE - Sign in to vote.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{D:"div",I:"iv-card-content",K:[h3("h2",e,b.title),{D:"form",K:[{D:"fieldset",K:[d]}]}]}];b.Gi&&(f.push("iv-card-unavailable"),d.push({D:"div",Y:["iv-card-sign-in"],K:[{D:"h2",W:"Want to vote?"},{D:"a",Y:["iv-card-sign-in-button","iv-button"],M:{href:e3(b.Gi)},K:[{D:"span",Y:["iv-button-content"],W:"Sign in"}]}]}));f=new g.S({D:"div",
Y:f,K:d});d=f.element;Zra(b,d);yra(a.o.o,d,g.Sa(a.A,b),a);(0,g.y)(g.Kd("iv-card-poll-choice-input",d),function(k){this.o.o.ha(k,"focus",g.Sa(this.u,!0));this.o.o.ha(k,"blur",g.Sa(this.u,!1))},a);
b.Gi&&(d=g.Ld("iv-card-sign-in-button",d),a.w(d,b.Gi,b.id,b.Nb,b.Jc.click,5));return f},asa=function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.DP?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.wG&&b.ew?{D:"span",Y:d,M:e,W:b.ew}:"";c={D:"div",Y:["iv-card",c],K:[{D:"a",I:"iv-click-target",M:{href:e3(b.url)},K:[i3(b.Mi,d?{D:"div",I:"iv-card-image-text",K:[d,b.priceText]}:""),{D:"div",I:"iv-card-content",K:[{D:"h2",I:"iv-card-primary-link",W:b.title},j3(a,b)]}]}]};c=new g.S(c);k3(a,g.Kd("iv-click-target",c.element),b,b.url);return c},l3=function(a){return a.customMessage?
h3("div","iv-card-message",a.customMessage):""},i3=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{D:"div",I:"iv-card-image",M:{style:c},K:d}},j3=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.y)(b.metaInfo,function(d){c.push(h3("li","",d))},a);
return{D:"ul",I:"iv-card-meta-info",K:c}},Yra=function(a,b){return{D:"li",
I:Tra(a,b.index),K:[{D:"label",K:[{D:"input",I:"iv-card-poll-choice-input",M:{type:"checkbox",role:"radio",name:a.id.replace(/[^a-z0-9-]/gi,"-")+b.index.toString(),value:b.index.toString(),"data-poll-choice-index":b.index.toString()}},{D:"span",I:"iv-card-poll-choice-text",K:[{D:"span",I:"iv-card-poll-choice-percent"},h3("span",void 0,b.desc)]}]},{D:"div",I:"iv-card-poll-result",K:[{D:"div",I:"iv-card-poll-result-bar"}]}]}},h3=function(a,b,c){b?"string"===typeof b?b={"class":b}:g.Ma(b)&&(b={"class":b.join(" ")}):
b={};
b.dir=g.Nm(c);return{D:a,M:b,W:c}},bsa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.an&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.an+");");c.dir=g.Nm(a.customMessage);var d=[{D:"span",W:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",I:"iv-card-link-icon"}));return{D:"div",Y:b,M:c,K:d}},Zra=function(a,b){var c=0;
(0,g.y)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.Ld(Tra(a,e.index),b);e=e.count/c;null==a.Ce&&(e=0);g.L(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.Ce==d);f.getElementsByTagName("input")[0].checked=a.Ce==d;var k=Math.floor(100*e).toFixed(0),l=g.Ld("iv-card-poll-choice-percent",f);g.fe(l,g.LM("$PERCENT%",{PERCENT:k}));f=g.Ld("iv-card-poll-result-bar",f);g.ch(f,"transform","scaleX("+e.toFixed(2)+")")}g.L(b,"iv-card-poll-voted",null!=a.Ce);g.L(b,"iv-card-poll-expanded",
null!=a.Ce&&1<a.choices.length)},k3=function(a,b,c,d){d&&(0,g.y)(b,function(e){this.w(e,d,c.id,c.Nb,c.Jc.click,5)},a)},csa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},dsa=function(a,b){return b?b:csa(a)?"current":"new"},m3=function(a,b){g.B.call(this);
var c=this;this.o=a;this.context=b;this.Mu=!1;this.ra=new Map;this.na=new Map;this.context.aa.addEventListener(g.ID("annotations_module"),function(d){(d=c.ra.get(d))&&d.apply(c)});
this.context.aa.addEventListener("crx_annotations_module",function(d){(d=c.na.get(d))&&d.apply(c)})},esa=function(a,b,c,d,e){var f=e3(b);
if(f){var k=dsa(f,b.target),l=(0,g.x)(function(){b.o&&this.context.aa.pauseVideo();var m=this.context.videoData.zc||!1,n=g.Op(f||"");m&&n&&(n.v||n.list)?g.zT(this.context.aa.app,n.v,c,n.list,!1,void 0):g.PM(f||"","current"==k?"_top":void 0,c)},a);
"new"==k&&(l(),l=null);f3(a.context.logger,d,l,e);csa(f)||(a=g.Er(),d=c.itct,a&&d&&g.Vr(a,g.wr(d)))}},fsa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},n3=function(a,b,c){return{Yx:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
sC:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
Kp:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl})}},q3=function(a,b,c){m3.call(this,b,c);
var d=this;this.w=a;this.da=this.Ga=this.C=this.Ea=!1;this.ea=null;this.Z=new g.J(g.Ja,c.Wa.Ka?4E3:3E3);g.C(this,this.Z);this.ya=new g.J(g.Ja);g.C(this,this.ya);this.H=new g3(c,(0,g.x)(this.Sj,this),(0,g.x)(this.mo,this));this.U=new g.S({D:"div",I:"iv-drawer",M:{id:"iv-drawer"},K:[{D:"div",I:"iv-drawer-header",M:{"aria-role":"heading"},K:[{D:"span",I:"iv-drawer-header-text"},{D:"button",Y:["iv-drawer-close-button","ytp-button"],M:{"aria-label":"Hide cards",tabindex:"0"}}]},{D:"div",I:"iv-drawer-content"}]});
g.C(this,this.U);this.F=this.U.element;this.sa=new g.fM(this.U,330);g.C(this,this.sa);this.Ba=g.Ld("iv-drawer-header-text",this.F);this.B=g.Ld("iv-drawer-content",this.F);this.A=[];this.za=this.R=this.G=this.ga=this.u=null;this.V=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.Ga&&o3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Ga=d.C)&&p3(d)});
this.O=this.J=this.ca=null;this.P=0},gsa=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){o3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){p3(a)});
var c=b.data.headerText;g.fe(a.Ba,c);a.R&&a.R.setAttribute("title",c);a.ca=g.wr(b.data.trackingParams);a.O=g.wr(b.data.closeTrackingParams);a.J=g.wr(b.data.iconTrackingParams)},hsa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.P;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.P,type:"simple",teaserText:g.W(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Nb:r3(a,c,b,d),sponsored:!1,Jc:n3(d,e,d.command),ae:d.trackingParams?g.wr(d.trackingParams):null,Vd:e.trackingParams?
g.wr(e.trackingParams):null,xd:f&&f.trackingParams?g.wr(f.trackingParams):null,imageUrl:s3(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.W(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,an:null,title:d.title?g.W(d.title):"",customMessage:d.callToAction?g.W(d.callToAction):"",url:d.command.urlEndpoint.url?d3({pause_on_navigation:!a.context.videoData.va,target:"new",value:d.command.urlEndpoint.url}):null};t3(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.P,type:"collaborator",teaserText:g.W(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Nb:r3(a,c,b,d),sponsored:!1,Jc:n3(d,e,d.endpoint),ae:d.trackingParams?g.wr(d.trackingParams):null,Vd:e.trackingParams?g.wr(e.trackingParams):null,xd:f&&f.trackingParams?
g.wr(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.W(d.customText):null,uB:s3(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.W(d.channelName):"",metaInfo:[d.subscriberCountText?g.W(d.subscriberCountText):""],url:d3({pause_on_navigation:!a.context.videoData.va,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};t3(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.P,type:"playlist",teaserText:g.W(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Nb:r3(a,c,b,d),sponsored:!1,Jc:n3(d,e,d.action),ae:d.trackingParams?g.wr(d.trackingParams):null,Vd:e.trackingParams?g.wr(e.trackingParams):null,xd:f&&f.trackingParams?g.wr(f.trackingParams):
null,Mi:s3(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.W(d.customMessage):null,playlistVideoCount:g.W(d.playlistVideoCount),title:d.playlistTitle?g.W(d.playlistTitle):"",metaInfo:[d.channelName?g.W(d.channelName):"",d.videoCountText?g.W(d.videoCountText):""],url:d3({pause_on_navigation:!a.context.videoData.va,target:"new",value:fsa(d.action)})};t3(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.P,type:"video",teaserText:g.W(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Nb:r3(a,c,b,d),sponsored:!1,Jc:n3(d,e,d.action),ae:d.trackingParams?g.wr(d.trackingParams):null,Vd:e.trackingParams?g.wr(e.trackingParams):null,xd:f&&f.trackingParams?g.wr(f.trackingParams):null,Mi:s3(d.videoThumbnail.thumbnails,
258).url,videoDuration:d.lengthString?g.W(d.lengthString):null,customMessage:d.customMessage?g.W(d.customMessage):null,title:d.videoTitle?g.W(d.videoTitle):"",metaInfo:[d.channelName?g.W(d.channelName):"",d.viewCountText?g.W(d.viewCountText):""],isLiveNow:!!d.badge,url:d3({pause_on_navigation:!a.context.videoData.va,target:"new",value:fsa(d.action)})};t3(a,c)}a.P++},s3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height==b||290==a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},r3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId,itct:d.trackingParams}},jsa=function(a,b){var c=isa(a,b);
c&&(c==a.u&&(a.u=null),a.w.removeCueRange(c.card.id),g.be(c.Gq),g.gb(a.A,c),a.dn(),u3(a))},o3=function(a,b,c){if(!a.C){a.sa.show();
a.ga=new g.J(function(){g.K(g.eL(a.context.aa),"ytp-iv-drawer-open")},0);
a.ga.start();a.ea=g.gp(a.B,"mousewheel",(0,g.x)(a.yH,a));a.C=!0;var d=g.Er();d&&a.ca&&a.O&&I2(d,[a.ca,a.O]);var e=g.A.create("TRIGGER_TYPE",b);(0,g.y)(a.A,function(f){f.Ey||(f.Ey=!0,Wra(a.context.logger,f.card.Jc.Yx,e));d&&I2(d,[f.card.ae])});
H2(a.w);c&&(a.G=new g.J(function(){a.wa=a.R;a.za.focus()},330),a.G.start())}},p3=function(a){a.C&&(a.sa.hide(),g.hp(a.ea),a.ea=null,g.rn(g.eL(a.context.aa),"ytp-iv-drawer-open"),a.C=!1,H2(a.w),a.G&&a.G.stop(),a.G=new g.J(function(){a.wa&&(a.wa.focus(),a.wa=null)},330),a.G.start())},ksa=function(a){var b=g.Ld("iv-drawer-close-button",a.F);
a.context.o.ha(b,"click",a.yE,a);a.context.o.ha(a.B,"touchend",function(){a.Z.start()});
a.context.o.ha(a.B,"scroll",a.OE,a);a.context.u.subscribe("onHideControls",function(){a.da=!0});
a.context.u.subscribe("onShowControls",function(){a.da=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.da=g.pn(g.eL(a.w),"ytp-autohide")});
a.V.push(g.Ao("iv-button-shown",a.EG,a));a.V.push(g.Ao("iv-button-hidden",a.DG,a));a.V.push(g.Ao("iv-teaser-shown",a.HG,a));a.V.push(g.Ao("iv-teaser-hidden",a.GG,a));a.V.push(g.Ao("iv-teaser-clicked",a.FG,a))},t3=function(a,b){a.Ea||(g.qn(a.o,["html5-stop-propagation",
"iv-drawer-manager"]),g.yL(a.w,a.F,5),ksa(a),a.R=g.Ld("ytp-cards-button",g.eL(a.w)),a.za=g.Ld("iv-drawer-close-button",a.F),a.Ea=!0);jsa(a,b.id);var c=lsa(a,b);if(c){var d={card:b,Gq:c.element,Ey:!1},e=msa(a,d);g.ob(a.A,e,0,d);c.ba(a.B,e);a.dn();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,g.Sa(a.UO,d)):(c=1E3*a.context.aa.getCurrentTime(),5E3>c&&c>b.startMs&&a.ZB(d),a.addCueRange(b.startMs,b.startMs+1,b.id,g.Sa(a.ZB,d)),u3(a))}},lsa=function(a,b){switch(b.type){case "simple":var c=a.H;
var d=b.displayDomain?{D:"div",I:"iv-card-image-text",W:b.displayDomain}:"";var e=bsa(b);d={D:"div",Y:["iv-card"],K:[{D:"a",I:"iv-click-target",M:{href:e3(b.url)},K:[i3(b.imageUrl,d),{D:"div",I:"iv-card-content",K:[h3("h2",void 0,b.title),e]}]}]};d=new g.S(d);k3(c,g.Kd("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.H,d={D:"div",Y:["iv-card","iv-card-channel"],K:[{D:"a",Y:["iv-click-target"],M:{href:e3(b.url),"data-ytid":b.channelId},K:[i3(b.uB),{D:"div",I:"iv-card-content",
K:[l3(b),{D:"h2",I:"iv-card-primary-link",W:b.title},j3(c,b)]}]}]},d=new g.S(d),k3(c,g.Kd("iv-click-target",d.element),b,b.url),d;case "episode":return asa(a.H,b,"iv-card-episode");case "movie":return asa(a.H,b,"iv-card-movie");case "playlist":return c=a.H,d={D:"div",Y:["iv-card","iv-card-playlist"],K:[{D:"a",I:"iv-click-target",M:{href:e3(b.url)},K:[i3(b.Mi,{D:"div",I:"iv-card-image-overlay",K:[{D:"span",I:"iv-card-playlist-video-count",W:b.playlistVideoCount}]}),{D:"div",I:"iv-card-content",K:[l3(b),
h3("h2","iv-card-primary-link",b.title),j3(c,b)]}]}]},d=new g.S(d),k3(c,g.Kd("iv-click-target",d.element),b,b.url),d;case "poll":return $ra(a.H,b);case "productListing":c=a.H;var f=!g.db(b.offers);d=["iv-card"];e="";var k=bsa(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",f=b.offers[0],k=[],f.price&&k.push({D:"div",I:"iv-card-offer-price",W:f.price}),f.merchant&&k.push({D:"div",I:"iv-card-offer-merchant",W:f.merchant}),k={D:"div",K:k});d={D:"div",Y:d,M:{tabindex:"0"},K:[{D:"a",
Y:["iv-card-image","iv-click-target"],M:{style:"background-image: url("+b.imageUrl+");",href:e3(b.url),"aria-hidden":"true",tabindex:"-1"}},{D:"div",I:"iv-card-content",K:[b.sponsored?{D:"div",I:"iv-card-sponsored",K:["Sponsored",{D:"div",I:"iv-ad-info-container",K:[{D:"div",I:"iv-ad-info",W:"{{adInfo}}"},{D:"div",I:"iv-ad-info-icon-container",K:[{D:"div",I:"iv-ad-info-icon"},{D:"div",I:"iv-ad-info-callout"}]}]}]}:"",{D:"a",I:"iv-click-target",M:{href:e3(b.url)},K:[h3("h2",e,b.title),k]}]}]};d=new g.S(d);
e=g.Xd("span");g.fe(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");d.sb(e,"adInfo");k3(c,g.Kd("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.H,d=b.isLiveNow?{D:"span",Y:["yt-badge","yt-badge-live"],W:"LIVE NOW"}:"",d={D:"div",Y:["iv-card","iv-card-video"],K:[{D:"a",I:"iv-click-target",M:{href:e3(b.url)},K:[i3(b.Mi,b.videoDuration?{D:"span",I:"iv-card-video-duration",W:b.videoDuration}:""),{D:"div",I:"iv-card-content",
K:[l3(b),h3("h2","iv-card-primary-link",b.title),j3(c,b),d]}]}]},d=new g.S(d),k3(c,g.Kd("iv-click-target",d.element),b,b.url),d}return null},msa=function(a,b){if(0==a.A.length)return 0;
var c=g.ab(a.A,function(d){return b.card.startMs>d.card.startMs||b.card.startMs==d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1==c?0:c+1},nsa=function(a){return a.u?"productListing"==a.u.card.type:(0,g.bi)(a.A,function(b){return"productListing"==b.card.type})},u3=function(a){g.L(g.eL(a.w),"ytp-cards-shopping-active",nsa(a))},osa=function(a,b){if(a.U.Ha()){var c=new N2([0,
a.B.scrollTop],[0,b.Gq.offsetTop],600,sra);a.context.w.ha(c,"animate",function(d){a.B.scrollTop=d.y});
a.context.w.ha(c,"finish",function(d){a.B.scrollTop=d.y});
c.play()}else g.ku(a.U,!0),a.B.scrollTop=b.Gq.offsetTop,g.ku(a.U,!1)},v3=function(a){return a.u&&a.u.card?a.u.card:a.A[0]&&a.A[0].card?a.A[0].card:null},isa=function(a,b){return g.Za(a.A,function(c){return c.card.id==b})},w3=function(a,b,c){m3.call(this,a,b);
this.annotation=c;this.isActive=!1},psa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},x3=function(a,b,c){w3.call(this,a,b,c);
this.w=null;this.G=!1;this.A=null;this.B=!1;this.u=this.F=this.C=null},y3=function(a,b,c){w3.call(this,a,b,c);
this.J=this.C=this.P=!1;this.G=5E3;this.B=null;this.H=g.Wd("DIV","iv-promo-contents");this.w=this.A=this.u=null;this.F=new g.J(function(){this.u.setAttribute("aria-hidden",!0);g.wh(this.A,!1);g.wh(this.w,!0)},700,this);
g.C(this,this.F)},qsa=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.G=b.collapse_delay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.o.setAttribute("aria-hidden",!0);a.o.setAttribute("aria-label","Promotion");a.o.tabIndex=0;var e=Sra(a.annotation),f=b.image_url;if(f){var k=g.Wd("DIV",["iv-promo-img","iv-click-target"]);f=g.Wd("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.Wd("SPAN","iv-promo-video-duration",b.video_duration),
k.appendChild(f)):b.playlist_length&&(f=g.Wd("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.Sj(k,e,a.annotation.id,b.session_data,void 0,c)}e?(f=g.Wd("A","iv-promo-txt"),g.Fc(f,e3(e)),a.u=f):a.u=g.Wd("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.Wd("P",null,g.Wd("STRONG",null,b.text_line_1));var m=g.Wd("P",null,g.Wd("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");g.T(a.context.Wa.experiments,
"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.Wd("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.Wd("BUTTON",["iv-button","iv-promo-button"],g.Wd("SPAN","iv-button-content",f));var q=g.Wd("DIV","iv-promo-button-container");q.appendChild(f);e&&a.Sj(a.o,e,a.annotation.id,b.session_data,void 0,c)}g.K(a.u,"iv-click-target");e&&a.Sj(a.u,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=g.Wd("P",null,g.Wd("SPAN",null,b.text_line_1)),
m=g.Wd("P",null,g.Wd("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.Wd("SPAN",["yt-badge","iv-promo-badge-live"],"LIVE NOW")),g.K(a.u,"iv-click-target"),e&&a.Sj(a.u,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.u.appendChild(l);m&&a.u.appendChild(m);a.H.appendChild(a.u);q&&a.H.appendChild(q);c=g.Wd("DIV","iv-promo-actions");a.w=g.Wd("BUTTON",["iv-promo-expand","ytp-button"]);a.w.title="Expand";a.context.o.ha(a.w,"click",g.Sa(a.Er,5E3),a);c.appendChild(a.w);g.wh(a.w,!1);
a.context.o.ha(a.o,"mouseover",a.NF,a);a.context.o.ha(a.o,"mouseout",a.MF,a);a.context.o.ha(a.o,"touchend",g.Sa(a.Er,5E3),a);a.A=g.Wd("BUTTON",["iv-promo-close","ytp-button"]);a.A.title="Close";a.context.o.ha(a.A,"click","cta"==a.annotation.style&&b.text_line_3?a.FF:a.EF,a);c.appendChild(a.A);g.qn(a.o,d);k&&(a.o.appendChild(k),n&&k.appendChild(n));a.o.appendChild(a.H);a.o.appendChild(c)},rsa=function(a){a.C||a.J||a.B||(g.K(a.o,"iv-promo-collapsed"),a.C=!0,a.F.start())},ssa=function(a){a.F.stop();
a.C&&(g.sn(a.o,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.C=!1,a.u&&a.u.removeAttribute("aria-hidden"),g.wh(a.w,!1),g.wh(a.A,!0))},tsa=function(a,b){a.B||(a.B=g.Df(function(){z3(this);
rsa(this)},b,a))},z3=function(a){a.B&&(g.v.clearTimeout(a.B),a.B=null)},A3=function(a){g.LL.call(this,a);
this.J=!1;this.H=0;this.F={};this.U=new Vra(a);this.B=new g.P(this);g.C(this,this.B);this.C=this.w=null;this.B.L(this.player,"onVideoAreaChange",(0,g.x)(this.S,this,"onVideoAreaChange"));this.B.L(this.player,"onHideControls",(0,g.x)(this.S,this,"onHideControls"));this.B.L(this.player,"onShowControls",(0,g.x)(this.S,this,"onShowControls"));this.B.L(this.player,"resize",(0,g.x)(this.S,this,"resize"));this.B.L(this.player,"presentingplayerstatechange",(0,g.x)(this.S,this,"presentingplayerstatechange"));
this.subscribe("presentingplayerstatechange",this.DM,this);this.subscribe("resize",this.cp,this);this.player.N().F.subscribe("vast_info_card_add",this.gB,this);this.R=new g.P(this);g.C(this,this.R);this.O=g.Wd("DIV","video-custom-annotations");this.u=new g.S({D:"div",Y:["ytp-player-content","ytp-iv-player-content"]});g.C(this,this.u);g.yL(this.player,this.u.element,4);this.u.hide();this.A=new g.S({D:"div",Y:["ytp-iv-video-content"]});g.C(this,this.A);g.Zd(this.A.element,g.Wd("DIV","video-annotations",
this.O));this.G=this.o=null;this.P=[];usa(this)&&this.load();var b=g.Xd("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.ne(this,function(){g.be(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},vsa=function(){var a=g.Wd("DIV",["annotation",
"annotation-type-custom"]);g.wh(a,!1);return a},wsa=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},usa=function(a){var b=a.player.N();
a=a.player.getVideoData();return 1==(b.annotationsLoadPolicy||a.annotationsLoadPolicy)&&!a.XC||b.F.get(a.videoId)||g.jC(a)||g.kC(a)?!0:!1},xsa=function(a,b,c){a.J=!0;
a.C=g.fq(b,c)},ysa=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Pa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(ysa(a,e))}return c},zsa=function(a,b,c){return!(a.loaded&&a.H==b&&a.player.getVideoData().videoId==
c)},Csa=function(a){var b=a.player.getVideoData();
if(b.Zd){var c=a.player.N().F.get(b.videoId);if(c){var d={format:"XML",Yd:{},method:"POST",withCredentials:!0};d.fd=(0,g.x)(function(e,f,k){zsa(this,e,f)||(e=g.$p(k)&&k.responseXML?k.responseXML:null)&&B3(this,e)},a,a.H,b.videoId);
g.xp()&&(d.fd=Asa(a,d.fd));d.ub={ic_only:"1"};Bsa(d,c);a.J=!0;g.fq(b.Zd,d)}}},Bsa=function(a,b){a.method="POST";
a.ub=a.ub||{};b.hn&&(a.ub.ic_coll=b.hn);b.jn&&(a.ub.ic_xml=b.jn);b.rm&&(a.ub.ic_track=b.rm)},Dsa=function(a){var b=new g.S({D:"div"});
g.wh(b.element,!1);var c=new q3(a.player,b.element,C3(a));g.C(c,b);b.ba(a.u.element);c.fm();return c},C3=function(a){if(!a.G){var b=new Q2(a);
g.C(a,b);var c=new g.Q1(a);g.C(a,c);a.G=new Xra(b,c,a.player.N(),a.player.getVideoData(),a.U,a.player,a.oc)}return a.G},B3=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Er();if(e){var f=g.Cr();f&&g.Tr(g.io("use_default_events_client")?void 0:g.rq,e,f,[g.wr(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var k=ysa(a,d[e]);f=null;try{if(k){var l=k.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var q=c3(k.type,Esa),t=c3(k.style,Fsa),u=b3(k.data),z=0!=u.length?JSON.parse(u):{},D=Jra(k.action);f=n&&q?new Qra(n,q,t,D,z):null}else f=null}catch(la){}if(f){a:{switch(f.type){case "branding":case "promotion":k=
!0;break a}k=!1}if(k){k=a;m=f;var E=vsa(),F=null;switch(m.type){case "branding":if(k.player.N().Ia)break;k.u.element.appendChild(E);F=new x3(E,C3(k),m);break;case "promotion":g.yL(k.player,E,4),F=new y3(E,C3(k),m)}F&&F.fm();if(k=F)g.C(a,k),a.F[f.id]=k}else if("card"==f.type||"drawer"==f.type){a.o||(a.o=Dsa(a),g.C(a,a.o));if("card"==f.type){if(c=a.o,F=f&&f.data&&f.data.card_type)switch(k=f.data.tracking||{},k={Yx:k.impression,click:k.click,close:k.close,sC:k.teaser_impression,Kp:k.teaser_click},m=
f.data.tracking_params||{},E=null,F){case "collaborator":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Nb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Jc:k,ae:m.card?g.wr(m.card):null,Vd:m.teaser?g.wr(m.teaser):null,xd:m.icon?g.wr(m.icon):null,channelId:f.data.channel_id,customMessage:f.data.custom_message?f.data.custom_message:null,uB:f.data.image_url,
title:f.data.title,metaInfo:f.data.meta_info,url:d3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};t3(c,f);break;case "episode":case "movie":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Nb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Jc:k,ae:m.card?g.wr(m.card):null,Vd:m.teaser?g.wr(m.teaser):null,
xd:m.icon?g.wr(m.icon):null,Mi:f.data.image_url,ew:f.data.badge_symbol||"",priceText:f.data.price_text||"",title:f.data.title,metaInfo:f.data.meta_info,wG:!!f.data.is_paygated,DP:!!f.data.user_has_entitlement,url:d3({target:f.data.target||"new",value:f.data.url})};t3(c,f);break;case "playlist":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Nb:f.data.session_data||
{},sponsored:f.data.sponsored||!1,Jc:k,ae:m.card?g.wr(m.card):null,Vd:m.teaser?g.wr(m.teaser):null,xd:m.icon?g.wr(m.icon):null,Mi:f.data.image_url,playlistVideoCount:f.data.playlist_video_count,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,url:d3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};t3(c,f);break;case "poll":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,
teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Nb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Jc:k,ae:m.card?g.wr(m.card):null,Vd:m.teaser?g.wr(m.teaser):null,xd:m.icon?g.wr(m.icon):null,title:f.data.title,choices:f.data.choices,Ce:f.data.hasOwnProperty("old_vote")?f.data.old_vote:null,Gi:f.data.signin_url?d3({target:"current",value:f.data.signin_url}):null,OP:f.data.hasOwnProperty("xsrf_token")?f.data.xsrf_token:null};t3(c,f);break;case "productListing":f.data.signin_url&&
(E=d3({target:"current",value:f.data.signin_url}));F=[];for(var H=f.data.offers||[],G=0;G<H.length;G++)F.push(new Ura(g.Oc(H[G].merchant),g.Oc(H[G].price)));f={VT:!1,id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Nb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Jc:k,ae:m.card?g.wr(m.card):null,Vd:m.teaser?g.wr(m.teaser):null,xd:m.icon?g.wr(m.icon):null,
imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,an:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:d3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url}),Gi:E,pU:f.data.signin_title?f.data.signin_title:null,oU:f.data.signin_message?f.data.signin_message:null,offers:F};t3(c,f);break;case "simple":f=
{id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Nb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Jc:k,ae:m.card?g.wr(m.card):null,Vd:m.teaser?g.wr(m.teaser):null,xd:m.icon?g.wr(m.icon):null,imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,an:f.data.button_icon_url?f.data.button_icon_url:
null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:d3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};t3(c,f);break;case "video":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Nb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Jc:k,ae:m.card?g.wr(m.card):null,Vd:m.teaser?
g.wr(m.teaser):null,xd:m.icon?g.wr(m.icon):null,Mi:f.data.image_url,videoDuration:f.data.video_duration||null,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,isLiveNow:!!f.data.is_live_now,url:d3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})},t3(c,f)}}else gsa(a.o,f);c=!0}}}c&&(H2(a.player),a.cp())},Gsa=function(a,b){var c=!1;
a.o||(a.o=Dsa(a),g.C(a,a.o));for(var d=g.p(b.cards||[]),e=d.next();!e.done;e=d.next())hsa(a.o,e.value.cardRenderer),c=!0;c&&(c=a.o,d=b.headerText?g.W(b.headerText):"",g.fe(c.Ba,d),c.R&&c.R.setAttribute("title",d),c.ca=b.trackingParams?g.wr(b.trackingParams):null,c.O=b.closeButton.infoCardIconRenderer.trackingParams?g.wr(b.closeButton.infoCardIconRenderer.trackingParams):null,c.J=b.icon.infoCardIconRenderer.trackingParams?g.wr(b.icon.infoCardIconRenderer.trackingParams):null,H2(a.player),a.cp())},
Hsa=function(a,b,c,d,e){if(!a.player.N().Ia){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new Nra("openUrl","click",new Lra("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var k=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:k.height,image_type:1,image_url:k.url,image_width:k.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;b=b.subscribeButton.subscribeButtonRenderer;k=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.W(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(k=g.W(b.subscriberCountText))):(b.subscriberCountText&&(e=g.W(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(k=g.W(b.subscriberCountWithSubscribeText)));var l="";b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url&&(l=b.signInEndpoint.webNavigationEndpointData.url);b={subscribeText:g.W(b.unsubscribedButtonText),subscribeCount:e,unsubscribeText:g.W(b.subscribedButtonText),unsubscribeCount:k,enabled:b.enabled,classic:!1,subscribed:b.subscribed,feature:"iv",signInUrl:l};d.standalone_subscribe_button_data=b}f=new Qra(c,"branding","branding",f,d);d=vsa();a.u.element.appendChild(d);f=new x3(d,C3(a),f);f.fm();g.C(f,f);a.F[c]=f}},Asa=function(a,b){return(0,g.x)(function(){if(!this.la()){var c=
Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Sa.apply(window,c);this.P.push(g.vp(b))}},a)},K2={},L2=null;g.Ua(N2,g.tn);g.h=N2.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.o)this.progress=0,this.coords=this.w;else if(1==this.o)return!1;M2(this);this.startTime=a=(0,g.I)();-1==this.o&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.F=this.startTime;this.progress||this.B();this.qe("play");-1==this.o&&this.qe("resume");this.o=1;var b=g.Ra(this);b in K2||(K2[b]=this);ura();vra(this,a);return!0};
g.h.stop=function(a){M2(this);this.o=0;a&&(this.progress=1);wra(this,this.progress);this.qe("stop");this.A()};
g.h.pause=function(){1==this.o&&(M2(this),this.o=-1,this.qe("pause"))};
g.h.X=function(){0==this.o||this.stop(!1);this.qe("destroy");N2.Db.X.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.Et=function(){this.qe("animate")};
g.h.qe=function(a){this.dispatchEvent(new xra(a,this))};
g.Ua(xra,g.qe);g.Ua(O2,N2);O2.prototype.C=g.Ja;O2.prototype.Et=function(){this.C();O2.Db.Et.call(this)};
O2.prototype.A=function(){this.C();O2.Db.A.call(this)};
O2.prototype.B=function(){this.C();O2.Db.B.call(this)};
g.Ua(P2,O2);P2.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.r(Q2,g.B);Q2.prototype.ha=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.gp(a,b,c);this.o.push(a);return a};
Q2.prototype.rs=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.qp(a,b,c);this.o.push(a);return a};
Q2.prototype.Va=function(a){g.hp(a);g.gb(this.o,a)};
Q2.prototype.X=function(){g.hp(this.o);this.o.length=0;g.B.prototype.X.call(this)};g.r(U2,g.LL);g.h=U2.prototype;g.h.load=function(){g.LL.prototype.load.call(this);if(!V2(this)){var a=g.iC(this.player.getVideoData());if(a)a=T2(a,Ara(this)),W2(this,a,!1);else{var b=this.player.getVideoData();a=b.videoId;this.A&&this.A.abort();a={method:"POST",fd:(0,g.x)(this.qL,this,a),Yd:{v:a},withCredentials:!0};this.J&&(a.Yd.ptype="embedded");var c=this.player.getVideoData().xn;c&&(a.ub={ad_tracking:c});if(b=g.hC(b))if(b=g.dc(b),b=g.bc(b))this.A=g.fq(b,a)}}};
g.h.unload=function(){W2(this,null);this.A&&(this.A.abort(),this.A=null);g.LL.prototype.unload.call(this)};
g.h.Nc=function(a,b){if(!V2(this))return null;if("loadCustomEndscreenRenderer"==a){var c=T2(b,"new");W2(this,c);return!0}return null};
g.h.getOptions=function(){return V2(this)?["loadCustomEndscreenRenderer"]:[]};
g.h.qL=function(a,b){var c=this.A=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=T2(c,Ara(this)))}W2(this,c)};
g.h.Wy=function(){if(this.u&&this.u.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Isa.length;f++){var k=Math.abs(b.width-Isa[f]);if(-1==e||d>=k)e=f,d=k}d=Jsa[e];this.w&&g.ch(this.w.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.u.elements.length;++b)if(f=this.u.elements[b].id,e=this.o[f],k=this.F[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.uh(e.element,Math.round(k.width*a.width),f);g.kh(e.element,m,n);g.sn(e.element,Ksa);m=k.left+k.width/2;k=k.top+l/2;g.K(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.sn(e.element,Jsa);g.K(e.element,d);(e=g.Jd(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.ch(e,"height",f+"px")}}}}};
g.h.kH=function(a){if(this.u)if("ytp-ce-in-endscreen"==a.getId())$2(this,this.u.impressionUrls),(a=g.Er())&&this.u.visualElement&&g.Ur(a,this.u.visualElement);else{a=a.getId().substring(15);var b=this.o[a],c=this.F[a];g.K(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");g.K(g.eL(this.player),"ytp-ce-shown");$2(this,c.impressionUrls);(b=g.Er())&&g.Ur(b,c.visualElement);this.player.N().Bb&&this.player.ma("endscreenelementshown",a)}};
g.h.lH=function(a){if("ytp-ce-in-endscreen"!=a.getId()){a=a.getId().substring(15);var b=this.o[a];g.rn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);g.rn(g.eL(this.player),"ytp-ce-shown");this.player.N().Bb&&this.player.ma("endscreenelementhidden",a)}};
g.h.hO=function(a){var b=this;a.target===window&&(new g.J(function(){for(var c in b.o)g.sn(b.o[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.FA=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.pn(c,"ytp-ce-element");){g.pn(c,"subscribe-label")&&a3(this,a);if(g.pn(c,"ytp-ce-channel-subscribe"))return;c=g.de(c)}if(!c||g.pn(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.o[a.id])this.It(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.kP?(a3(this,a),this.YB(),this.player.pauseVideo(),c=g.dc(Y2(this,a.targetUrl)),c=g.bc(c),g.PM(c,void 0,a.Nb)):(c=this.player.getVideoData().zc,
c=(0,g.x)(this.dP,this,c,Y2(this,a.targetUrl),a.Nb),c=(0,g.x)(this.YB,this,c),a3(this,a,c))}}};
g.h.dP=function(a,b,c){var d=g.Op(b);a&&d&&(d.v||d.list)?g.zT(this.player.app,d.v,c,d.list,!1,void 0):g.OM(b,c)};
g.h.Es=function(a,b){g.pn(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.K(a.element,"ytp-ce-element-hover"):this.player.N().o?(new g.J(function(){g.K(a.element,"ytp-ce-element-hover")},200)).start():g.K(a.element,"ytp-ce-element-hover"),$2(this,b.jG),Z2(this,b.id,!0))};
g.h.It=function(a,b){g.rn(a.element,"ytp-ce-element-hover");g.rn(a.element,"ytp-ce-force-expand");Z2(this,b.id,!1)};
g.h.YB=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var Isa=[346,426,470,506,570,640,853,1280,1920],Jsa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Ksa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var Mra={TQ:"current",oS:"new"};var Ora={CLOSE:"close",rS:"openUrl",TD:"subscribe"},Pra={NQ:"click",CLOSE:"close",ER:"hidden",XS:"rollOut",YS:"rollOver",bT:"shown"};var Fsa={qQ:"anchored",nD:"branding",CHANNEL:"channel",SQ:"cta",GR:"highlightText",XR:"label",PLAYLIST:"playlist",JS:"popup",fT:"speech",TD:"subscribe",pT:"title",VIDEO:"video",CT:"website"},Esa={nD:"branding",EQ:"card",ZQ:"drawer",FR:"highlight",eS:"marker",OS:"promotion",TEXT:"text",ET:"widget"};g3.prototype.u=function(a,b){var c=g.ke(b.target,"label");c&&g.L(c,"iv-card-poll-choice-focused",a)};
g3.prototype.A=function(a,b){var c=g.ke(b.target,null,"iv-card-poll",void 0);if(c)if(a.Gi)g.Ld("iv-card-sign-in-button",c).click();else{var d=parseInt(qra(b.target),10);if(null==a.Ce)a.choices[d].count++,a.Ce=d;else if(a.Ce!=d){var e=a.choices[a.Ce];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.Ce=d}else e=a.choices[a.Ce],e.count=Math.max(e.count-1,0),a.Ce=null;Zra(a,c);g.jq(this.o.videoData.Zd,{Yd:{action_poll_vote:1},ub:{poll_id:a.id,index:d,session_token:a.OP}});f3(this.o.logger,a.Jc.click,
void 0,5);(c=g.Er())&&a.ae&&g.Vr(c,a.ae)}};g.r(m3,g.B);g.h=m3.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.FD(a,b,{id:c});a.namespace="annotations_module";d&&this.ra.set(a,d);e&&this.na.set(a,e);g.uL(this.context.aa,[a])};
g.h.fm=function(){this.context.u.subscribe("resize",this.dn,this)};
g.h.Sj=function(a,b,c,d,e,f){this.context.o.ha(a,"click",g.Sa(this.mo,b,c,d,e||[],f||0),this);this.context.o.ha(a,"touchstart",g.Sa(function(){this.Mu=!1}),this);
this.context.o.ha(a,"touchmove",g.Sa(function(){this.Mu=!0}),this)};
g.h.mo=function(a,b,c,d,e,f){if(this.Mu)return!1;f&&(f.stopPropagation(),f.preventDefault());esa(this,a,c,d,e);return!1};
g.h.show=function(){};
g.h.hide=function(){};
g.h.destroy=function(){g.be(this.o)};
g.h.dn=function(){};
g.h.X=function(){this.ra.clear();this.na.clear();g.B.prototype.X.call(this)};g.r(q3,m3);g.h=q3.prototype;g.h.isAvailable=function(){var a;if(a=!!this.A.length)(a=g.eL(this.w))?(a=g.vh(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.dn=function(){var a=this.isAvailable();g.wh(this.o,a);g.L(g.eL(this.context.aa),"ytp-iv-drawer-enabled",a);H2(this.w)};
g.h.destroy=function(){var a=g.mL(g.$K(this.w));a&&a.As(!1,void 0);try{g.eL(this.w).removeChild(this.F)}catch(b){}g.Bo(this.V);g.hp(this.ea);this.ga&&this.ga.dispose();this.G&&this.G.dispose();m3.prototype.destroy.call(this)};
g.h.yH=function(a){this.Z.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.B.scrollTop+=a};
g.h.ZB=function(a){if(!g.pn(g.eL(this.w),"ytp-cards-teaser-shown")){if(this.u!=a){var b=g.Er(),c=this.u?this.u.card.xd:this.J;b&&c&&J2(b,[c]);this.u=a;u3(this)}if(b="none"!=this.o.style.display)2==this.context.aa.getPresentingPlayerType()?b=1==this.context.aa.getAdState():(b=this.context.aa.getPlayerState(),c=0==b&&0===this.context.aa.getCurrentTime(),b=1==b||3==b||c);b&&a.card.teaserDurationMs&&(b={teaserText:a.card.teaserText,durationMs:a.card.teaserDurationMs},(c=g.mL(g.$K(this.w)))&&c.As(!0,b));
this.ya.isActive()||((!this.C||!this.Z.isActive()&&this.da)&&osa(this,a),this.ya.start(910+a.card.teaserDurationMs))}};
g.h.UO=function(a){this.C||(this.u=a,u3(this),osa(this,a),o3(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1))};
g.h.yE=function(){if(this.C){f3(this.context.logger,v3(this).Jc.close);var a=g.Er();a&&this.O&&g.Vr(a,this.O);p3(this)}};
g.h.OE=function(){g.L(this.F,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.h.EG=function(){var a=g.Er(),b=v3(this);b=b?b.xd:this.J;a&&b&&I2(a,[b])};
g.h.DG=function(){var a=g.Er(),b=v3(this);b=b?b.xd:this.J;a&&b&&J2(a,[b])};
g.h.HG=function(){var a=v3(this);f3(this.context.logger,a.Jc.sC);var b=g.Er();b&&a&&I2(b,[a.Vd,a.xd])};
g.h.GG=function(){var a=g.Er(),b=v3(this);a&&b&&J2(a,[b.Vd])};
g.h.FG=function(a){var b=v3(this),c=g.Er();this.u?a?(a=this.context.logger,f3(a,b.Jc.Kp),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.Vd&&g.Vr(c,b.Vd)):(a=this.context.logger,f3(a,b.Jc.Kp),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.xd&&g.Vr(c,b.xd)):(a=this.context.logger,f3(a,b.Jc.Kp),a.o.sendVideoStatsEngageEvent(4,void 0),c&&this.J&&g.Vr(c,this.J))};g.r(w3,m3);w3.prototype.fm=function(){m3.prototype.fm.call(this);psa(this)};
w3.prototype.show=function(){m3.prototype.show.call(this);var a=g.Er(),b=this.annotation.data;a&&b&&(b=b.session_data)&&I2(a,[g.wr(b.itct)])};
w3.prototype.hide=function(){m3.prototype.hide.call(this);var a=g.Er(),b=this.annotation.data;a&&b&&(b=b.session_data)&&J2(a,[g.wr(b.itct)])};g.r(x3,w3);g.h=x3.prototype;g.h.eP=function(a,b,c,d){this.A.stop();if(!this.B){var e=g.vh(a);this.u||(g.th(a,e.width),g.th(b,e.width));g.ch(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.ch(c,"right","1px");this.B=!0;g.wh(a,!0);this.C=new g.J(function(){g.K(this.o,"iv-branding-active")},0,this);
this.C.start()}};
g.h.iG=function(a,b){g.rn(this.o,"iv-branding-active");this.F=new g.J((0,g.x)(function(){g.wh(a,!1);this.u||g.th(b,0)},this),250);
this.F.start();this.B=!1};
g.h.show=function(){if(!this.isActive){w3.prototype.show.call(this);if(!this.G){g.K(this.o,"iv-branding");var a=this.annotation.data;this.w=g.Wd("IMG",{"aria-label":"Channel watermark",src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.wh(this.w,!1);var b=g.Wd("DIV","branding-img-container",this.w);this.o.appendChild(b);(b=Sra(this.annotation))&&this.Sj(this.w,b,this.annotation.id,a.session_data);if(a.channel_name){var c=g.Wd("DIV","iv-branding-context-name");
g.fe(c,a.channel_name);var d=g.Wd("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.u=new g.cQ(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.aa),this.u.ba(d);b=g.Wd("DIV","iv-branding-context-subscribe-caret");c=g.Wd("DIV","branding-context-container-inner",b,c,d);g.wh(c,!1);d=g.Wd("DIV","branding-context-container-outer",c);g.ch(d,"right",
a.image_width+"px");this.o.appendChild(d);this.A=new g.J(g.Sa(this.iG,c,d),500,this);g.C(this,this.A);this.context.o.ha(this.o,"mouseover",(0,g.x)(this.eP,this,c,d,b,a.image_height));this.context.o.ha(this.o,"mouseout",(0,g.x)(this.A.start,this.A,void 0))}this.G=!0}g.wh(this.o,!0);this.isActive=!0;if(this.w){a=this.w;var e=void 0===e?0:e;b=g.oh(a);c=g.vh(a);b=(new g.$g(b.x,b.y,c.width,c.height)).width;g.kh(a,b);e=new P2(a,[b,a.offsetTop],[b-b-e,a.offsetTop],200,rra);g.C(this,e);this.context.w.ha(e,
"begin",g.Sa(g.wh,a,!0));e.play()}}};
g.h.hide=function(){this.isActive&&(w3.prototype.hide.call(this),g.wh(this.o,!1),this.isActive=!1)};
g.h.destroy=function(){this.u&&(this.u.dispose(),this.u=null);w3.prototype.destroy.call(this)};g.r(y3,w3);g.h=y3.prototype;g.h.show=function(){this.isActive||(w3.prototype.show.call(this),this.P||(qsa(this),this.P=!0),g.wh(this.o,!0),g.Df(function(){g.rn(this.o,"iv-promo-inactive")},100,this),this.o.removeAttribute("aria-hidden"),this.isActive=!0,z3(this),ssa(this),tsa(this,this.G))};
g.h.hide=function(){this.isActive&&(g.K(this.o,"iv-promo-inactive"),this.isActive=!1,this.o.setAttribute("aria-hidden",!0))};
g.h.mo=function(a,b,c,d,e,f){return this.C?!1:w3.prototype.mo.call(this,a,b,c,d,e,f)};
g.h.Er=function(a,b){b.stopPropagation();ssa(this);tsa(this,a);this.u.focus()};
g.h.NF=function(a){this.J=!0;this.Er(500,a)};
g.h.MF=function(){this.J=!1;rsa(this)};
g.h.EF=function(a){a.stopPropagation();this.hide()};
g.h.FF=function(a){a.stopPropagation();z3(this);this.C=!0;g.K(this.o,"iv-promo-collapsed-no-delay");this.F.start()};
g.h.destroy=function(){this.F.dispose();w3.prototype.destroy.call(this)};g.r(A3,g.LL);g.h=A3.prototype;g.h.Nc=function(a,b){if(!wsa(this.player.N().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.P1(b);c&&B3(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(jsa(this.o,b),H2(this.player)),!0}return null};
g.h.getOptions=function(){return wsa(this.player.N().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.cp=function(){if(this.A){var a=g.dL(this.player).getVideoContentRect(!0);g.uh(this.A.element,a.width,a.height);g.kh(this.A.element,a.left,a.top)}if(this.o){var b=g.pL(this.player);a=this.o;b=b.width;g.L(a.F,"iv-drawer-small",426>=b);g.L(a.F,"iv-drawer-big",1280<=b)}};
g.h.DM=function(a){this.qc(a.state);g.X(a.state,2)&&(this.ql()&&this.Ly()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.As(!1))};
g.h.load=function(){g.LL.prototype.load.call(this);this.qc(g.gL(this.player));this.H++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.x)(this.sL,this,b,this.H),d=(0,g.x)(function(){this.C=null},this);
g.xp()&&(c=Asa(this,c));c={format:"XML",fd:c,onError:d,Yd:{}};a.isPharma&&(c.Yd.pharma="1");c.method="POST";c.withCredentials=!0;(b=this.player.N().F.get(b))&&Bsa(c,b);b=b&&(b.jn||b.hn);if(!a.Tm||b)a.Zd?xsa(this,a.Zd,c):(this.w=(0,g.x)(this.iH,this,c),this.player.addEventListener("videodatachange",this.w));g.yL(this.player,this.A.element,4);this.cp();(b=g.jC(a))&&Gsa(this,b);(b=g.kC(a))&&b.featuredChannel&&Hsa(this,b.featuredChannel,b.annotationId||"branding",a.videoId||null,a.eventId||null)};
g.h.qc=function(a){a=!a.isCued()&&!g.X(a,1024);g.ku(this.u,a);g.ku(this.A,a)};
g.h.iH=function(a){var b=this.player.getVideoData();b.Zd&&(this.w&&(this.player.removeEventListener("videodatachange",this.w),this.w=null),xsa(this,b.Zd,a))};
g.h.unload=function(){g.NQ(this.player.app,"annotations_module",void 0);g.A.forEach(this.F,function(a){a.destroy()});
this.G=null;this.o&&(this.o.destroy(),this.o=null,H2(this.player));this.J=!1;this.C&&(this.C.abort(),this.C=null);this.F={};this.u.hide();g.LL.prototype.unload.call(this);g.hu(this.A);this.w&&(this.player.removeEventListener("videodatachange",this.w),this.w=null)};
g.h.sL=function(a,b,c){this.C=null;!zsa(this,b,a)&&(a=g.$p(c)&&c.responseXML?c.responseXML:null)&&(B3(this,a),g.K(g.eL(this.player),"iv-module-loaded"))};
g.h.gB=function(a){a==this.player.getVideoData().videoId&&(this.loaded?Csa(this):this.load())};
g.h.ql=function(){return!!this.o&&this.o.isAvailable()};
g.h.Ly=function(){this.ql();return!!this.o&&this.o.C};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.ql();this.o&&(a?c?o3(this.o,c,b):o3(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):p3(this.o))};
g.h.As=function(a,b){this.player.S(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.X=function(){this.player.N().F.unsubscribe("vast_info_card_add",this.gB,this);g.rn(g.eL(this.player),"ytp-iv-drawer-open");for(var a=this.P,b=0,c=a.length;b<c;b++)g.yp(a[b]);this.P.length=0;g.LL.prototype.X.call(this)};g.$L.annotations_module=A3;g.$L.creatorendscreen=U2;})(_yt_player);
