(function(g){var window=this;var V4=function(a,b,c){var d=b.xa();g.L(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.Ec(c?c:"mqdefault.jpg");var f=b instanceof g.CB&&b.lengthSeconds?g.bM(b.lengthSeconds):null,k=!!e;e=k&&"RD"===(new g.JD(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.CB?b.va:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.kk||g.LM("Watch $TITLE",{TITLE:b.title}),duration:f,url:b.ai(),is_live:l,is_list:k,
is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.KD&&(d.playlist_length=b.getLength());a.update(d)},W4=function(a){g.S.call(this,{D:"div",
Y:["ytp-upnext","ytp-player-content"],M:{"aria-label":"{{aria_label}}"},K:[{D:"div",I:"ytp-cued-thumbnail-overlay-image",M:{style:"{{background}}"}},{D:"span",I:"ytp-upnext-top",K:[{D:"span",I:"ytp-upnext-header",W:"Up Next"},{D:"span",I:"ytp-upnext-title",W:"{{title}}"},{D:"span",I:"ytp-upnext-author",W:"{{author}}"}]},{D:"a",I:"ytp-upnext-autoplay-icon",M:{role:"button",href:"{{url}}","aria-label":"Play next video"},K:[{D:"svg",M:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},K:[{D:"circle",
I:"ytp-svg-autoplay-circle",M:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{D:"circle",I:"ytp-svg-autoplay-ring",M:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{D:"path",I:"ytp-svg-fill",M:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{D:"span",I:"ytp-upnext-bottom",K:[{D:"span",I:"ytp-upnext-cancel"},{D:"span",I:"ytp-upnext-paused",W:"Autoplay is paused"}]}]});
this.B=null;var b=this.o["ytp-upnext-cancel"];this.B=new g.S({D:"button",Y:["ytp-upnext-cancel-button","ytp-button"],M:{tabindex:"0","aria-label":"Cancel autoplay"},W:"Cancel"});g.C(this,this.B);this.B.ha("click",this.PK,this);this.B.ba(b);this.u=a;this.J=this.o["ytp-svg-autoplay-ring"];this.F=this.C=this.w=this.A=null;this.G=new g.J(this.on,5E3,this);g.C(this,this.G);this.H=0;g.AL(this.u,this.element,this,18788);this.L(this.o["ytp-upnext-autoplay-icon"],"click",this.yM);this.wA();this.L(a,"autonavvisibility",
this.wA);this.L(a,"mdxnowautoplaying",this.QL);this.L(a,"mdxautoplaycanceled",this.RL);this.L(a,"mdxautoplayupnext",this.QC);3==this.u.getPresentingPlayerType()&&(a=(a=g.hL(g.$K(this.u)))?a.uF():null)&&this.QC(a);g.L(this.element,"ytp-upnext-mobile",this.u.N().o)},X4=function(a,b){if(!a.w){g.Co("a11y-announce","Up Next "+a.A.title);
a.H=(0,g.O)();a.w=new g.J((0,g.x)(a.uq,a,b),25);a.uq(b);var c=b||g.U(a.u.N().experiments,"autoplay_time")||1E4;a.u.ma("onAutonavCoundownStarted",c)}g.rn(a.element,"ytp-upnext-autoplay-paused")},Z4=function(a){Y4(a);
a.H=(0,g.O)();a.uq();g.K(a.element,"ytp-upnext-autoplay-paused")},Y4=function(a){a.w&&(a.w.dispose(),a.w=null)},$4=function(a,b){b=void 0===b?!1:b;
if(g.T(a.u.N().experiments,"autonav_notifications")&&b&&window.Notification&&document.hasFocus){var c=Notification.permission;"default"==c?Notification.requestPermission():"granted"!=c||document.hasFocus()||(c=a.A.xa(),a.on(),a.C=new Notification("Up Next",{body:c.title,icon:c.Ec()}),a.F=a.L(a.C,"click",a.pM),a.G.start())}Y4(a);a.u.nextVideo(!1,b)},a5=function(a,b){g.S.call(this,{D:"div",
Y:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},Wta=function(a){a5.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.u=new g.S({D:"div",I:"ytp-subscribe-card",K:[{D:"img",I:"ytp-author-image",M:{src:b.Rd}},{D:"div",I:"ytp-subscribe-card-right",K:[{D:"div",I:"ytp-author-name",W:b.author},{D:"div",I:"html5-subscribe-button-container"}]}]});g.C(this,this.u);this.u.ba(this.element);this.subscribeButton=new g.cQ("Subscribe",null,"Unsubscribe",null,!0,!1,b.Bg,b.subscribed,"trailer-endscreen",null,null,a);g.C(this,this.subscribeButton);this.subscribeButton.ba(this.u.o["html5-subscribe-button-container"]);
this.hide()},b5=function(a){var b=a.N(),c=g.Xs||g.fh?{style:"will-change: opacity"}:void 0,d=b.u,e=["ytp-videowall-still"];
b.o&&e.push("ytp-videowall-show-text");g.S.call(this,{D:"a",Y:e,M:{href:"{{url}}",target:d?b.A:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},K:[{D:"div",I:"ytp-videowall-still-image",M:{style:"{{background}}"}},{D:"span",I:"ytp-videowall-still-info",K:[{D:"span",I:"ytp-videowall-still-info-bg",K:[{D:"span",I:"ytp-videowall-still-info-content",M:c,K:[{D:"span",I:"ytp-videowall-still-info-title",W:"{{title}}"},{D:"span",I:"ytp-videowall-still-info-author",
W:"{{author_and_views}}"},{D:"span",I:"ytp-videowall-still-info-live",W:"Live"},{D:"span",I:"ytp-videowall-still-info-duration",W:"{{duration}}"}]}]}]},{D:"span",Y:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],K:[{D:"span",I:"ytp-videowall-still-listlabel-icon"},"Playlist",{D:"span",I:"ytp-videowall-still-listlabel-length",K:[" (",{D:"span",W:"{{playlist_length}}"},")"]}]},{D:"span",Y:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],K:[{D:"span",I:"ytp-videowall-still-listlabel-mix-icon"},
"Mix",{D:"span",I:"ytp-videowall-still-listlabel-length",W:" (50+)"}]}]});this.suggestion=null;this.w=d;this.api=a;this.u=new g.P(this);g.C(this,this.u);this.ha("click",this.onClick);this.ha("keypress",this.B);this.u.L(a,"videodatachange",this.A);g.BL(a,this.element,this);this.A()},Xta=function(a){var b=a.suggestion.xa().videoId,c=a.suggestion.getPlaylistId();
(g.zT(a.api.app,b,a.suggestion.Nb,c,void 0,void 0)||a.api.fa("web_player_endscreen_double_log_fix_killswitch"))&&g.DL(a.api,a.element)},c5=function(a){a5.call(this,a,"videowall-endscreen");
var b=this;this.aa=a;this.A=0;this.stills=[];this.B=this.videoData=this.suggestions=null;this.C=this.H=!1;this.G=null;this.w=new g.P(this);g.C(this,this.w);this.F=new g.J(function(){g.K(b.element,"ytp-show-tiles")},0);
g.C(this,this.F);var c=new g.S({D:"button",Y:["ytp-button","ytp-endscreen-previous"],M:{"aria-label":"Previous"},K:[g.jM()]});g.C(this,c);c.ba(this.element);c.ha("click",this.JH,this);this.table=new g.gu({D:"div",I:"ytp-endscreen-content"});g.C(this,this.table);this.table.ba(this.element);c=new g.S({D:"button",Y:["ytp-button","ytp-endscreen-next"],M:{"aria-label":"Next"},K:[g.kM()]});g.C(this,c);c.ba(this.element);c.ha("click",this.IH,this);this.u=new W4(a);g.C(this,this.u);g.yL(this.player,this.u.element,
4);this.hide()},d5=function(a){return g.zL(a.player)&&a.cw()&&!a.B},Yta=function(a,b){return(0,g.jc)(b.suggestions,function(c){c=g.qO(a.aa.N(),c);
g.C(a,c);return c})},e5=function(a){var b=a.Is();
b!==a.H&&(a.H=b,a.player.S("autonavvisibility"))},f5=function(a){g.LL.call(this,a);
this.endScreen=null;this.listeners=new g.P(this);g.C(this,this.listeners);this.o=a.N();Zta(a)?this.endScreen=new c5(this.player):this.o.Ga?this.endScreen=new Wta(this.player):this.endScreen=new a5(this.player);g.C(this,this.endScreen);g.yL(this.player,this.endScreen.element,4);this.SB();this.listeners.L(a,"videodatachange",this.SB,this);this.listeners.L(a,g.ID("endscreen"),this.GH,this);this.listeners.L(a,"crx_endscreen",this.hL,this)},Zta=function(a){a=a.N();
return a.Ea&&!a.Ga};
g.r(W4,g.S);g.h=W4.prototype;g.h.on=function(){this.C&&(this.G.stop(),this.Va(this.F),this.F=null,this.C.close(),this.C=null)};
g.h.wA=function(){g.ku(this,g.aL(this.u));g.EL(this.u,this.element,g.aL(this.u))};
g.h.pM=function(){window.focus();this.on()};
g.h.hide=function(){g.S.prototype.hide.call(this)};
g.h.uq=function(a){a=a||g.U(this.u.N().experiments,"autoplay_time")||1E4;var b=Math.min((0,g.O)()-this.H,a);a=Math.min(b/a,1);this.J.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.u.getPresentingPlayerType()?$4(this,!0):this.w&&this.w.start()};
g.h.yM=function(a){!g.ee(this.B.element,g.ip(a))&&g.RM(a,this.u)&&$4(this)};
g.h.PK=function(){g.cL(this.u,!0)};
g.h.QL=function(a){this.u.getPresentingPlayerType();this.show();X4(this,a)};
g.h.QC=function(a){this.u.getPresentingPlayerType();this.A&&this.A.xa().videoId==a.xa().videoId||(this.A=a,V4(this,a,"hqdefault.jpg"))};
g.h.RL=function(){this.u.getPresentingPlayerType();Y4(this);this.hide()};
g.h.X=function(){Y4(this);this.on();g.S.prototype.X.call(this)};g.r(a5,g.S);g.h=a5.prototype;g.h.create=function(){this.created=!0};
g.h.destroy=function(){this.created=!1};
g.h.cw=function(){return!1};
g.h.Is=function(){return!1};
g.h.oy=function(){return!1};g.r(Wta,a5);g.r(b5,g.S);b5.prototype.onClick=function(a){g.RM(a,this.api,this.w,this.suggestion.Nb||void 0)&&Xta(this)};
b5.prototype.B=function(a){switch(a.keyCode){case 13:case 32:g.np(a)||(Xta(this),g.mp(a))}};
b5.prototype.A=function(){var a=this.api.getVideoData(),b=this.api.N();this.w=a.zc?!1:b.u};g.r(c5,a5);g.h=c5.prototype;g.h.create=function(){a5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.suggestions=Yta(this,a),this.videoData=a);this.vg();this.w.L(this.player,"appresize",this.vg);this.w.L(this.player,"onVideoAreaChange",this.vg);this.w.L(this.player,"videodatachange",this.KH);this.w.L(this.player,"autonavchange",this.Js);this.w.L(this.player,"autonavcancel",this.HH);a=this.videoData.autonavState;a!==this.G&&this.Js(a);this.w.L(this.element,"transitionend",this.RN)};
g.h.destroy=function(){g.gr(this.w);g.pe(this.stills);this.stills=[];this.suggestions=null;a5.prototype.destroy.call(this);g.rn(this.element,"ytp-show-tiles");this.F.stop();this.G=this.videoData.autonavState};
g.h.cw=function(){return 1!==this.videoData.autonavState};
g.h.show=function(){a5.prototype.show.call(this);g.rn(this.element,"ytp-show-tiles");this.player.N().o?g.gn(this.F):this.F.start();(this.C||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.cL(this.player,!1);d5(this)?(e5(this),2===this.videoData.autonavState?g.T(this.player.N().experiments,"fast_autonav_in_background")&&3===this.player.getVisibilityState()?$4(this.u,!0):X4(this.u):3===this.videoData.autonavState&&Z4(this.u)):(g.cL(this.player,!0),e5(this))};
g.h.hide=function(){a5.prototype.hide.call(this);Z4(this.u);e5(this)};
g.h.RN=function(a){g.ip(a)===this.element&&this.vg()};
g.h.vg=function(){if(this.suggestions&&this.suggestions.length){g.K(this.element,"ytp-endscreen-paginate");var a=g.pL(this.aa,!0,this.aa.isFullscreen()),b=g.EC(this.aa);b&&(b=b.jc()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var q=b/2,t=e/2,u=b<=f-2&&n>=t*m,z=e<=k-2&&n>=q*m;if((q+1)/t*d/c>c/(q/(t+1)*d)&&z)n-=q*m,e+=2;else if(u)n-=
t*m,b+=2;else if(z)n-=q*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.ud(a.width/m||1,1,1.21);n*=g.ud(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.table.element;g.uh(a,m,n);g.ch(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.u;f=this.suggestions[0];c.A=f;V4(c,f,"hqdefault.jpg");g.L(this.element,"ytp-endscreen-takeover",d5(this));e5(this);m+=4;n+=4;for(f=
c=0;f<b;f++)for(k=0;k<e;k++)if(q=c,t=0,d&&f>=b-2&&k>=e-2?t=1:0===k%2&&0===f%2&&(2>k&&2>f?0===k&&0===f&&(t=2):t=2),q=g.vd(q+this.A,l),0!==t){u=this.stills[c];u||(u=new b5(this.player),this.stills[c]=u,a.appendChild(u.element));z=Math.floor(n*k/e);var D=Math.floor(m*f/b),E=Math.floor(n*(k+t)/e)-z-4,F=Math.floor(m*(f+t)/b)-D-4;g.kh(u.element,D,z);g.uh(u.element,F,E);g.ch(u.element,"transitionDelay",(k+f)/20+"s");g.L(u.element,"ytp-videowall-still-mini",1===t);g.L(u.element,"ytp-videowall-still-large",
2<t);t=u;q=this.suggestions[q];t.suggestion!==q&&(t.suggestion=q,u=t.api.N(),z=g.pn(t.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",V4(t,q,z),g.gy(u)&&(u=q.ai(),u=g.gd(u,g.pD({},"emb_rel_end")),t.ia("url",u)),(q=(q=q.Nb)&&q.itct)&&g.CL(t.api,t.element,q));c++}g.L(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.be(e.element),g.oe(e);this.stills.length=c}};
g.h.KH=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.A=0,this.suggestions=Yta(this,a),this.videoData=a,this.vg())};
g.h.IH=function(){this.A+=this.stills.length;this.vg()};
g.h.JH=function(){this.A-=this.stills.length;this.vg()};
g.h.oy=function(){return!!this.u.w};
g.h.Js=function(a){1===a?(this.C=!1,this.B=this.videoData.clientPlaybackNonce,Y4(this.u),this.Ha()&&this.vg()):(this.C=!0,this.Ha()&&d5(this)&&(2===a?X4(this.u):3===a&&Z4(this.u)))};
g.h.HH=function(a){if(a){for(a=0;a<this.stills.length;a++)g.EL(this.aa,this.stills[a].element,!0);this.Js(1)}else this.B=null,this.C=!1;this.vg()};
g.h.Is=function(){return this.Ha()&&d5(this)};g.r(f5,g.LL);g.h=f5.prototype;g.h.Ny=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!Zta(this.player)||b;var c=a.Qi||g.py(a.Na),d=g.TS(this.player.app);a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.h.My=function(){return this.endScreen.Is()};
g.h.rG=function(){return this.My()?this.endScreen.oy():!1};
g.h.X=function(){g.NQ(this.player.app,"endscreen",void 0);g.LL.prototype.X.call(this)};
g.h.load=function(){g.LL.prototype.load.call(this);this.endScreen.show()};
g.h.unload=function(){g.LL.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.h.GH=function(a){this.Ny()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.h.hL=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.h.SB=function(){g.NQ(this.player.app,"endscreen",void 0);var a=this.player.getVideoData();a=new g.FD(Math.max(1E3*(a.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var b=new g.FD(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.uL(this.player,[a,b])};g.$L.endscreen=f5;})(_yt_player);
