(function(g){var window=this;var m_=function(a){var b=a.itemData.itemId,c=a.config.flowType,d=a.offerData?a.offerData.offerId:null,e=a.innertubeRequestParams,f=a.transactionAction,k={};k.ypc_it=a.itemData.itemType;k.ypc_ii=b;k.ypc_ft=c;e&&(k.ypc_irp=e);d&&(k.ypc_oi=d);f&&(k.ypc_ta=f);return k},p_=function(){var a=n_,b=g.z("legacy-history-iframe");
this.G=this.D=this.C=null;this.F=a;this.L=o_?b:null;this.J=window;this.H=this.J.location;this.Y=this.H.href.split("#")[0];this.N=(0,g.v)(this.M,this)},q_=function(a){a=a.H.href;
var b=a.indexOf("#");return 0>b?"":a.substring(b+1)},r_=function(a,b){var c=a.Y+"#"+b,d=a.H.href;
d!=c&&d+"#"!=c&&g.fc(a.H,c)},s_=function(a,b){var c=a.L.contentWindow.document,d=c.body?c.body.innerHTML:"",e="#"+g.gc(b);
d!=e&&(d=g.Bn(g.Dn("title",{},window.document.title||""),g.Dn("body")),c.open("text/html"),c.write(g.Zb(d)),g.N(c.body,e),c.close())},t_=function(){var a=n_;
this.H=this.L=this.C=null;this.D=a;this.G=window;this.F=this.G.location;this.N=(0,g.v)(this.J,this)},Cqa=function(){var a=u_("state");
a.setEnabled.call(a,!0,!0)},Dqa=function(a){var b=null,c=u_();
b=b||window.history&&window.history.state;c.replace.call(c,a,b,!0)},u_=function(a){var b=g.u("ytglobal.HistoryHistoryInstance");
b||("state"==(void 0===a?"hash":a)?(b=new t_,t_.prototype.setEnabled=t_.prototype.rb,t_.prototype.add=t_.prototype.add,t_.prototype.replace=t_.prototype.replace):(b=new p_,p_.prototype.setEnabled=p_.prototype.rb,p_.prototype.add=p_.prototype.add,p_.prototype.replace=p_.prototype.add),g.r("ytglobal.HistoryHistoryInstance",b,void 0));return b},n_=function(a,b){g.H("navigate",a,b)},x_=function(a){var b=g.E("YPC_LOADER_CSS",void 0),c=g.E("YPC_LOADER_JS",void 0);
v_&&(c="www/ypc_core");w_.length||(w_.push(new g.He(function(d){g.ij(b,d)})),w_.push(new g.He(function(d){g.ig(c,d)})));
g.Ne(w_).then(function(){a&&a()})},z_=function(a,b,c,d,e){if(g.cE())x_(function(){g.u("yt.ypc.checkout.showYpcOverlay")(a,b,c,d,e)});
else{var f={ypc_it:a,ypc_ii:b,ypc_ft:c};d&&(f.ypc_irp=d);e&&(f.ypc_cc=e);f=y_(f);g.pj(f)}},Eqa=function(a){if(g.cE())x_(function(){g.u("yt.ypc.checkout.showPrepurchaseOverlay")(a)});
else{var b=y_({});g.pj(b)}},A_=function(a,b){if(g.cE())x_(function(){g.u("yt.ypc.checkout.showYpcOverlayForInnertubeRequestParams")(a,b)});
else{var c=y_({ypc_ft:a,ypc_irp:b});g.pj(c)}},B_=function(a,b,c){g.cE()?x_(function(){g.u("yt.ypc.checkout.offerpurchaser.purchaseOffer")(a,c)}):(b=y_(b),g.pj(b))},C_=function(a,b){if(g.cE())x_(function(){g.u("yt.ypc.subscription.openUnsubscribeOverlay")(a,b)});
else throw Error("Unsubscribe triggered when user not signed in.");},y_=function(a){a=g.Dg(window.location.href,a);
var b=g.E("YPC_SIGNIN_URL",void 0),c=g.Iq(b)["continue"];c=g.Dg(c,{next:a});return g.Dg(b,{"continue":c})},Fqa=function(a){if(a=a.currentTarget)D_(a),(a=g.F(a,"ytr-prepurchase-html"))&&Eqa(g.Kn(a))},Gqa=function(a){var b=a.currentTarget;
if(b)if(a=g.F(b,"ypc-transaction-action"),b=g.xO(b,"D")){if(b.gtmData){var c=JSON.parse(b.gtmData);c&&(window.dataLayer=window.dataLayer||[],window.dataLayer.push(c))}(a="start_payment"==a)&&E_("inline-offer-button-click",b.itemData);B_(b,m_(b),a);setTimeout(g.Dh,0)}else g.Rf(Error("ypc-offer-button does not contain purchaseFlowData."))},Hqa=function(a){(a=a.currentTarget)&&F_(a)},Iqa=function(a){x_(a.callback)},Jqa=function(a){E_("container-button-click-attempt");
var b=g.M("ypc-checkout-button",a.container);(a=g.M("ytr-purchase-button",a.container))?(b=g.D(a,"ypc-offer-button"),(a.href||b)&&a.click()):b&&F_(b)},Kqa=function(a){var b=a.C;
a=b.itemId;var c=b.itemType;b=b.flowType;E_("paid-subscribe-button-click",{itemType:c,itemId:a});z_(c,a,b)},F_=function(a){var b=g.F(a,"ypc-item-type"),c=g.F(a,"ypc-item-id"),d=g.F(a,"ypc-flow-type");
a=g.F(a,"ypc-irp")||void 0;g.cE()?E_("purchase-button-click",{itemId:c,itemType:b}):E_("signin-button-click");z_(b,c,d,a)},G_=function(a){var b=a.currentTarget;
a=g.F(b,"ypc-item-type");b=g.F(b,"ypc-item-id");a&&b&&(E_("unsubscribe-button-click",{itemId:b,itemType:a}),C_(a,b))},Lqa=function(a){var b=a.C;
a=b.itemType;b=b.itemId;E_("paid-unsubscribe-button-click",{itemType:a,itemId:b});C_(a,b)},E_=function(a,b){var c={};
g.sb(c,{label:a,pageName:g.E("PAGE_NAME")});b&&g.sb(c,b);g.Er("ypc-checkout",g.qd(c))},D_=function(a){var b;
g.D(a,"yt-unlimited-more-offer-button")?b="YTO_GTM_2_BUTTON_CLICK_DATA":g.D(a,"ypc-offer-button")&&(b="YTO_GTM_1_BUTTON_CLICK_DATA");b&&(a=g.E(b,""))&&(window.dataLayer=window.dataLayer||[],window.dataLayer.push(a))},Mqa=function(a){a=a.currentTarget;
var b=g.F(a,"tab-id");if(b){for(var c=g.L("offer-module-tab-content"),d=0;d<c.length;d++)c[d].classList.remove("active-tab");c=g.L("offer-module-tab");for(d=0;d<c.length;d++)c[d].classList.remove("active-tab");g.z(b).classList.add("active-tab");a.classList.add("active-tab")}},Nqa=function(a){if(a=a.currentTarget){D_(a);
var b=g.xO(a,"U");b?(x_(function(){g.u("yt.ypc.checkout.offerpurchaser.completeTransaction")(b)}),setTimeout(g.Dh,0)):g.Rf(Error("ypc-complete-transaction-button does not contain purchaseFlowData"))}},Oqa=function(a){a=a.currentTarget;
var b=g.F(a,"feedback-token");b&&(a={itct:g.F(a,"innertube-clicktracking"),feedback_tokens:[b],wait_for_response:1},g.I("/feed_change_ajax?action_give_feedback=1",{method:"POST",onSuccess:function(c,d){if(d&&d.actions){var e=d.actions.url_endpoint.url,f=window,k=g.Cb("_self");e=e instanceof g.Kb?e:g.Qb(e);(f||g.p).open(g.Lb(e),k?g.Bb(k):"",void 0,void 0)}},
ia:a}))},Qqa=function(){var a=g.Iq(window.location.href);
if(H_){g.ib(Pqa,function(c){g.mb(a,c)});
var b=g.rd(window.location.href.split("?",2)[0],a);Cqa();Dqa(b)}},I_=g.Df&&8<=document.documentMode||g.Ul&&g.sc("1.9.2")||g.Vl&&g.sc("532.1"),o_=g.Df&&!I_;
p_.prototype.rb=function(a,b){this.D&&(g.nh(this.D),delete this.D);this.G&&(g.Zf(this.G),delete this.G);if(a){this.C=q_(this);if(o_){var c=this.L.contentWindow.document.body;c&&c.innerHTML||s_(this,this.C)}b||this.F(this.C);I_?this.D=g.J(this.J,"hashchange",this.N):this.G=g.Xf(this.N,200)}};
p_.prototype.M=function(){if(o_){var a=(a=this.L.contentWindow.document.body)?g.hc(g.cp(a).substring(1)):"";a!=this.C?(this.C=a,r_(this,a),this.F(a)):(a=q_(this),a!=this.C&&(this.C=a,s_(this,a),this.F(a)))}else a=q_(this),a!=this.C&&(this.C=a,this.F(a))};
p_.prototype.add=function(a,b,c){this.C=""+a;o_&&s_(this,a);r_(this,a);c||this.F(this.C)};t_.prototype.rb=function(a,b){this.H&&(g.nh(this.H),delete this.H);this.L&&(g.Zf(this.L),delete this.L);a&&H_&&(this.C=this.F.href,b||this.D(this.C),this.H=g.J(this.G,"popstate",this.N))};
t_.prototype.J=function(a){var b=this.F.href;if((a=a.state)||b!=this.C)this.C=b,this.D(b,a)};
t_.prototype.add=function(a,b,c){if(a||b)a=a||this.F.href,this.G.history.pushState(b,"",a),this.C=a,c||this.D(a,b)};
t_.prototype.replace=function(a,b,c){if(a||b)a=a||this.F.href,this.G.history.replaceState(b,"",a),this.C=a,c||this.D(a,b)};
var H_=!!window.history.pushState&&(!g.Vl||g.Vl&&g.sc("534.11"));var w_=[],v_=!1;var J_=[],K_=[];var Pqa={uK:"ypc_cc",UK:"ypc_ft",qL:"ypc_irp",tL:"ypc_ii",uL:"ypc_it"};g.aj(g.ur({name:"www/ypc_bootstrap",deps:["www/common"],page:"feed index results watch channel playlist subscription_manager unlimited live_chat live_dashboard".split(" "),init:function(){v_=!0;g.M("ypc-delayedloader-target")&&x_();var a=g.Iq(window.location.href),b=a.ypc_it,c=a.ypc_ii,d=a.ypc_ft||"D",e=a.ypc_oi,f=a.ypc_irp,k=a.ypc_cc,l=a.ypc_ta;"channel"==g.E("PAGE_NAME")&&"ypc_cc"in a&&(b="U",c=g.E("CHANNEL_ID",void 0));if(f||c&&b)Qqa(),"start_payment"==l?(a=g.wO(e,b,c,d,k,null,"","",f,l),B_(a,
m_(a),!0)):c&&b?z_(b,c,d,f,k):A_(d,f);J_.push(g.S(document.body,"click",Hqa,"ypc-checkout-button"),g.S(document.body,"click",Gqa,"ypc-offer-button"),g.S(document.body,"click",Nqa,"ypc-complete-transaction-button"),g.S(document.body,"click",Fqa,"ytr-pre-purchase-button"),g.S(document.documentElement,"click",G_,"ypc-unsubscribe-link"),g.S(document.documentElement,"click",G_,"ypc-unsubscribe-button"),g.S(document.documentElement,"click",Mqa,"offer-module-tab"),g.S(document.documentElement,"click",Oqa,
"yt-unlimited-more-offer-button"));K_.push(g.Pi(g.bF,Iqa),g.Pi(g.UP,Jqa),g.Pi(g.cF,Kqa),g.Pi(g.fF,Lqa))},
dispose:function(){w_.length=0;g.nh(J_);J_.length=0;g.Qi(K_);K_.length=0}}));
g.r("yt.ypc.bootstrap.api.loadOffers",z_,void 0);g.r("yt.ypc.bootstrap.api.loadOffersForInnertubeRequestParams",A_,void 0);})(_yt_www);
