(function(g){var window=this;var j_=function(a){var b=a.itemData.itemId,c=a.config.flowType,d=a.offerData?a.offerData.offerId:null,e=a.innertubeRequestParams,f=a.transactionAction,k={};k.ypc_it=a.itemData.itemType;k.ypc_ii=b;k.ypc_ft=c;e&&(k.ypc_irp=e);d&&(k.ypc_oi=d);f&&(k.ypc_ta=f);return k},m_=function(){var a=k_,b=g.z("legacy-history-iframe");
this.G=this.D=this.C=null;this.F=a;this.L=l_?b:null;this.J=window;this.H=this.J.location;this.Y=this.H.href.split("#")[0];this.N=(0,g.v)(this.M,this)},n_=function(a){a=a.H.href;
var b=a.indexOf("#");return 0>b?"":a.substring(b+1)},o_=function(a,b){var c=a.Y+"#"+b,d=a.H.href;
d!=c&&d+"#"!=c&&g.ec(a.H,c)},p_=function(a,b){var c=a.L.contentWindow.document,d=c.body?c.body.innerHTML:"",e="#"+g.fc(b);
d!=e&&(d=g.zn(g.Bn("title",{},window.document.title||""),g.Bn("body")),c.open("text/html"),c.write(g.Yb(d)),g.N(c.body,e),c.close())},q_=function(){var a=k_;
this.H=this.L=this.C=null;this.D=a;this.G=window;this.F=this.G.location;this.N=(0,g.v)(this.J,this)},Bqa=function(){var a=r_("state");
a.setEnabled.call(a,!0,!0)},Cqa=function(a){var b=null,c=r_();
b=b||window.history&&window.history.state;c.replace.call(c,a,b,!0)},r_=function(a){var b=g.u("ytglobal.HistoryHistoryInstance");
b||("state"==(void 0===a?"hash":a)?(b=new q_,q_.prototype.setEnabled=q_.prototype.rb,q_.prototype.add=q_.prototype.add,q_.prototype.replace=q_.prototype.replace):(b=new m_,m_.prototype.setEnabled=m_.prototype.rb,m_.prototype.add=m_.prototype.add,m_.prototype.replace=m_.prototype.add),g.r("ytglobal.HistoryHistoryInstance",b,void 0));return b},k_=function(a,b){g.H("navigate",a,b)},u_=function(a){var b=g.E("YPC_LOADER_CSS",void 0),c=g.E("YPC_LOADER_JS",void 0);
s_&&(c="www/ypc_core");t_.length||(t_.push(new g.Le(function(d){g.gj(b,d)})),t_.push(new g.Le(function(d){g.gg(c,d)})));
g.Re(t_).then(function(){a&&a()})},w_=function(a,b,c,d,e){if(g.aE())u_(function(){g.u("yt.ypc.checkout.showYpcOverlay")(a,b,c,d,e)});
else{var f={ypc_it:a,ypc_ii:b,ypc_ft:c};d&&(f.ypc_irp=d);e&&(f.ypc_cc=e);f=v_(f);g.nj(f)}},Dqa=function(a){if(g.aE())u_(function(){g.u("yt.ypc.checkout.showPrepurchaseOverlay")(a)});
else{var b=v_({});g.nj(b)}},x_=function(a,b){if(g.aE())u_(function(){g.u("yt.ypc.checkout.showYpcOverlayForInnertubeRequestParams")(a,b)});
else{var c=v_({ypc_ft:a,ypc_irp:b});g.nj(c)}},y_=function(a,b,c){g.aE()?u_(function(){g.u("yt.ypc.checkout.offerpurchaser.purchaseOffer")(a,c)}):(b=v_(b),g.nj(b))},z_=function(a,b){if(g.aE())u_(function(){g.u("yt.ypc.subscription.openUnsubscribeOverlay")(a,b)});
else throw Error("Unsubscribe triggered when user not signed in.");},v_=function(a){a=g.Bg(window.location.href,a);
var b=g.E("YPC_SIGNIN_URL",void 0),c=g.Gq(b)["continue"];c=g.Bg(c,{next:a});return g.Bg(b,{"continue":c})},Eqa=function(a){if(a=a.currentTarget)A_(a),(a=g.F(a,"ytr-prepurchase-html"))&&Dqa(g.In(a))},Fqa=function(a){var b=a.currentTarget;
if(b)if(a=g.F(b,"ypc-transaction-action"),b=g.vO(b,"D")){if(b.gtmData){var c=JSON.parse(b.gtmData);c&&(window.dataLayer=window.dataLayer||[],window.dataLayer.push(c))}(a="start_payment"==a)&&B_("inline-offer-button-click",b.itemData);y_(b,j_(b),a);setTimeout(g.Bh,0)}else g.Pf(Error("ypc-offer-button does not contain purchaseFlowData."))},Gqa=function(a){(a=a.currentTarget)&&C_(a)},Hqa=function(a){u_(a.callback)},Iqa=function(a){B_("container-button-click-attempt");
var b=g.M("ypc-checkout-button",a.container);(a=g.M("ytr-purchase-button",a.container))?(b=g.C(a,"ypc-offer-button"),(a.href||b)&&a.click()):b&&C_(b)},Jqa=function(a){var b=a.C;
a=b.itemId;var c=b.itemType;b=b.flowType;B_("paid-subscribe-button-click",{itemType:c,itemId:a});w_(c,a,b)},C_=function(a){var b=g.F(a,"ypc-item-type"),c=g.F(a,"ypc-item-id"),d=g.F(a,"ypc-flow-type");
a=g.F(a,"ypc-irp")||void 0;g.aE()?B_("purchase-button-click",{itemId:c,itemType:b}):B_("signin-button-click");w_(b,c,d,a)},D_=function(a){var b=a.currentTarget;
a=g.F(b,"ypc-item-type");b=g.F(b,"ypc-item-id");a&&b&&(B_("unsubscribe-button-click",{itemId:b,itemType:a}),z_(a,b))},Kqa=function(a){var b=a.C;
a=b.itemType;b=b.itemId;B_("paid-unsubscribe-button-click",{itemType:a,itemId:b});z_(a,b)},B_=function(a,b){var c={};
g.qb(c,{label:a,pageName:g.E("PAGE_NAME")});b&&g.qb(c,b);g.Cr("ypc-checkout",g.od(c))},A_=function(a){var b;
g.C(a,"yt-unlimited-more-offer-button")?b="YTO_GTM_2_BUTTON_CLICK_DATA":g.C(a,"ypc-offer-button")&&(b="YTO_GTM_1_BUTTON_CLICK_DATA");b&&(a=g.E(b,""))&&(window.dataLayer=window.dataLayer||[],window.dataLayer.push(a))},Lqa=function(a){a=a.currentTarget;
var b=g.F(a,"tab-id");if(b){for(var c=g.L("offer-module-tab-content"),d=0;d<c.length;d++)c[d].classList.remove("active-tab");c=g.L("offer-module-tab");for(d=0;d<c.length;d++)c[d].classList.remove("active-tab");g.z(b).classList.add("active-tab");a.classList.add("active-tab")}},Mqa=function(a){if(a=a.currentTarget){A_(a);
var b=g.vO(a,"U");b?(u_(function(){g.u("yt.ypc.checkout.offerpurchaser.completeTransaction")(b)}),setTimeout(g.Bh,0)):g.Pf(Error("ypc-complete-transaction-button does not contain purchaseFlowData"))}},Nqa=function(a){a=a.currentTarget;
var b=g.F(a,"feedback-token");b&&(a={itct:g.F(a,"innertube-clicktracking"),feedback_tokens:[b],wait_for_response:1},g.I("/feed_change_ajax?action_give_feedback=1",{method:"POST",onSuccess:function(c,d){if(d&&d.actions){var e=d.actions.url_endpoint.url,f=window,k=g.Bb("_self");e=e instanceof g.Jb?e:g.Pb(e);(f||g.p).open(g.Kb(e),k?g.Ab(k):"",void 0,void 0)}},
ia:a}))},Pqa=function(){var a=g.Gq(window.location.href);
if(E_){g.gb(Oqa,function(c){g.kb(a,c)});
var b=g.pd(window.location.href.split("?",2)[0],a);Bqa();Cqa(b)}},F_=g.Bf&&8<=document.documentMode||g.Sl&&g.rc("1.9.2")||g.Tl&&g.rc("532.1"),l_=g.Bf&&!F_;
m_.prototype.rb=function(a,b){this.D&&(g.jh(this.D),delete this.D);this.G&&(g.Xf(this.G),delete this.G);if(a){this.C=n_(this);if(l_){var c=this.L.contentWindow.document.body;c&&c.innerHTML||p_(this,this.C)}b||this.F(this.C);F_?this.D=g.J(this.J,"hashchange",this.N):this.G=g.Vf(this.N,200)}};
m_.prototype.M=function(){if(l_){var a=(a=this.L.contentWindow.document.body)?g.gc(g.$o(a).substring(1)):"";a!=this.C?(this.C=a,o_(this,a),this.F(a)):(a=n_(this),a!=this.C&&(this.C=a,p_(this,a),this.F(a)))}else a=n_(this),a!=this.C&&(this.C=a,this.F(a))};
m_.prototype.add=function(a,b,c){this.C=""+a;l_&&p_(this,a);o_(this,a);c||this.F(this.C)};q_.prototype.rb=function(a,b){this.H&&(g.jh(this.H),delete this.H);this.L&&(g.Xf(this.L),delete this.L);a&&E_&&(this.C=this.F.href,b||this.D(this.C),this.H=g.J(this.G,"popstate",this.N))};
q_.prototype.J=function(a){var b=this.F.href;if((a=a.state)||b!=this.C)this.C=b,this.D(b,a)};
q_.prototype.add=function(a,b,c){if(a||b)a=a||this.F.href,this.G.history.pushState(b,"",a),this.C=a,c||this.D(a,b)};
q_.prototype.replace=function(a,b,c){if(a||b)a=a||this.F.href,this.G.history.replaceState(b,"",a),this.C=a,c||this.D(a,b)};
var E_=!!window.history.pushState&&(!g.Tl||g.Tl&&g.rc("534.11"));var t_=[],s_=!1;var G_=[],H_=[];var Oqa={uK:"ypc_cc",UK:"ypc_ft",qL:"ypc_irp",tL:"ypc_ii",uL:"ypc_it"};g.Zi(g.sr({name:"www/ypc_bootstrap",deps:["www/common"],page:"feed index results watch channel playlist subscription_manager unlimited live_chat live_dashboard".split(" "),init:function(){s_=!0;g.M("ypc-delayedloader-target")&&u_();var a=g.Gq(window.location.href),b=a.ypc_it,c=a.ypc_ii,d=a.ypc_ft||"D",e=a.ypc_oi,f=a.ypc_irp,k=a.ypc_cc,l=a.ypc_ta;"channel"==g.E("PAGE_NAME")&&"ypc_cc"in a&&(b="U",c=g.E("CHANNEL_ID",void 0));if(f||c&&b)Pqa(),"start_payment"==l?(a=g.uO(e,b,c,d,k,null,"","",f,l),y_(a,
j_(a),!0)):c&&b?w_(b,c,d,f,k):x_(d,f);G_.push(g.S(document.body,"click",Gqa,"ypc-checkout-button"),g.S(document.body,"click",Fqa,"ypc-offer-button"),g.S(document.body,"click",Mqa,"ypc-complete-transaction-button"),g.S(document.body,"click",Eqa,"ytr-pre-purchase-button"),g.S(document.documentElement,"click",D_,"ypc-unsubscribe-link"),g.S(document.documentElement,"click",D_,"ypc-unsubscribe-button"),g.S(document.documentElement,"click",Lqa,"offer-module-tab"),g.S(document.documentElement,"click",Nqa,
"yt-unlimited-more-offer-button"));H_.push(g.Ki(g.$E,Hqa),g.Ki(g.SP,Iqa),g.Ki(g.aF,Jqa),g.Ki(g.dF,Kqa))},
dispose:function(){t_.length=0;g.jh(G_);G_.length=0;g.Oi(H_);H_.length=0}}));
g.r("yt.ypc.bootstrap.api.loadOffers",w_,void 0);g.r("yt.ypc.bootstrap.api.loadOffersForInnertubeRequestParams",x_,void 0);})(_yt_www);
