(function(g){var window=this;var PU=function(a,b){var c=g.z(b);if(c){var d=g.Y(a,"toggled");(0,g.B)(g.L(d,c),function(e){g.R(e,d);e.removeAttribute("aria-pressed")})}},QU=function(a,b,c){a.addEventListener&&a.addEventListener(b,c,!1)},RU=function(a){try{return!!a&&null!=a.location.href&&g.Ec(a,"foo")}catch(b){return!1}},Una=function(){var a=SU(g.Dd),b=TU();
this.D=a;this.pubWin=b;this.C=(this.iframeWin=g.Dd)||{};this.H=-1;this.Y=!1;this.N="";this.L=this.F=0;this.G=this.M=this.J=""},UU=function(){var a=void 0===a?!1:a;
return g.yd.getInstance().C(a)},VU=function(){var a=void 0===a?0:a;
return g.yd.getInstance().F(a)},WU=function(a){a=void 0===a?g.q:a;
var b=a.context||a.AMP_CONTEXT_DATA;if(!b)try{b=a.parent.context||a.parent.AMP_CONTEXT_DATA}catch(c){}try{if(b&&b.pageViewId&&b.canonicalUrl)return b}catch(c){}return null},XU=function(a,b){g.q.google_image_requests||(g.q.google_image_requests=[]);
var c=g.q.document.createElement("img");if(b){var d=function(e){b&&b(e);c.removeEventListener&&c.removeEventListener("load",d,!1);c.removeEventListener&&c.removeEventListener("error",d,!1)};
QU(c,"load",d);QU(c,"error",d)}c.src=a;g.q.google_image_requests.push(c)},Vna=function(a){return g.Cd(a,"object")},YU=function(a){return g.Cd(a,"function")},ZU=function(a,b){if(a)for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.call(void 0,a[c],c,a)},$U=function(a){return!(!a||!a.call)&&YU(a)},aV=function(a,b){if(a.filter)return a.filter(b,void 0);
for(var c=[],d=0;d<a.length;d++)b.call(void 0,a[d],d,a)&&c.push(a[d]);return c},Wna=function(a,b){var c=b.slice(-1),d="?"===c||"#"===c?"":"&",e=[b];
ZU(a,function(f,k){if(f||0===f||!1===f)g.Cd(f,"boolean")&&(f=f?1:0),e.push(d),e.push(k),e.push("="),e.push(encodeURIComponent(String(f))),d="&"});
return e.join("")},TU=function(){if(g.qm&&!RU(g.rm)){var a="."+g.lm.domain;
try{for(;2<a.split(".").length&&!RU(g.rm);)g.lm.domain=a=a.substr(a.indexOf(".")+1),g.rm=window.parent}catch(b){}RU(g.rm)||(g.rm=window)}return g.rm},Xna=function(){var a,b=window.ActiveXObject;
if(navigator.plugins&&navigator.mimeTypes.length){if((a=navigator.plugins["Shockwave Flash"])&&a.description)return a.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else{if(navigator.userAgent&&0<=navigator.userAgent.indexOf("Windows CE")){var c=3;for(a=1;a;)try{a=new b("ShockwaveFlash.ShockwaveFlash."+(c+1)),c++}catch(d){a=null}return c.toString()}if(g.Sb()){a=null;try{a=new b("ShockwaveFlash.ShockwaveFlash.7")}catch(d){c=0;try{a=new b("ShockwaveFlash.ShockwaveFlash.6"),c=6,a.AllowScriptAccess=
"always"}catch(e){if(6===c)return c.toString()}try{a=new b("ShockwaveFlash.ShockwaveFlash")}catch(e){}}if(a)return c=a.GetVariable("$version").split(" ")[1],c.replace(/,/g,".")}}return"0"},SU=function(a){a=a.top;
return RU(a)?a:null},bV=function(a,b){for(var c=0,d=a,e=0;a&&a!=a.parent;)if(a=a.parent,e++,RU(a))d=a,c=e;
else if(b)break;return{xg:d,level:c}},dV=function(){cV||(cV=bV(g.q,!0).xg);
return cV},Yna=function(a,b){ZU(a,function(c,d){b[d]=c})},eV=function(a){var b=a.location.href;
if(a==a.top)return{url:b,Yk:!0};var c=!1,d=a.document;d&&d.referrer&&(b=d.referrer,a.parent==a.top&&(c=!0));(a=a.location.ancestorOrigins)&&(a=a[a.length-1])&&-1==b.indexOf(a)&&(c=!1,b=a);return{url:b,Yk:c}},Zna=function(){var a=TU();
if(a==a.top)return 0;for(;a&&a!=a.top&&RU(a);a=a.parent){if(a.sf_)return 2;if(a.$sf)return 3;if(a.inGptIF)return 4;if(a.inDapIF)return 5}return 1},aoa=function(a){return(0,g.Ll)($na,function(b){return b.test(a)})},fV=function(a){if(a=/[-\w]+\.[-\w]+$/.exec(a))switch(g.lc(a[0].toLowerCase())){case 1967261364:return 0;
case 3147493546:return 1;case 1567346461:return 2;case 2183041838:return 3;case 763236279:return 4;case 1342279801:return 5;case 526831769:return 6;case 352806002:return 7;case 2755048925:return 8;case 3306848407:return 9;case 2207000920:return 10;case 484037040:return 11;case 3506871055:return 12;case 672143848:return 13;case 2528751226:return 14;case 2744854768:return 15;case 3703278665:return 16;case 2014749173:return 17;case 133063824:return 18;case 2749334602:return 19;case 3131239845:return 20;
case 2074086763:return 21;case 795772493:return 22;case 290857819:return 23;case 3035947606:return 24;case 2983138003:return 25;case 2197138676:return 26;case 4216016165:return 27;case 239803524:return 28;case 975993579:return 29;case 1794940339:return 30;case 1314429186:return 31;case 1643618937:return 32;case 497159982:return 33;case 3882239661:return 34}return-1},gV=function(a){if(!a.length)return 0;
for(var b=[],c=0;34>=c;c++)b[c]=0;for(c=a.length-1;0<=c;c--){var d=fV(a[c]);0<=d&&(b[34-d]=1)}return parseInt(b.join(""),2)},hV=function(a,b,c){this.url=a;
this.xg=b;this.kp=!!c;this.depth=null},iV=function(a){var b=a||g.q,c=[],d=null;
do{var e=b;if(RU(e)){var f=e.location.href;d=e.document&&e.document.referrer||null}else f=d,d=null;c.push(new hV(f||"",e));try{b=e.parent}catch(k){b=null}}while(b&&e!=b);e=0;for(b=c.length-1;e<=b;++e)c[e].depth=b-e;e=a||g.q;if(e.location&&e.location.ancestorOrigins&&e.location.ancestorOrigins.length==c.length-1)for(a=1;a<c.length;++a)b=c[a],b.url||(b.url=e.location.ancestorOrigins[a-1]||"",b.kp=!0);return c},jV=function(a){a=(this.F=a||g.q)||g.q;
this.D=a.top==a?1:RU(a.top)?2:3;3!=this.D&&(this.lastModifiedTime=Date.parse(g.q.top.document.lastModified)/1E3);this.C=iV(this.F)},lV=function(a){for(var b=[],c=Math.min(a.C.length,27),d=1;d<c;d++)a.C[d]&&a.C[d].url&&(b[d-1]=a.C[d].url);
return kV(a,b.reverse())},mV=function(a){var b=a.F.document&&a.F.document.scripts?a.F.document.scripts:[];
if(!b)return 0;for(var c=[],d=b.length-1;0<=d&&26>c.length;)b[d].src&&c.unshift(b[d].src),d--;return kV(a,c)},kV=function(a,b){for(var c,d=0,e=(c=a.C[Math.max(a.C.length-1,0)].url||null)&&g.qc(c),f=Math.min(b.length,26),k=0;k<f;k++)c=null!=b[k]&&g.qc(b[k])||"",d*=4,c&&(e&&c==e?d+=3:aoa(b[k])?d+=2:c&&0<=fV(c)&&(d+=1));
return d},nV=function(a){a=a.C;
for(var b=[],c=a.length-1;0<c;c--){var d=a[c];d&&null!=d.url&&b.push(g.qc(d.url))}return gV(b)},oV=function(a){a=a.F.document&&a.F.document.scripts?a.F.document.scripts:[];
if(!a)return 0;for(var b=[],c=a.length-1;0<=c;c--){var d=a[c];d&&null!=d.src&&b.push(g.qc(d.src))}return gV(b)},boa=function(a,b){this.C=a;
this.F=b},doa=function(){if("1"!=g.vn(g.E("PLAYER_CONFIG",{}),"args","privembed")){var a=function(){pV=!0;
"google_ad_status"in window?g.Nf("DCLKSTAT",1):g.Nf("DCLKSTAT",2)};
g.mg("//static.doubleclick.net/instream/ad_status.js",a);coa.push(g.ah(function(){if(!(pV||"google_ad_status"in window)){var b=g.lg("//static.doubleclick.net/instream/ad_status.js");spf.script.ignore(b,a);pV=!0;g.Nf("DCLKSTAT",3)}},5E3))}},eoa=function(a){g.Sf("botguard_periodic_refresh")?qV=(0,g.tg)():g.Sf("botguard_always_refresh")&&(rV=a)},foa=function(a){if(a){if(g.gi.F)return!1;
if(g.Sf("botguard_periodic_refresh"))return 72E5<(0,g.tg)()-qV;if(g.Sf("botguard_always_refresh"))return rV!=a}else return!1;return!sV},goa=function(a){var b=g.E("BG_P",void 0);
return foa(b)&&(g.E("BG_I")||g.E("BG_IU"))?(sV=!0,g.gi.initialize(g.E("BG_I",null),g.E("BG_IU",null),b,eoa,a,!!g.E("BG_CE",!1)),!0):!1},hoa=function(){var a=new jV(g.Dd),b=a.C[0].depth,c={};
c=(c.dssz=g.lm.scripts?g.lm.scripts.length:0,c.icsg=mV(a),c.mdo=nV(a),c.mso=oV(a),c);g.Dd.location&&g.Dd.location.ancestorOrigins&&(c.iag=lV(a));0<b&&(c.nhd=b);return c},ioa=function(a){var b;
g.Sq(["fullscreenEnabled","webkitFullscreenEnabled","mozFullScreenEnabled","msFullscreenEnabled"],document)?g.Lv()==a&&(b=document):b=a;b&&(a=g.Sq(["exitFullscreen","webkitExitFullscreen","mozCancelFullScreen","msExitFullscreen"],b))&&a.call(b)},joa=function(a){return(0,g.Kl)(a,function(b){return{key:b.id,
name:b.name}})},tV=function(){var a=g.wx("yt-remote-cast-receiver");
return a?a.friendlyName:null},koa=function(){var a=g.gz().Dc.$_gos();
var b=g.oz();b&&g.rz()&&(g.nx(a,b)||a.push(b));return joa(a)},loa=function(){var a=koa(),b=g.oz();
b||(b=g.lz());return g.Ka(a,function(c){return b&&g.hx(b,c.key)?!0:!1})},uV=function(){var a=loa();
!a&&g.xy()&&tV()&&(a={key:"cast-selector-receiver",name:tV()});return a},vV=function(){var a=g.z("watch-queue-mole");
return!!a&&g.sv(a)},wV=function(){var a=g.z("watch-queue-mole");
return a&&g.Wo(a)?0:1},moa=function(a){if(!a||g.pb(a.responseText))g.iL();
else try{eval(a.responseText)}catch(b){throw g.iL(),b;}},noa=function(){var a={};
return a.dff="times new roman",a.dfs="16",a.ppjl="u",a.rsz="||n|",a},xV=function(a){var b=g.wh(g.vh);
g.Xm(b,g.xh(g.vh));g.Sf("desktop_pyv_on_watch_missing_params")&&(g.Xm(b,noa()),g.Xm(b,hoa()));a=g.xc(a,b);g.Sf("desktop_pyv_on_watch_override_lact")&&(a=g.ao(a,"lact",g.jh()));g.bL=g.J(a,{format:"RAW",onSuccess:moa,onError:function(){g.iL()},
withCredentials:!0});g.wk("parq")},ooa=function(a){var b=a.C;
null==b.google_ad_output&&(b.google_ad_output="html");if(null!=b.google_ad_client){var c;(c=String(b.google_ad_client))?(c=c.toLowerCase())&&"ca-"!=c.substring(0,3)&&(c="ca-"+c):c="";b.google_ad_client=c}null!=b.google_ad_slot&&(b.google_ad_slot=String(b.google_ad_slot));if(null==b.google_flash_version){try{var d=Xna()}catch(e){d="0"}b.google_flash_version=d}b.google_webgl_support=!!g.Dd.WebGLRenderingContext;b.google_ad_section=b.google_ad_section||b.google_ad_region||"";b.google_country=b.google_country||
b.google_gl||"";d=(new Date).getTime();g.Aa(b.google_color_bg)&&(b.google_color_bg=yV(a,b.google_color_bg,d));g.Aa(b.google_color_text)&&(b.google_color_text=yV(a,b.google_color_text,d));g.Aa(b.google_color_link)&&(b.google_color_link=yV(a,b.google_color_link,d));g.Aa(b.google_color_url)&&(b.google_color_url=yV(a,b.google_color_url,d));g.Aa(b.google_color_border)&&(b.google_color_border=yV(a,b.google_color_border,d));g.Aa(b.google_color_line)&&(b.google_color_line=yV(a,b.google_color_line,d))},CV=
function(){var a=window;
ZU(zV,function(b,c){a[c]=null});
ZU(AV,function(b,c){a[c]=null});
ZU(BV,function(b,c){a[c]=null});
a.google_container_id=null;a.google_eids=null;a.google_page_location=null;a.google_referrer_url=null;a.google_enable_single_iframe=null;a.google_ad_region=null;a.google_gl=null;a.google_loader_used=null;a.google_loader_features_used=null;a.google_debug_params=null},yV=function(a,b,c){a.F|=2;
return b[c%b.length]},DV=function(a,b){var c=void 0===c?{}:c;
this.error=a;this.context=b.context;this.msg=b.message||"";this.id=b.id||"jserror";this.meta=c},EV=function(){this.D="&";
this.G=!1;this.F={};this.H=0;this.C=[]},FV=function(a,b){var c={};
c[a]=b;return[c]},HV=function(a,b,c,d,e){var f=[];
g.wd(a,function(k,l){var m=GV(k,b,c,d,e);m&&f.push(l+"="+m)});
return f.join(b)},GV=function(a,b,c,d,e){if(null==a)return"";
b=b||"&";c=c||",$";"string"==typeof c&&(c=c.split(""));if(a instanceof Array){if(d=d||0,d<c.length){for(var f=[],k=0;k<a.length;k++)f.push(GV(a[k],b,c,d+1,e));return f.join(c[d])}}else if("object"==typeof a)return e=e||0,2>e?encodeURIComponent(HV(a,b,c,d,e+1)):"...";return encodeURIComponent(String(a))},IV=function(a,b,c,d){a.C.push(b);
a.F[b]=FV(c,d)},poa=function(a){var b=1,c;
for(c in a.F)b=c.length>b?c.length:b;return 3997-b-a.D.length-1},qoa=function(){var a=void 0===a?g.Dd:a;
this.F="http:"===a.location.protocol?"http:":"https:";this.C=Math.random()},roa=function(){var a=JV,b=KV.google_srt;
0<=b&&1>=b&&(a.C=b)},LV=function(a,b,c,d,e,f){if((d?a.C:Math.random())<(e||.01))try{if(c instanceof EV)var k=c;
else k=new EV,g.wd(c,function(m,p){var t=k,y=t.H++,A=FV(p,m);t.C.push(y);t.F[y]=A});
var l=k.getUrl(a.F,"pagead2.googlesyndication.com","/pagead/gen_204?id="+b+"&","");l&&("undefined"===typeof f?XU(l,null):XU(l,void 0===f?null:f))}catch(m){}},MV=function(a){this.F={};
this.C={};a=a||[];for(var b=0,c=a.length;b<c;++b)this.C[a[b]]=""},toa=function(){var a=soa(),b=new MV;
g.wd(a.F,function(c,d){b.F[d]=c});
g.wd(a.C,function(c,d){b.C[d]=c});
return b},OV=function(a){var b=NV();
return b.C.hasOwnProperty(a)?b.C[a]:""},PV=function(a){var b=[];
g.wd(a.F,function(c,d){b.push(d)});
g.wd(a.C,function(c){""!=c&&b.push(c)});
return b},QV=function(){var a=g.q.performance;
return a&&a.now&&a.timing?Math.floor(a.now()+a.timing.navigationStart):(0,g.$c)()},RV=function(){var a=void 0===a?g.q:a;
return(a=a.performance)&&a.now?a.now():null},uoa=function(a,b,c){this.label=a;
this.type=b;this.value=c;this.duration=0;this.uniqueId=Math.random();this.slotId=void 0},TV=function(){var a=KV;
this.events=[];this.F=a||g.q;var b=null;a&&(a.google_js_reporting_queue=a.google_js_reporting_queue||[],this.events=a.google_js_reporting_queue,b=a.google_measure_js_timing);this.C=SV()||(null!=b?b:1>Math.random())},VV=function(a){a&&UV&&SV()&&(UV.clearMarks("goog_"+a.label+"_"+a.uniqueId+"_start"),UV.clearMarks("goog_"+a.label+"_"+a.uniqueId+"_end"))},XV=function(){var a=WV;
this.H=JV;this.F=null;this.L=this.G;this.C=void 0===a?null:a;this.D=!1},voa=function(a,b,c){try{if(a.C&&a.C.C){var d=a.C.start(b.toString(),3);
var e=c();a.C.end(d)}else e=c()}catch(k){c=!0;try{VV(d);var f=new DV(k,{message:YV(k)});c=a.L(b,f,void 0,void 0)}catch(l){a.G(217,l)}if(!c)throw k;}return e},woa=function(a,b){var c=ZV;
return function(d){for(var e=[],f=0;f<arguments.length;++f)e[f-0]=arguments[f];return voa(c,a,function(){return b.apply(void 0,e)})}},YV=function(a){var b=a.toString();
a.name&&-1==b.indexOf(a.name)&&(b+=": "+a.name);a.message&&-1==b.indexOf(a.message)&&(b+=": "+a.message);if(a.stack){a=a.stack;var c=b;try{-1==a.indexOf(c)&&(a=c+"\n"+a);for(var d;a!=d;)d=a,a=a.replace(/((https?:\/..*\/)[^\/:]*:\d+(?:.|\n)*)\2/,"$1");b=a.replace(/\n */g,"\n")}catch(e){b=c}}return b},$V=function(a,b){return woa(a,b)},xoa=function(){this.wasPlaTagProcessed=!1;
this.wasReactiveAdConfigReceived={};this.adCount={};this.wasReactiveAdVisible={};this.stateForType={};this.reactiveTypeEnabledInAsfe={};this.wasReactiveTagRequestSent=!1;this.reactiveTypeDisabledByPublisher={};this.tagSpecificState={};this.improveCollisionDetection=1;this.messageValidationEnabled=!1;this.floatingAdsStacking=new aW},bW=function(a){a.google_reactive_ads_global_state?null==a.google_reactive_ads_global_state.floatingAdsStacking&&(a.google_reactive_ads_global_state.floatingAdsStacking=
new aW):a.google_reactive_ads_global_state=new xoa;
return a.google_reactive_ads_global_state},aW=function(){this.maxZIndexRestrictions={};
this.nextRestrictionId=0;this.maxZIndexListeners=[]},cW=function(a){return a!=a.top?512:0},eW=function(a,b){var c=dW(a).clientWidth;
return c?c>(void 0===b?420:b)?32768:320>c?65536:0:16384},fW=function(a){var b=dW(a).clientWidth;
a=a.innerWidth;return(b=b&&a?b/a:0)?1.05<b?262144:.95>b?524288:0:131072},dW=function(a){a=a.document;
var b={};a&&(b="CSS1Compat"==a.compatMode?a.documentElement:a.body);return b||{}},yoa=function(a,b){if(!a.adCount)return!1;
if(1==b||2==b)return!(!a.adCount[1]&&!a.adCount[2]);var c=a.adCount[b];return c&&27!=b&&26!=b?1<=c:!1},gW=function(a){MV.call(this,a);
this.dfltBktExt=this.F;this.lrsExt=this.C},zoa=function(){this.S={}},jW=function(){if(hW)return hW;
var a=iW(),b=a.google_persistent_state_async;return null!=b&&"object"==typeof b&&null!=b.S&&"object"==typeof b.S?hW=b:a.google_persistent_state_async=hW=new zoa},lW=function(a,b,c){b=kW[b]||"google_ps_"+b;
a=a.S;var d=a[b];return void 0===d?a[b]=c:d},iW=function(){var a=WU();
return(a?RU(a.master)?a.master:null:null)||TU()},Aoa=function(){try{return mW.javaEnabled()}catch(a){return!1}},nW=function(a){var b=1,c;
if(void 0!=a&&""!=a)for(b=0,c=a.length-1;0<=c;c--){var d=a.charCodeAt(c);b=(b<<6&268435455)+d+(d<<14);d=b&266338304;b=0!=d?b^d>>21:b}return b},oW=function(a,b){if(!a||"none"==a)return 1;
a=String(a);"auto"==a&&(a=b,"www."==a.substring(0,4)&&(a=a.substring(4,a.length)));return nW(a.toLowerCase())},pW=function(a,b){if(!a)return!1;
var c=a.hash;if(!c||!c.indexOf)return!1;if(-1!=c.indexOf(b))return!0;var d=Boa(b);return"go"!=d&&-1!=c.indexOf(d)?!0:!1},Boa=function(a){var b="";
ZU(a.split("_"),function(c){b+=c.substr(0,2)});
return b},qW=function(a,b){var c;
if("relative"===a)return b;c||(c="https");g.q.location&&"https:"==g.q.location.protocol&&"http"==c&&(c="https");return[c,"://",a,b].join("")},sW=function(a){a=a.google_reactive_ad_format;
return g.sn(rW,a)?""+a:null},tW=function(a){return!!sW(a)||null!=a.google_pgb_reactive},Doa=function(){this.C=Coa},Eoa=function(a){try{if(!a.localStorage)return!1;
a.localStorage.setItem("__storage_test__","__storage_test__");var b=a.localStorage.getItem("__storage_test__");a.localStorage.removeItem("__storage_test__");return"__storage_test__"==b}catch(c){return!1}},uW=function(a){try{if(!Eoa(a)||!a.localStorage)return null;
var b=a.localStorage.getItem("__lsv__");if(!b)return[];try{var c=JSON.parse(b)}catch(d){}return!g.Aa(c)||(0,g.Ll)(c,function(d){return!Number.isInteger(d)})?(a.localStorage.removeItem("__lsv__"),[]):Foa(c)}catch(d){return null}},Foa=function(a){a=void 0===a?[]:a;
var b=Date.now();return(0,g.Gk)(a,function(c){return 36E5>b-c})},vW=function(a){return!!a&&1>a.length},Goa=function(a,b,c){switch(c){case 0:return 0;
case 1:case 2:var d=0;try{d|=cW(a);var e=Math.min(a.screen.width||0,a.screen.height||0);d|=e?320>e?8192:0:2048;var f;if(f=a.navigator){var k=a.navigator.userAgent;f=/Firefox/.test(k)||/Android 2/.test(k)||/iPhone OS [34]_/.test(k)||/Windows Phone (?:OS )?[67]/.test(k)}d|=f?1048576:0}catch(y){d|=32}var l=0;try{l|=a.innerHeight>=a.innerWidth?0:8,l|=eW(a,wW),l|=fW(a)}catch(y){l|=32}if(c=2==c){e=a.innerWidth;c=bW(a).improveCollisionDetection;f=Math.round(a.innerWidth/320*50+15);var m=[];for(k=0;3>k;k++)for(var p=
0;3>p;p++)m.push({x:p/2*(e-0),y:k/2*(f-0)});a:{for(e=0;e<m.length;e++){b:{f=a;b=m[e];k=c;p=f.document;p.elementFromPoint(b.x,b.y);var t=b.x;b=b.y;p.hasOwnProperty("_goog_efp_called_")||(p._goog_efp_called_=p.elementFromPoint(t,b));if(p=p.elementFromPoint(t,b))if("fixed"==g.Gp(p))f=p;else{if(1==k){c:{f=f.document;for(k=p.offsetParent;k&&k!=f.body;k=k.offsetParent)if("fixed"==g.Gp(k)){f=k;break c}f=null}if(f)break b}f=null}else f=null}if(f){a=f;break a}}a=null}c=null!=a}c&&!UU()&&(l|=16777216);return d|
l;case 8:l=!("on"===b.google_adtest||pW(a.location,"google_ia_debug"));c=0;try{c|=cW(a),c|=a.navigator&&/Android 2/.test(a.navigator.userAgent)?1048576:0}catch(y){c|=32}m=UU();e=0;try{e|=eW(a,0<VU()?VU():wW),UU()&&(d=dW(a).clientHeight,e|=d?320>d?-2147483648:0:1073741824),e|=fW(a),m||(e|=a.innerHeight>=a.innerWidth?0:8),l&&!vW(uW(a))&&(e|=134217728)}catch(y){e|=32}return c|e;case 9:d=UU()&&!("on"===b.google_adtest||pW(a.location,"google_scr_debug"));l=0;try{l|=cW(a),l|=fW(a),l|=eW(a),l|=a.innerHeight>=
a.innerWidth?0:8,l|=a.navigator&&/Android 2/.test(a.navigator.userAgent)?1048576:0,d&&!vW(uW(a))&&(l|=134217728)}catch(y){l|=32}return l;case 16:return b.google_ad_resizable&&!b.google_reactive_ad_format&&a.navigator&&/iPhone|iPod|iPad|Android|BlackBerry/.test(a.navigator.userAgent)&&a.top==a?0:8388608;case 30:d=0;try{d|=cW(a);d|=a.getComputedStyle?0:2097152;!(g.Rb("iPad")||g.Rb("Android")&&!g.Rb("Mobile")||g.Rb("Silk"))&&(g.Rb("iPod")||g.Rb("iPhone")||g.Rb("Android")||g.Rb("IEMobile"))||(d|=1048576);
p=Math.floor(a.document.body.getBoundingClientRect().width);xW||(xW=new Doa);t=parseFloat(xW.C[79]);p<=(isNaN(t)?0:t)||(d|=32768);a:{m=a.document.getElementsByClassName("adsbygoogle");for(a=0;a<m.length;a++)if("autorelaxed"==g.Ft(m[a],"adFormat")){l=!0;break a}l=!1}l&&(d|=33554432)}catch(y){d|=32}return d;case 26:d=0;try{d|=cW(a),d|=a.getComputedStyle?0:2097152,d|=a.document.querySelectorAll&&a.document.querySelector?0:4194304,d|=eW(a,1E4)}catch(y){d|=32}return d;case 27:d=0;try{d|=cW(a),d|=a.getComputedStyle?
0:2097152,d|=eW(a,1E4)}catch(y){d|=32}return d;default:return 32}},Joa=function(a){if(!a.hash)return null;
var b=null;ZU(Hoa,function(c){!b&&pW(a,c)&&(b=Ioa[c])});
return b},Moa=function(a,b){if(!b)return null;
var c=bW(b),d=0;ZU(rW,function(e){var f=Koa[e];f&&0===Loa(a,b,e)&&(d|=f)});
c.wasPlaTagProcessed&&(d|=256);a.google_reactive_tag_first&&(d|=1024);return d?""+d:null},Loa=function(a,b,c){if(!b)return 256;
var d=0,e=bW(b),f=yoa(e,c);if(a.google_reactive_ad_format==c||26!=c&&27!=c&&f)d|=64;var k=!1;ZU(e.reactiveTypeDisabledByPublisher,function(l,m){String(c)===m&&(k=!0)});
k&&Joa(b.location)!==c&&(d|=128);return d|Goa(b,a,c)},yW=function(a){try{return!!a&&g.Dc(!0)}catch(b){return!1}},Noa=function(){if(yW(zW))return!0;
var a=jW();if(a=lW(a,3,null)){if(a&&a.dfltBktExt&&a.lrsExt){var b=new gW;b.F=a.dfltBktExt;b.dfltBktExt=b.F;b.C=a.lrsExt;b.lrsExt=b.C;a=b}else a=null;a||(a=new gW,b={context:"ps::gpes::cf",url:TU().location.href},LV(JV,"jserror",b,!0,void 0,void 0))}return yW(a)?(zW=a,!0):!1},soa=function(){if(Noa())return zW;
var a=jW(),b=new gW(g.xd(Ooa));return zW=a.S[kW[3]||"google_ps_3"]=b},NV=function(){AW||(AW=toa());
return AW},Poa=function(a){a=void 0===a?NV():a;
return aV(PV(a),function(b){return!!BW[b]})},Qoa=function(a){a=void 0===a?NV():a;
return aV(PV(a),function(b){return!BW[b]})},CW=function(a){this.G=[];
this.F=a||window;this.C=0;this.D=null;this.H=0},DW=function(a){var b=$V(189,(0,g.v)(a.bH,a));
a.F.setTimeout(b,0)},EW=function(a){try{return a.sz()}catch(b){return!1}},FW=function(a,b){this.mc=a;
this.xg=b},GW=function(a,b,c){a-=b;
return a>=(void 0===c?1E5:c)?"M":0<=a?a:"-M"},HW=function(a){switch(a){case "":case "Test":case "Real":return!0;
default:return!1}},IW=function(a){var b=UU();
this.D=a;this.F=void 0===b?!1:b;this.C=new g.Vc(a.document)},MW=function(){JW=g.q;
KW=JW.googleToken=JW.googleToken||{};var a=(0,g.$c)();KW[1]&&KW[3]>a&&0<KW[2]||(KW[1]="",KW[2]=-1,KW[3]=-1,KW[4]="",KW[6]="");LW=JW.googleIMState=JW.googleIMState||{};a=LW[1];Roa.test(a)&&!Soa.test(a)||(LW[1]=".google.com");g.Aa(LW[5])||(LW[5]=[]);"boolean"!==typeof LW[6]&&(LW[6]=!1);g.Aa(LW[7])||(LW[7]=[]);"number"!==typeof LW[8]&&(LW[8]=0)},$oa=function(a){for(var b=a.getElementsByTagName("script"),c=b.length,d=0;d<c;++d){var e=b[d];
if(e.hasAttribute("src")){e=e.getAttribute("src");if(Toa.test(e))return 5;if(NW.test(e))return 6}}b=a.getElementsByTagName("link");c=b.length;for(d=0;d<c;++d)if(e=b[d],e.hasAttribute("href")&&(e=e.getAttribute("href"),Uoa.test(e)||NW.test(e)))return 6;a=a.getElementsByTagName("meta");d=a.length;for(e=0;e<d;++e){var f=a[e];if("generator"==f.getAttribute("name")&&f.hasAttribute("content")){f=f.getAttribute("content");if(Voa.test(f))return 1;if(Woa.test(f))return 2;if(Xoa.test(f))return 3;if(Yoa.test(f))return 4}}for(a=
0;a<c;++a)if(d=b[a],"stylesheet"==d.getAttribute("rel")&&d.hasAttribute("href")&&(d=d.getAttribute("href"),Zoa.test(d)))return 2;return 0},ipa=function(a){var b=a.C,c=TU().document,d={},e=TU();
var f=bV(TU(),!1).xg;var k=eV(f);a:{var l=TU(),m=b.google_ad_width||l.google_ad_width,p=b.google_ad_height||l.google_ad_height;if(l&&l.top==l)var t=!1;else{var y=c.documentElement;if(m&&p){var A=1,G=1;l.innerHeight?(A=l.innerWidth,G=l.innerHeight):y&&y.clientHeight?(A=y.clientWidth,G=y.clientHeight):c.body&&(A=c.body.clientWidth,G=c.body.clientHeight);if(G>2*p||A>2*m){t=!1;break a}}t=!0}}var O=t;var T=k.Yk,ra=TU(),Ba=ra.top==ra?0:RU(ra.top)?1:2,Ha=4;O||1!=Ba?O||2!=Ba?O&&1==Ba?Ha=7:O&&2==Ba&&(Ha=8):
Ha=6:Ha=5;T&&(Ha|=16);var vd=""+Ha;var nh=Zna();var oh=!!b.google_page_url;d.google_iframing=vd;0!=nh&&(d.google_iframing_environment=nh);if(!oh&&"ad.yieldmanager.com"==c.domain){for(var Xt=c.URL.substring(c.URL.lastIndexOf("http"));-1<Xt.indexOf("%");)try{Xt=decodeURIComponent(Xt)}catch(Rg){break}b.google_page_url=Xt;oh=!!Xt}oh?(d.google_page_url=b.google_page_url,d.google_page_location=(O?c.referrer:c.URL)||"EMPTY"):(O&&RU(e.top)&&c.referrer&&e.top.document.referrer===c.referrer?d.google_page_url=
e.top.document.URL:d.google_page_url=O?c.referrer:c.URL,d.google_page_location=null);a:{if(c.URL==d.google_page_url)try{var N6=Date.parse(c.lastModified)/1E3;break a}catch(Rg){}N6=null}d.google_last_modified_time=N6;if(f==f.top)var O6=f.document.referrer;else{var P6=WU();O6=P6&&P6.referrer||""}d.google_referrer_url=O6;Yna(d,b);var UA=b.google_page_location||b.google_page_url;"EMPTY"==UA&&(UA=b.google_page_url);if(UA){var Sg=UA.toString();0==Sg.indexOf("http://")?Sg=Sg.substring(7,Sg.length):0==Sg.indexOf("https://")&&
(Sg=Sg.substring(8,Sg.length));var DM=Sg.indexOf("/");-1==DM&&(DM=Sg.length);var Q6=Sg.substring(0,DM);if(apa.test(Q6))var EM=!1;else{var Hp=Q6.split("."),VA=!1;3<=Hp.length&&(VA=Hp[Hp.length-3]in OW);2<=Hp.length&&(VA=VA||Hp[Hp.length-2]in OW);EM=VA}}else EM=!1;var S6=EM?"pagead2.googlesyndication.com":"googleads.g.doubleclick.net",oa={};bpa(a,oa);MW();oa.adsid=KW[1];MW();oa.pucrd=KW[6];var gg=a.C,Yt=a.C;oa.dt=g.zh;Yt.google_async_iframe_id&&Yt.google_bpp&&(oa.bpp=Yt.google_bpp);var T6,Hta=TU();
a:{var Ita=TU();try{var Ip=Ita.performance;if(Ip&&Ip.timing&&Ip.now){var U6=Ip.timing.navigationStart+Math.round(Ip.now())-Ip.timing.domLoading;break a}}catch(Rg){}U6=null}var V6=U6;(T6=V6?GW(V6,Hta.Date.now()-g.zh,1E6):null)&&(oa.bdt=T6);var W6=Yt.google_iframe_start_time;if("number"!==typeof W6)var X6=null;else Yt.google_iframe_start_time=null,X6=GW(W6,g.zh);var Y6=X6;null!=Y6&&(oa.fdt=Y6);oa.idt=GW(0,g.zh);var WA=a.C;oa.shv="r20100101";oa.cbv="/r20100101".replace("/","");"sa"==WA.google_loader_used?
oa.ptt=5:"aa"==WA.google_loader_used&&(oa.ptt=9);/^\w{1,3}$/.test(WA.google_loader_used)&&(oa.saldr=WA.google_loader_used);var FM=WU(a.pubWin);if(FM){oa.is_amp=1;var GM=FM||WU();oa.amp_v=GM&&GM.mode?+GM.mode.version||null:null;var HM=FM||WU();if(HM&&HM.container){for(var Z6=HM.container.split(","),$6=[],IM=0;IM<Z6.length;IM++)$6.push(cpa[Z6[IM]]||"x");var a7=$6.join()}else a7=null;var b7=a7;b7&&(oa.act=b7)}TU()==window.top&&(oa.abxe=1);if("_gfp_a_"in a.pubWin){var JM=a.pubWin._gfp_a_;if("boolean"!==
typeof JM)throw Error("Illegal value of _gfp_a_: "+JM);if(JM&&UU()){var KM=(new IW(a.pubWin)).read();KM&&(oa.cookie=KM,oa.crv="Test"!==KM)}}var Hk=jW(),c7=lW(Hk,8,{}),XA=gg.google_ad_section;c7[XA]&&(oa.prev_fmts=c7[XA]);var d7=lW(Hk,9,{});d7[XA]&&(oa.prev_slotnames=d7[XA].toLowerCase());var LM=lW(Hk,8,{}),MM=lW(Hk,9,{}),Jp=gg.google_ad_section,NM=gg.google_ad_format,OM=gg.google_ad_slot;NM?LM[Jp]=LM[Jp]?LM[Jp]+(","+NM):NM:OM&&(MM[Jp]=MM[Jp]?MM[Jp]+(","+OM):OM);var e7=lW(Hk,15,0);0<e7&&(oa.nras=String(e7));
var f7=TU(),g7=WU(f7);if(g7){var PM=g7||WU();if(PM){var h7=PM.pageViewId,i7=PM.clientId;"string"===typeof i7&&(h7+=i7.replace(/\D/g,"").substr(0,6));var j7=h7}else j7=null;var k7=+j7}else{var l7=bV(f7,!1).xg,QM=l7.google_global_correlator;QM||(l7.google_global_correlator=QM=1+Math.floor(Math.random()*Math.pow(2,43)));k7=QM}oa.correlator=lW(Hk,7,k7);NV().F["21060549"]&&(oa.rume=1);if(gg.google_ad_channel){for(var m7=lW(Hk,10,{}),n7="",p7=gg.google_ad_channel.split(PW),RM=0;RM<p7.length;RM++){var SM=
p7[RM];m7[SM]?n7+=SM+"+":m7[SM]=!0}oa.pv_ch=n7}if(gg.google_ad_host_channel){for(var YA=lW(Hk,11,[]),q7=gg.google_ad_host_channel.split("|"),ZA=-1,TM=[],Oi=0;Oi<q7.length;Oi++){var r7=q7[Oi].split(PW);YA[Oi]||(YA[Oi]={});for(var Zt="",UM=0;UM<r7.length;UM++){var $A=r7[UM];""!==$A&&(YA[Oi][$A]?Zt+="+"+$A:YA[Oi][$A]=!0)}Zt=Zt.slice(1);TM[Oi]=Zt;""!==Zt&&(ZA=Oi)}var VM="";if(-1<ZA){for(var WM=0;WM<ZA;WM++)VM+=TM[WM]+"|";VM+=TM[ZA]}oa.pv_h_ch=VM}oa.frm=gg.google_iframing;oa.ife=gg.google_iframing_environment;
var s7=gg.google_ad_client;try{var t7=dV(),aB=t7.google_prev_clients;aB||(aB=t7.google_prev_clients={});if(s7 in aB)var XM=1;else aB[s7]=!0,XM=2}catch(Rg){XM=0}oa.pv=XM;var YM=a.pubWin.document,u7=a.C,v7="";try{v7=YM.cookie}catch(Rg){}var w7=YM.domain,$t=v7,bB=a.pubWin.screen,Kta=YM.referrer,Lta=g.Ed();if(WU())var x7=TU().gaGlobal||{};else{var ZM=Math.round((new Date).getTime()/1E3),$M=u7.google_analytics_domain_name,cB="undefined"==typeof $M?oW("auto",w7):oW($M,w7),Mta=-1<$t.indexOf("__utma="+cB+
"."),Nta=-1<$t.indexOf("__utmb="+cB),aN;if(!(aN=iW().gaGlobal)){var Ota={};aN=iW().gaGlobal=Ota}var Fd=aN,y7=!1;if(Mta){var bN=$t.split("__utma="+cB+".")[1].split(";")[0].split(".");Nta?Fd.sid=bN[3]+"":Fd.sid||(Fd.sid=ZM+"");Fd.vid=bN[0]+"."+bN[1];Fd.from_cookie=!0}else{Fd.sid||(Fd.sid=ZM+"");if(!Fd.vid){y7=!0;var Pta=Math.round(2147483647*Math.random()),z7=Lta,A7,vm=[mW.appName,mW.version,mW.language?mW.language:mW.browserLanguage,mW.platform,mW.userAgent,Aoa()?1:0].join("");if(bB)vm+=bB.width+"x"+
bB.height+bB.colorDepth;else if(g.q.java&&g.q.java.awt){var B7=g.q.java.awt.Toolkit.getDefaultToolkit().getScreenSize();vm+=B7.screen.width+"x"+B7.screen.height}vm=vm+$t+(Kta||"");for(A7=vm.length;0<z7;)vm+=z7--^A7++;Fd.vid=(Pta^nW(vm)&2147483647)+"."+ZM}Fd.from_cookie=!1}if(!Fd.cid){b:{var Kp=$M,C7=999;Kp&&(Kp=0==Kp.indexOf(".")?Kp.substr(1):Kp,C7=(""+Kp).split(".").length);for(var D7,E7=999,dB=$t.split(";"),au=0;au<dB.length;au++){var eB=dpa.exec(dB[au])||epa.exec(dB[au])||fpa.exec(dB[au]);if(eB){var cN=
eB[1]||0;if(cN==C7){var F7=eB[2];break b}cN<E7&&(E7=cN,D7=eB[2])}}F7=D7}var bu=F7;y7&&bu&&-1!=bu.search(/^\d+\.\d+$/)?Fd.vid=bu:bu!=Fd.vid&&(Fd.cid=bu)}Fd.dh=cB;Fd.hid||(Fd.hid=Math.round(2147483647*Math.random()));x7=Fd}var cu=x7;oa.ga_vid=cu.vid;oa.ga_sid=cu.sid;oa.ga_hid=cu.hid;oa.ga_fc=cu.from_cookie;oa.ga_cid=cu.cid;oa.ga_wpids=u7.google_analytics_uacct;var du=a.pubWin,eu=new jV(du);du.location&&du.location.ancestorOrigins&&(oa.iag=lV(eu));oa.icsg=mV(eu);var dN=eu.C[0].depth;dN&&0<dN&&(oa.nhd=
dN);oa.dssz=du.document.scripts?du.document.scripts.length:0;oa.mdo=nV(eu);oa.mso=oV(eu);var eN=gg.google_ad_layout;eN&&0<=QW[eN]&&(oa.rplot=QW[eN]);g.Gd(oa);var H7=WU(),fB=H7&&H7.initialIntersection,fN=(fB&&g.Ea(fB.rootBounds)?new g.ed(fB.rootBounds.width,fB.rootBounds.height):null)||g.Hd(a.pubWin.top);fN&&(oa.biw=fN.width,oa.bih=fN.height);var I7=a.pubWin;if(I7.top!=I7){var gN=g.Hd(a.pubWin);gN&&(oa.isw=gN.width,oa.ish=gN.height)}var wm=a.pubWin;if(null!==wm&&wm!=wm.top){var gB=[wm.document.URL];
wm.name&&gB.push(wm.name);var J7=g.Hd(wm,!1);gB.push(J7.width.toString());gB.push(J7.height.toString());var K7=gB.join(""),L7=K7.length;if(0==L7)var hN=0;else{for(var Lp=305419896,iN=0;iN<L7;iN++)Lp^=(Lp<<5)+(Lp>>2)+K7.charCodeAt(iN)&4294967295;hN=0<Lp?Lp:4294967296+Lp}}else hN=0;var M7=hN;0!==M7&&(oa.ifk=M7);var hB=SU(a.pubWin);if(hB&&hB.document){var iB=hB.document,fu=hB;fu=void 0===fu?g.q:fu;var N7=iB.scrollingElement||("CSS1Compat"==iB.compatMode?iB.documentElement:iB.body);var O7=new g.bd(fu.pageXOffset||
N7.scrollLeft,fu.pageYOffset||N7.scrollTop)}else O7=new g.bd(-12245933,-12245933);var P7=O7;oa.scr_x=Math.round(P7.x);oa.scr_y=Math.round(P7.y);var Q7=NV(),R7=Qoa(Q7),jB=a.C.google_eids;if(g.Aa(jB)){a.F|=64;for(var kB=0;kB<jB.length;kB++)"string"===typeof jB[kB]&&R7.push(jB[kB])}oa.eid=R7.join();var S7=Poa(Q7),T7=a.C.google_loeid;"string"===typeof T7&&(a.F|=4096,g.Ra(S7,T7.split(",")));oa.loeid=S7.join();a.L&&(oa.oid=a.L);if("423550201"===OV(139)){var jN=SU(a.pubWin);if(jN){var kN=dW(jN);oa.pg_h=
kN.scrollHeight==dW(jN).clientHeight?kN.offsetHeight:kN.scrollHeight}}var Tta=jW(),U7=lW(Tta,20,{})[a.C.google_ad_client];U7&&(oa.psts=U7.join());var lN=a.pubWin;if("number"!==typeof lN.goog_pvsid)try{Object.defineProperty(lN,"goog_pvsid",{value:Math.floor(Math.random()*Math.pow(2,52))})}catch(Rg){}oa.pvsid=Number(lN.goog_pvsid)||-1;a:{var V7=a.pubWin,lB=-1;try{V7.localStorage&&(lB=parseInt(V7.localStorage.getItem("google_pem_mod"),10))}catch(Rg){var W7=null;break a}W7=0<=lB&&1E3>lB?lB:null}oa.pem=
W7;var xf=a.C,mB=a.pubWin,Uta=dV();oa.ref=xf.google_referrer_url;oa.loc=xf.google_page_location;var nB=WU(a.pubWin);if(nB&&g.Ea(nB.data)&&"string"===typeof nB.data.type){var mN=nB.data.type.toLowerCase();var X7="doubleclick"==mN||"adsense"==mN?null:mN}else X7=null;var Y7=X7;Y7&&(oa.apn=Y7.substr(0,10));var gu=eV(Uta);oa.url||oa.loc||!gu.url||(oa.url=gu.url,gu.Yk||(oa.usrc=1));gu.url!=(oa.loc||oa.url)&&(oa.top=gu.url);xf.google_async_rrc&&(oa.rr=xf.google_async_rrc);oa.rx=0;var Z7;if(RW&&EW(RW))var $7=
RW;else{var nN=dV(),Pi=nN.google_jobrunner;$7=Pi&&(Vna(Pi)||YU(Pi))&&EW(Pi)&&$U(Pi.nq)&&$U(Pi.nqa)&&$U(Pi.al)&&$U(Pi.rl)?RW=Pi:nN.google_jobrunner=RW=new CW(nN)}var a8=$7;(Z7=$U(a8.tc)?a8.tc():null)&&(oa.jtc=Z7);0<=a.H&&(oa.eae=a.H);var b8=Moa(xf,a.D);b8&&(oa.fc=b8);var c8=xf.google_ad_format;if(!(c8&&0<c8.indexOf("_0ads"))){var iu=(a.iframeWin||a.pubWin).document,d8="";if(iu.documentMode){var xm=(new g.pp(iu)).createElement("IFRAME");xm.frameBorder="0";xm.style.height=0;xm.style.width=0;xm.style.position=
"absolute";if(iu.body){iu.body.appendChild(xm);try{var oB=xm.contentWindow.document;oB.open();oB.write("<!DOCTYPE html>");oB.close();d8+=oB.documentMode}catch(Rg){}iu.body.removeChild(xm)}}oa.docm=d8}oa.brdim=g.Id(mB).join();var Vta="618018086"===OV(67),pB=0;void 0===g.q.postMessage&&(pB|=1);if(Vta){var e8=WU(mB);e8&&e8.observeIntersection&&(pB|=256);var f8=mB.document;f8&&g.Da(f8.elementFromPoint)&&(pB|=1024)}var g8=pB;0<g8&&(oa.osd=g8);oa.vis=g.Pd(mB.document);if(!tW(xf)){a:{var ju=Number(xf.google_ad_width),
ku=Number(xf.google_ad_height);if(!(0<ju&&0<ku)){b:{try{var oN=String(xf.google_ad_format);if(oN&&oN.match){var pN=oN.match(/(\d+)x(\d+)/i);if(pN){var h8=parseInt(pN[1],10),i8=parseInt(pN[2],10);if(0<h8&&0<i8){var j8={width:h8,height:i8};break b}}}}catch(Rg){}j8=null}var qN=j8;if(!qN){var k8=null;break a}ju=0<ju?ju:qN.width;ku=0<ku?ku:qN.height}k8={width:ju,height:ku}}var rN=k8;if(rN){var l8=0;a:{try{var m8=xf.google_async_iframe_id,n8=TU().document;if(m8)var o8=n8.getElementById(m8);else{var p8=
n8.getElementsByTagName("script"),q8=p8[p8.length-1];o8=q8&&q8.parentNode||null}var r8=o8;if(r8){for(var lu=[],qB=r8,Wta=0,Xta=Date.now();100>=++Wta&&50>Date.now()-Xta&&(qB=gpa(qB));)1===qB.nodeType&&lu.push(qB);b:{for(var sN=0;sN<lu.length;sN++){c:{var Qi=lu[sN];try{if(Qi.parentNode&&0<Qi.offsetWidth&&0<Qi.offsetHeight&&Qi.style&&"none"!==Qi.style.display&&"hidden"!==Qi.style.visibility&&(!Qi.style.opacity||0!==Number(Qi.style.opacity))){var s8=Qi.getBoundingClientRect();var t8=0<s8.right&&0<s8.bottom;
break c}}catch(Rg){}t8=!1}if(!t8){var u8=!1;break b}}u8=!0}if(u8){b:{for(var Zta=Date.now(),$ta=/^html|body$/i,aua=/^fixed/i,tN=0;tN<lu.length&&50>Date.now()-Zta;tN++){var rB=lu[tN];if(!$ta.test(rB.tagName)&&aua.test(rB.style.position||g.Gp(rB))){var uN=rB;break b}}uN=null}break a}}}catch(Rg){}uN=null}var vN=uN;vN&&vN.offsetWidth*vN.offsetHeight<=4*rN.width*rN.height&&(l8=1);oa.pfx=l8}}if("26835106"===OV(41)&&a.D){try{var v8=a.D.document.getElementsByTagName("head")[0];var w8=v8?$oa(v8):0}catch(Rg){w8=
0}var x8=w8;0!==x8&&(oa.cms=x8)}"r20100101"!==xf.google_lrv&&(oa.alvm=xf.google_lrv||"none");oa.fu=a.F;oa.bc=g.Od();MW();oa.jar=KW[4];var y8=a.C,bua=y8.google_ad_channel,z8="/pagead/ads?";"ca-pub-6219811747049371"===y8.google_ad_client&&hpa.test(bua)&&(z8="/pagead/lopri?");var wN=qW(S6,z8);3===g.Pd(a.pubWin.document)&&(a.Y=!0,a.N=wN,wN=qW(S6,"/pagead/blank.gif#?"));var dua=Wna(oa,wN+"");return b.google_ad_url=dua},gpa=function(a){try{if(a.parentNode)return a.parentNode}catch(e){return null}if(9===
a.nodeType)a:{try{var b=g.No(a);
if(b){var c=b.frameElement;if(c&&RU(b.parent)){var d=c;break a}}}catch(e){}d=null}else d=null;return d},jpa=function(a,b){a.J&&(b.us_privacy=a.J);
a.M&&(b.gdpr_consent=a.M);a.G&&(b.addtl_consent=a.G)},bpa=function(a,b){var c=a.C;
ZU(AV,function(d,e){b[d]=c[e]});
jpa(a,b);ZU(zV,function(d,e){b[d]=c[e]});
ZU(BV,function(d,e){b[d]=c[e]});
tW(c)&&(b.fa=sW(c))},SW=function(){this.G=this.C=!1;
this.F=new g.KH(this);this.H=!1},aX=function(){if(g.E("WATCH_LEGAL_TEXT_ENABLE_AUTOSCROLL")){var a=document.getElementById("watch_companion_legal_text");
a&&(TW=new SW,TW.start(a))}var b=g.E("ADS_DATA",void 0);b&&(g.Sf("ima_prevent_mpu_queries_on_cached_playback")&&g.E("SERVED_VIA_SPF_HISTORY")&&(b.afc_vars=null,b.afv_vars=null,b.show_afv=!1,b.show_afc=!1),UW(),kpa(b),VW=b,WW=g.kL(),null!=WW&&(WW.addEventListener("onApiChange",lpa),WW.addEventListener("onReady",mpa)),b.pyv_ad_tag&&npa(b),b.use_gut&&(g.ng("//www.googletagservices.com/tag/js/gpt.js"),g.mg("//www.googletagservices.com/tag/js/gpt.js",function(){opa(b.gut_vars.tag)})),b.show_afv&&(g.ng("//pagead2.googlesyndication.com/pagead/show_companion_ad.js"),
XW(),g.mg("//pagead2.googlesyndication.com/pagead/show_companion_ad.js",ppa),g.Sf("remove_yt_uds")||g.mg("//www.google.com/jsapi?autoload=%7B%22modules%22%3A%5B%7B%22name%22%3A%22ads%22%2C%22version%22%3A%221%22%2C%22callback%22%3A%22(function()%7B%7D)%22%2C%22packages%22%3A%5B%22content%22%5D%7D%5D%7D")),YW(),ZW&&(ZW=!1,$W(b)),g.H("watchAdsInit"))},YW=function(){bX&&null!=WW&&null!=WW.getOptions&&null!=WW.getOptions()&&g.Ma(WW.getOptions(),"ad")&&WW.getOption("ad","PAGE_JAVASCRIPT_INITIALIZED",{})},
UW=function(){var a=window.Goog_Osd_UnloadAdBlock,b=g.z("google_companion_ad_div");
g.Da(a)&&null!=b&&a(g.Wo(b))},kpa=function(a){cX.length=0;
if("afv_vars"in a)for(var b in a.afv_vars)window[b]=a.afv_vars[b],cX.push(b)},opa=function(a){"googletag"in window&&googletag&&(googletag.cmd=googletag.cmd||[],googletag.cmd.push(function(){if(dX=googletag.defineSlot(a,[[300,
250],[300,60]],"google_companion_ad_div")){dX.set("ad_type","flash");dX.addService(googletag.companionAds());googletag.enableServices();var b=dX.getSizes();b&&2<=b.length&&(eX=b[0],fX=b[1])}}))},gX=function(a,b){a||(a="");
b||(b=!1);var c=g.z("watch-channel-brand-div");c&&g.uq(c,"collapsible",b);if(c=g.z("google_companion_ad_div"))c.innerHTML=a},hX=function(a){var b=Math.round(1E4*Math.random());
return['<iframe src="',a,'" name="ifr_300x250ad',b,'" id="ifr_300x250ad',b,'" width="300" height="250" marginwidth="0" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no"></iframe>'].join("")},iX=function(a){return!!a.match("/ad_companion.*render=video_wall_companion")},ppa=function(){g.H("showCompanionAdLoaded")},XW=function(){window.google_ad_output="html";
window.google_ad_height="250";window.google_ad_format="300x250_as";window.google_container_id="google_companion_ad_div"},lX=function(){var a=document.getElementById("google_companion_ad_div");
if(a&&(a=a.firstElementChild)){"DIV"==a.nodeName&&(a=a.firstElementChild);try{var b=encodeURIComponent(jX)+","+encodeURIComponent(kX);a.contentWindow.postMessage(b,"*");a.width=370;a.height=null!=jX?210:185}catch(c){}}},mX=function(){var a=document.getElementById("movie_player");
a&&a.pauseVideo()},npa=function(a){xV(a.pyv_ad_tag.tag);
a.log_pyv&&nX.push(g.ah(function(){"google_render_ad"in window?g.Qk("pyvls"):g.Qk("pyvlf")},5E3))},$W=function(a){if(!oX){if(!a){if(!VW){ZW=!0;
return}a=VW}if(g.Sf("remove_yt_uds")){oX=!0;window.google_ad_client=a.afv_vars.google_ad_client;window.google_page_url=a.afv_vars.google_page_url;window.google_page_location=window.location.href;var b=a.afc_vars,c;for(c in b){var d=b[c];if("no_initial_ads"==c&&d){CV();return}if("format"!=c||g.pb(g.Rn(d)))if("loeid"!=c||g.pb(g.Rn(d))){var e="google_"+c;(zV[e]||AV[e]||BV[e])&&(window[e]=d)}else window.google_loeid=g.Rn(d);else if(d=g.Rn(d),e=d.match(/(\d+)x(\d+)/))window.google_ad_width=e[1],window.google_ad_height=
e[2],window.google_ad_format=d}b=new Una;ooa(b);window.google_loader_used="yt";(b=ipa(b))&&qpa(b);CV()}else(b=g.u("google.ads.Ad"))?(oX=!0,new b(a.afv_vars.google_ad_client,"google_companion_ad_div",a.afc_vars)):pX=g.$f(function(){$W(a)},200)}},qpa=function(a){var b=g.z("google_companion_ad_div");
null!=b&&(a=g.nd("IFRAME",{width:window.google_ad_width,height:window.google_ad_height,frameBorder:0,marginWidth:0,marginHeight:0,vpsace:0,hspace:0,allowTransparency:"true",scrolling:"no",src:a,style:{visibility:"visible"}}),b.appendChild(a))},lpa=function(){YW()},mpa=function(){bX=!0;
YW()},rpa=function(a){var b=null;
"transition"in a.style?b="transition-duration":"webkitTransition"in a.style?b="-webkit-transition-duration":"MozTransition"in a.style?b="-moz-transition-duration":"OTransition"in a.style?b="-o-transition-duration":"msTransition"in a.style&&(b="-ms-transition-duration");a=b?(document.defaultView?document.defaultView.getComputedStyle(a,null):document.parentWindow.getComputedStyle(a,null)).getPropertyValue(b):"0";return 1E3*parseFloat(a)},qX=function(){g.X.call(this);
this.G=this.J=this.H=this.D=null},rX=function(a,b){if(a&&b){var c=g.kP(a);
g.rd(b);g.So(b,c,0)}},sX=function(){g.X.call(this);
this.H=null;this.G=0;this.N={report:(0,g.v)(this.XF,this),share:(0,g.v)(this.wG,this)}},tX=function(a){a.G&&(g.cg(a.G),a.G=0);
a.Ud&&(a.Ud.dispose(),a.Ud=null)},spa=function(a){a.Ud=new g.BM(a.D,a.J,a.W,null,null,!1,!1,g.E("SHARE_REFERER",void 0),g.E("SHARE_CAPTION",void 0),null,null,null,null,null,g.E("PLAYLIST_INDEX",void 0),null,"metadata",g.E("EVENT_ID",void 0),null,!0);
g.Sd(a,a.Ud);g.cg(a.G);a.G=g.ag(function(){var b=g.kL().getCurrentTime(),c=Math.floor(b/3600),d=Math.floor(b%3600%60);b=(0<c?c+":":"")+g.kc(Math.floor(b%3600/60),0<c?2:1)+":"+g.kc(d,2);this.Ud.updateTime(b)},1E3)},vpa=function(){if(uX=g.M("mealbar-promo-renderer")){var a=g.M("yt-uix-button-primary",uX);
if(a){var b=g.M("yt-uix-button-blue-text",uX);if(b){var c=g.M("ad-blocker-msg-data");c&&(vX.push(g.I(a,"click",tpa,!0),g.I(b,"click",upa,!0)),g.F(c,"freq-cap"),wX=g.um(),xX("AD_BLOCKER_MESSAGING_EVENT_TYPE_DISPLAYED"))}}}},tpa=function(){xX("AD_BLOCKER_MESSAGING_EVENT_TYPE_LEARN_HOW");
yX();g.cq(uX,!1)},upa=function(){xX("AD_BLOCKER_MESSAGING_EVENT_TYPE_DISMISSED");
yX();g.cq(uX,!1)},xX=function(a){var b=g.yi();
b&&(a={displayPeriodMs:Math.round(g.um()-wX),adBlockerMessagingEventType:a,clientScreenNonce:b},g.Zh("adBlockerMessagingShown",a))},yX=function(){g.Vg(vX);
vX.length=0},xpa=function(){(0,g.B)(g.L("promoted-button-container"),function(a){a:{var b=g.F(a,"promo-id");
var c=g.Iq(a,"promo-impression-cap")||0;var d=g.Iq(a,"promo-impression-delay")||0;if(b&&0<c&&0<d){b="yt-hint-"+b;var e=g.wx(b)||{},f=e.lastSeen;e=e.impressions||0;if(f&&(0,g.$c)()-new Date(f)<1E3*d||e>=c){c=!1;break a}e={lastSeen:(0,g.$c)(),impressions:e+1};g.vx(b,e,2592E3)}c=!0}c?("true"===g.F(a,"promo-visible")&&(c=g.EB.getInstance(),c.wm(a),"hidden"!=window.getComputedStyle(a).visibility&&(c.show(a),g.D(a,"hide-hint-on-scroll")&&(c=g.z(g.F(a,"scroll-parent"))||window,zX.push(g.Wg(c,"scroll",(0,g.v)(wpa,
this,a)))))),g.gH(a)):(a=g.M("generic-promo-impression-logging",a))&&g.R(a,"generic-promo-impression-logging")})},wpa=function(a){g.EB.getInstance().hide(a)},AX=function(a,b){g.X.call(this,b);
this.qa=a;this.G=null;this.D=250;this.aa=this.T=this.N=this.W=this.H=this.J=null;this.na=0},BX=function(a,b,c){for(var d=0;d<a.length;d++)if(g.rd(a[d]),b){var e=g.kP(b,c);
g.So(a[d],e,0)}},Apa=function(){var a=g.M("youthere-data");
CX=!1;if(DX=g.M("mealbar-promo-renderer"))if(EX=g.M("yt-dialog-title",DX))if(FX=g.M("yt-ytb",DX))if(GX=g.M("youthere-conf"))if(HX=g.M("youthere-pause-msg"))IX=parseInt(g.F(a,"pause-del"),10),JX=parseInt(g.F(a,"lact-th"),10),KX=parseInt(g.F(a,"prompt-del-sec"),10),LX.push(g.I(FX,"click",MX,!0)),NX.push(g.ig("player-ad-end",ypa)),NX.push(g.ig("yt-ui-dialog-show-complete",zpa)),CX=OX=!0},ypa=function(){CX&&g.jh()<JX&&PX("YOU_THERE_EVENT_TYPE_BELOW_LACT_THRESHOLD")},zpa=function(a){OX=!1;
var b=DX;b&&a&&a.F==b&&((a=g.Lv())&&ioa(a),g.$f(function(){LX.push(g.I(document,"scroll",MX,!0));LX.push(g.I(document,"click",MX,!0))},500),QX=g.$f(Bpa,IX),PX("YOU_THERE_EVENT_TYPE_PROMPT_SHOWN"))},MX=function(){OX=!0;
RX();if(SX){var a=document.getElementById("movie_player");a&&a.playVideo()}g.cq(FX,!1);a=GX;g.To(a,EX);a.className=EX.className;EX=a;g.$f(Cpa,400);PX("YOU_THERE_EVENT_TYPE_USER_RESPONDED")},RX=function(){g.bg(QX);
g.jg(NX);g.Vg(LX);NX.length=LX.length=0},Bpa=function(){if(!OX){var a=HX;
g.To(a,EX);a.className=EX.className;EX=a;if(a=document.getElementById("movie_player"))a.pauseVideo(),SX=!0,PX("YOU_THERE_EVENT_TYPE_PLAYBACK_PAUSED")}},Cpa=function(){var a=new g.NG(EX,1E3);
a.play();a.O("finish",function(){g.cq(DX,!1)})},PX=function(a){var b=g.yi();
b&&(a={clientScreenNonce:b,lactMs:String(g.jh()),lactThresholdMs:String(JX),mediaPosSec:KX,youThereEventType:a},g.Zh("youThere",a))},Dpa=function(){-1!=g.Tf("service_worker_push_logged_out_prompt_watches")&&g.Mj("WatchCount").then(function(a){100<=a||g.Lj("WatchCount",a+1)})},Lpa=function(){TX=g.M("toggle-loop",UX);
UX=g.z("watch-appbar-playlist");VX=g.M("playlist-videos-list",UX);WX=g.M("shuffle-playlist",UX);XX=g.M("next-playlist-list-item",UX);YX=g.M("prev-playlist-list-item",UX);ZX=g.M("playlist-header-content",UX);$X="currently-playing";if(UX&&VX){var a=g.kL();a&&(aY=a,a.addEventListener("onReady",bY));ZX&&(cY="true"===g.F(ZX,"initial-loop-state"));dY.push(g.I(TX,"click",Epa));dY.push(g.I(WX,"click",Fpa));dY.push(g.I(XX,"click",function(b){eY(b,"bf_next")}));
dY.push(g.I(YX,"click",function(b){eY(b,"bf_prev")}));
dY.push(g.$q(VX,Gpa));dY.push(g.S(VX,"click",Hpa,"yt-uix-button-playlist-remove-item"));fY.push(g.ig("navigate",Ipa));fY.push(g.ig("player-state-change",Jpa));fY.push(g.ig("player-error",Kpa));fY.push(g.ig("watch-queue-show",function(b){g.Sk()&&(0==b?g.Q(UX,"watch-queue-nav"):g.W(UX))}));
fY.push(g.ig("watch-queue-hide",function(){g.V(UX);g.R(UX,"watch-queue-nav")}));
g.Sk()&&vV()&&(0==wV()?g.Q(UX,"watch-queue-nav"):g.W(UX));g.E("SKIP_TO_NEXT_VIDEO")&&gY(5);hY();iY();jY()}},pY=function(a,b){var c=XX;
if(b){if(!kY().loop||lY)return;var d=ZX;if(d){var e=mY(d,"auto");var f=g.F(d,"autoplay-clicktracking")||""}}else nY(),e=mY(c,"next"),f=g.F(c,"clicktracking")||"";f=oY(a||"bf_next",f,b,e);g.qj(c.href,f)},qY=function(a){var b=a||"bf_prev";
a=YX;var c=mY(a,"prev"),d=g.F(a,"clicktracking")||"";b=oY(b,d,!1,c);g.qj(a.href,b)},kY=function(){var a=[],b=-1,c=VX;
if(!c)return null;(0,g.B)(c.getElementsByTagName("li"),function(e,f){g.D(e,$X)&&(b=f);var k={encrypted_id:g.F(e,"video-id"),author:g.F(e,"video-username"),title:g.F(e,"video-title"),start:g.F(e,"video-clip-start"),end:g.F(e,"video-clip-end"),iurl:g.F(e,"thumbnail-url")};a.push(k)});
c=ZX;var d=b+1<a.length||cY;return{author:g.F(c,"list-author"),loop:d,index:b,list:g.F(c,"full-list-id"),title:g.F(c,"list-title"),description:g.F(c,"list-description"),video:a}},iY=function(){g.H("yt-dom-content-change",VX)},mY=function(a,b){var c=g.E("SHUFFLE_VALUE"),d=cY,e="normal";
c&&d?e="loop_shuffle":c?e="shuffle":d&&(e="loop");return g.F(a,e+"-"+b+"-clicktracking")},bY=function(a){aY&&aY.removeEventListener("onReady",bY);
aY=a;a.addEventListener("onCueRangeEnter",rY);var b=a.getDuration(),c=g.E("PREFETCH_AUTOPLAY"),d=g.E("PREFETCH_AUTOPLAY_TIME",10);c&&a.addCueRange("AUTOPLAY_PREFETCH",b-d,b);g.E("EXP_DEBUG_PREFETCH")&&g.Qk(g.wc({a:"registerNearEndEventsWithPlayer",endTime:b,prefetchEnabled:c,prefetchTime:d}));a.addEventListener("onPlaylistNext",pY);a.addEventListener("onPlaylistPrevious",qY);a.addEventListener("onPlaylistIndex",sY)},rY=function(a){if("AUTOPLAY_PREFETCH"==a&&(a=g.E("PREFETCH_AUTOPLAY_TIME",10),kY().loop&&
!lY&&!tY)){tY=!0;
var b=ZX;if(b){var c=mY(b,"auto");var d=g.F(b,"autoplay-clicktracking")||""}b=XX.href;d=oY("autoplay",d,!0,c,a);g.zE(b,!!g.E("PREBUFFER_AUTOPLAY"),d,Mpa)}},Mpa=function(a){tY=!1;
uY=a.response.cacheKey||null},nY=function(){uY&&(spf.cache.remove(uY),uY=null)},jY=function(){g.eh()?(g.bh(vY),vY=g.ah(g.w(g.kg,"watch-list-change"))):g.H("watch-list-change")},gY=function(a){0==a?pY("mr_meh",!0):wY=g.$f(function(){gY(a-1)},1E3)},xY=function(){var a=ZX;
return!(!a||"False"==g.F(a,"shareable"))},Epa=function(){var a=TX;
a&&(cY=!g.Tz.getInstance().isToggled(a))},Fpa=function(){var a=VX,b=g.Qa(a.getElementsByTagName("li")),c=WX;
c&&g.Tz.getInstance().isToggled(c)?(b=Npa(b),g.Nf("SHUFFLE_VALUE",0)):(c=Opa(b),b=Ppa(b,c));g.rd(a);(0,g.B)(b,function(d){a.appendChild(d)});
c=g.E("SHUFFLE_VALUE");yY(b,c);hY();iY();zY();jY()},zY=function(){var a=0;
(0,g.B)(g.Ko("li",null,VX),function(b){(b=g.M("index",b))&&!isNaN(b.innerText)&&g.N(b,a+1);a+=1})},Gpa=function(a){var b=g.op(a.currentTarget,"li"),c=g.F(b,"clicktracking")||"";
b=g.F(b,"innertube-clicktracking")||"";AY(a,void 0,c,b)},eY=function(a,b){var c=g.F(a.currentTarget,"clicktracking")||"";
AY(a,b,c)},AY=function(a,b,c,d){b=oY(b||"BFa",c,!1,d);
c=a.currentTarget.href;d={};var e=g.E("SHUFFLE_VALUE");e?d.shuffle=e:-1!=c.indexOf("shuffle=")&&(d.shuffle=0);d&&(c=g.uh(c,d));g.dc(a.currentTarget,c);g.oj(c,b);nY()},Hpa=function(a){var b=ZX,c=g.op(a.currentTarget,"li");
if(b&&c){var d=VX;g.Q(d,"playlist-editing-locked");a=g.F(b,"full-list-id");var e=g.F(c,"video-id"),f=g.Iq(c,"index");g.PA("delete_from_playlist",{videoIds:e,fullListId:a,onSuccess:function(){g.sd(c);var k=g.Ko("li",null,d),l=g.M("currently-playing",d);(0,g.B)(k,function(p){var t=g.Iq(p,"index");t>f&&g.Jq(p,"index",t-1)});
"RD"!=g.F(b,"full-list-id").substring(0,2)&&zY();l=l&&g.Iq(l,"index")+1||0;var m=g.z("playlist-current-index");m&&g.N(m,l);(l=g.z("playlist-length"))&&g.N(l,k.length);yY(k,g.E("SHUFFLE_VALUE"))},
Xa:function(){g.R(d,"playlist-editing-locked");jY()}})}},Jpa=function(a){0==a&&pY("autoplay",!0)},Kpa=function(){},Ipa=function(){lY=!0},Ppa=function(a,b){function c(f){var k=0,l=[];
for(f=f.split("");f.length;){k=(b+k)%f.length;var m=f[k];g.Oa(f,k);l.push(m)}return l.join("")}
g.kn(a,function(f,k){var l=g.F(f,"video-id"),m=g.F(k,"video-id");return c(l).localeCompare(c(m))});
var d=b>>8,e=g.Ja(a,function(f){f=g.F(f,"index");return d==f})||0;
0<e&&(a=g.fn(a,e).concat(g.fn(a,0,e)));return a},Npa=function(a){g.kn(a,function(b,c){var d=g.Iq(b,"index"),e=g.Iq(c,"index");
return d-e});
return a},Opa=function(a){var b=g.E("SHUFFLE_VALUE");
if(!b){var c=0;(0,g.B)(a,function(d){g.D(d,$X)&&(c=g.F(d,"index"))});
b=(c<<8)+Math.floor(256*Math.random());g.Nf("SHUFFLE_VALUE",b)}return b},yY=function(a,b){var c=null;
(0,g.B)(a,function(l){g.D(l,$X)&&(c=l)});
if(c){var d=g.Xo(c);d||(d=a[0]);var e=g.Yo(c);e||(e=a[a.length-1]);var f=XX,k=YX;f&&d&&(d={v:g.F(d,"video-id")},b?d.shuffle=b:-1!=f.href.indexOf("shuffle=")&&(d.shuffle=0),g.dc(f,g.uh(f.href,d)));k&&e&&(d={v:g.F(e,"video-id")},b?d.shuffle=b:-1!=k.href.indexOf("shuffle=")&&(d.shuffle=0),g.dc(k,g.uh(k.href,d)))}},oY=function(a,b,c,d,e){var f={},k=g.E("EVENT_ID");
k&&(f.ei=k,a&&(f.feature=a),d?f.itct=d:b&&(f.ved=b),(a=g.E("SHUFFLE_VALUE"))&&(f.shuffle=a),cY&&(f.loop_on=!0),c&&(f.playnext=g.E("LIST_AUTO_PLAY_VALUE"),f.autonav=1,c=g.jh(),0<c&&(f.lact=c),e&&(f.prefetch=e),(e=aY)&&e.isReady()&&(e=e.getVisibilityState(),0!=e&&(f.vis=e))));return f},hY=function(){var a=g.M("playlist-videos-list",UX),b=g.M($X,a);
if(b){var c=g.yC.getInstance();if(a&&b&&(b=(0,g.La)(g.L(g.Y(c,"scroll-unit"),a),b),0<=b&&!(!a||isNaN(b)||0>b)&&(c=g.L(g.Y(c,"scroll-unit"),a),!(0>=c.length)))){b>=c.length&&(b=c.length-1);if(c.length){var d=c[0];var e=d.offsetHeight;1<c.length&&(e=c[1].offsetTop-d.offsetTop);d=e}else d=0;e=a.offsetHeight;b>Math.max(Math.floor(a.scrollTop/d),0)-1&&(d=Math.floor(e/d),e=c.length,b+d>e&&(b=e-d+1));0>b&&(b=0);b=c[b].offsetTop;a&&!isNaN(b)&&(0>b&&(b=0),a.scrollTop=b,g.Jq(a,"scroller-offset",b+""),g.H("yt-dom-content-change",
a))}}},sY=function(a){a=g.Uo(VX)[a];
g.Iq(a,"index");a&&(a=g.M("playlist-video",a))&&a.click()},Qpa=function(a){var b=0,c=g.kL();
c&&c.isReady()&&(b=c.getCurrentTime());b=Math.floor(b);var d=Math.floor(b/60);b={action_get_report_video_component:1,video_id:g.E("VIDEO_ID"),t_mins:d,t_secs:b-60*d};"METADATA_LANGUAGE"in g.Mf&&(b.metadata_language=g.E("METADATA_LANGUAGE"));c&&c.isReady()&&(c=c.getOption("cc","track")||c.getOption("captions","track"))&&(b.cc_vss_id=c.vss_id);return g.J("/watch_ajax",{method:"GET",Ta:b,onSuccess:function(e,f){a(f.report_html,!0)},
onError:function(){a(null,!1)},
ob:!0})},CY=function(a,b){g.C.call(this);
this.M=a;this.F=b;this.J=g.z("watch8-secondary-actions");this.D="action-panel-none";this.C=[];this.G=[];this.H=null;this.L=0;this.G.push(g.ig("player-share",this.Fq,this));this.G.push(g.ig("livestreaming-likes-updated",this.eH,this));this.C.push(g.S(this.M,"click",(0,g.v)(this.Cq,this),"action-panel-trigger"));this.C.push(g.S(this.F,"click",(0,g.v)(this.Ux,this),"yt-uix-close"));var c=g.z("action-panel-overflow-menu");c&&this.C.push(g.S(c,"click",(0,g.v)(this.Cq,this),"action-panel-trigger"));c=g.gr(window.location.hash).action;
"share"==c?this.Fq():"flag"==c&&BY(this,"action-panel-report")},Rpa=function(){var a=g.M("yt-uix-button-toggled",g.z("action-panel-share")),b;
xY()&&a?b=g.F(a,"video-id"):b=g.E("VIDEO_ID",void 0);return b},Spa=function(){var a=null;
if(xY()){var b=g.z("share-with-playlist");if(!b||b&&b.checked)a=(a=ZX)?g.F(a,"full-list-id"):""}return a},BY=function(a,b,c,d){var e=g.M("watch-secondary-actions");
PU(g.Tz.getInstance(),e);e=g.z(b);var f=Tpa(a,e);e&&f&&(g.Q(f,"yt-uix-button-toggled"),DY(a,b,c,d))},DY=function(a,b,c,d){if("action-panel-none"!=b){var e=g.z(b);
if(e){var f=!!g.F(e,"auth-required");e=!!g.F(e,"panel-loaded");if(f&&!g.E("LOGGED_IN"))EY(a,"action-panel-login");else if(e)EY(a,b);else switch(b){case "action-panel-share":Upa(a,c,d);break;case "action-panel-transcript":Vpa(a);break;case "action-panel-add-transcript":b=g.z("action-panel-add-transcript");g.V(g.z("watch-actions-add-transcript"));g.Jq(b,"panel-loaded","true");EY(a,"action-panel-add-transcript");break;case "action-panel-report":Wpa(a)}}}},Upa=function(a,b,c){var d=Rpa(),e=Spa(),f=g.z("action-panel-share"),
k=g.z("watch-actions-share-panel"),l=g.E("SHARE_CAPTION",void 0),m=g.E("SHARE_REFERER",void 0),p=g.E("PLAYLIST_INDEX",void 0),t=g.E("EVENT_ID",void 0),y=!!g.E("LIVESTREAMING_NO_SHARE_TIME");
if(g.E("LIVESTREAMING_DEFAULT_BROADCAST")&&-1==document.location.href.indexOf(d))var A=document.location.pathname;var G=new g.BM(k,d,e,(0,g.v)(a.sE,a),null,b,y,m,l,null,null,null,null,null,p,null,"watch",t,A,c);g.Sd(a,G);g.cg(a.L);var O=g.ag(function(){var T=g.kL(),ra=g.sv(f);if(T&&T.isReady()&&ra){T=T.getCurrentTime();ra=Math.floor(T/3600);var Ba=Math.floor(T%3600%60);T=(0<ra?ra+":":"")+g.kc(Math.floor(T%3600/60),0<ra?2:1)+":"+g.kc(Ba,2);G.updateTime(T)}else g.cg(O)},1E3);
a.L=O;g.Jq(f,"panel-loaded","true");EY(a,"action-panel-share")},Wpa=function(a){var b,c=!1,d=!1,e=g.z("action-panel-report"),f=(0,g.v)(function(){EY(this,"action-panel-error")},a);
g.ij(g.E("REPORTVIDEO_CSS",void 0));g.mg(g.E("REPORTVIDEO_JS",void 0),(0,g.v)(function(){this.qb()||(c=!0,d&&c&&FY(e,b))},a));
a.H=Qpa((0,g.v)(function(k,l){l?(d=!0,b=k,d&&c&&(FY(e,b),e.focus())):f()},a));
g.Jq(e,"panel-loaded","true");EY(a,"action-panel-report")},FY=function(a,b){g.In(a,b);
g.u("yt.www.report.reportvideo.init")(!0)},Vpa=function(a){var b=g.z("action-panel-transcript");
g.u("yt.www.watch.transcript.open")(function(){g.W("watch-actions-transcript-loading");g.V(g.z("watch-actions-transcript"))});
g.Jq(b,"panel-loaded","true");EY(a,"action-panel-transcript")},EY=function(a,b){var c=g.z(a.D),d=g.z(b),e=a.F;
b==a.D?g.V(c):(g.V(e),a.D=b,g.W(c),g.V(d))},Tpa=function(a,b){return g.Ka(g.L("action-panel-trigger",a.M),function(c){c=g.F(c,"trigger-for");
return b.id==c})},bqa=function(){if(GY=g.z("watch7-preview"))g.OF(),HY.push(g.S(GY,"click",Xpa,"watch-queue-preview-playlist-checkbox")),HY.push(g.S(GY,"click",Ypa,"preview-play-now-button")),HY.push(g.S(GY,"click",Zpa,"preview-play-all-now-button")),HY.push(g.S(GY,"click",IY,"preview-addto-queue-button")),HY.push(g.S(GY,"click",$pa,"preview-addto-queue-button-success")),HY.push(g.S(GY,"click",IY,"preview-addto-queue-button-error")),HY.push(g.S(null,"click",aqa,"watch-queue-preview-menu-choice")),
JY.push(g.ig("watch-queue-show",function(){KY()?LY():g.W(GY)})),JY.push(g.ig("watch-queue-hide",function(){g.tz()||g.W(GY)})),JY.push(g.ig("watch-queue-update",MY)),JY.push(g.ig("watch-queue-empty",function(){KY()?LY():g.W(GY)})),g.Wo(GY)&&(g.E("LIST_ID")&&g.uq(GY,"preview-playlist-mode",!0),NY=g.M("preview-play-loading",GY),OY=g.M("preview-play-now-button",GY),PY=g.M("preview-play-all-now-button",GY),QY=g.M("preview-addto-queue-button",GY),RY=g.M("preview-addto-queue-button-success",GY),SY=g.M("preview-addto-queue-button-error",
GY),g.W(NY)),(KY()||TY())&&LY(),UY=!0},TY=function(){if(!uV())return!1;
var a=!g.sv("player-unavailable"),b=g.Bx()?g.wx("yt-remote-session-video-id"):"";return a&&!(b==g.E("VIDEO_ID")&&!g.E("LIST_ID"))},LY=function(){if(!g.sv(GY)&&g.Wo(GY)){var a=uV();
if(a){var b=g.M("video-receiver",GY);b&&g.N(b,a.name)}MY();g.W(NY);VY()?(g.W(OY),g.V(PY)):(g.W(PY),g.V(OY));g.V(GY)}},VY=function(){return g.D(GY,"preview-playlist-mode")},MY=function(){if(g.Wo(GY)&&!VY()){var a=g.YF();
a=g.Ma(a,g.E("VIDEO_ID",void 0));g.rv(RY,a);g.rv(QY,!a);g.W(SY)}},Xpa=function(a){g.uq(GY,"preview-playlist-mode",a.currentTarget.checked);
VY()?(g.V(PY),g.V(QY),g.W(RY),g.W(SY),g.W(OY)):(g.V(OY),g.W(PY),MY())},Ypa=function(){g.V(NY);
g.W(OY);g.H("watch-queue-addto-video-play-now",g.E("VIDEO_ID",void 0))},Zpa=function(){g.V(NY);
g.W(PY);g.H("watch-queue-addto-playlist-play-now",g.E("LIST_ID",void 0),g.E("VIDEO_ID",void 0),WY())},IY=function(){var a=g.E("VIDEO_ID",void 0),b=g.E("LIST_ID",void 0),c=WY();
if(VY()){a=function(){g.V(RY);g.W(QY);g.W(SY);g.H("watch-queue-addto-playlist-added")};
var d=function(){g.V(SY);g.W(RY);g.W(QY)};
c?g.SF(c,a,d):g.VF(b,a,d)}else g.SF(a,function(){g.V(RY);g.W(QY);g.W(SY);g.H("watch-queue-addto-video-added")},function(){g.V(SY);
g.W(RY);g.W(QY)})},$pa=function(){var a=g.E("VIDEO_ID",void 0);
VY()?g.WF(function(){g.V(QY);g.W(RY);g.W(SY);g.H("watch-queue-addto-playlist-removed")},function(){g.V(SY);
g.W(RY);g.W(QY)}):g.UF(a,function(){g.V(QY);
g.W(RY);g.W(SY);g.H("watch-queue-addto-video-removed")},function(){g.V(SY);
g.W(RY);g.W(QY)})},aqa=function(a){var b=g.F(a.currentTarget,"action");
cqa[b](a.currentTarget)},KY=function(){var a=!g.sv("player-unavailable"),b=wV();
b=vV()&&0==b;return a&&g.Sk()&&(b||TY())},WY=function(){var a;
(a=g.E("LIST_ID"))?(a=a.substr(0,2),a="PL"!=a&&"RD"!=a):a=!1;if(!a)return null;a=kY();if(!a)return null;a=a.video;for(var b=[],c=0;c<a.length;c++)b.push(a[c].encrypted_id);return b},YY=function(a){if(!(a.metaKey||a.ctrlKey||XY(a.target)||XY(document.activeElement)||a.event&&!1===a.event.returnValue))switch(a.keyCode){case 191:break;
default:g.kg("player-unhandled-keydown",a)}},XY=function(a){return a&&("INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"EMBED"==a.tagName||a.isContentEditable)?!0:!1},jqa=function(){if(!ZY){var a=g.u("ytplayer.config");
if(a&&(ZY=g.Jj("player-api")||g.Hj("player-api",a))){a=ZY;a.addEventListener("onReady",$Y);a.addEventListener("onStateChange",aZ);a.addEventListener("onVideoProgress",bZ);a.addEventListener("SHARE_CLICKED",cZ);a.addEventListener("SIZE_CLICKED",dZ);a.addEventListener("onError",eZ);a.addEventListener("onAdStart",fZ);a.addEventListener("onAdComplete",dqa);a.addEventListener("onAdSkip",eqa);a.addEventListener("onAdEnd",fqa);a.addEventListener("onAutonavChangeRequest",gZ);a.addEventListener("onAutonavPauseRequest",
hZ);a.addEventListener("onFeedbackStartRequest",iZ);a.addEventListener("onFeedbackArticleRequest",jZ);a.addEventListener("onScreenChanged",kZ);a.addEventListener("onLogClientVeCreated",lZ);a.addEventListener("onLogServerVeCreated",mZ);a.addEventListener("onLogVeClicked",nZ);a.addEventListener("onLogVesShown",oZ);a.addEventListener("onYpcContentRequest",pZ);a.addEventListener("onPlayVideo",qZ);a=document.activeElement;var b=g.z("movie_player");a&&a!=document.body||!b||b.focus();rZ();sZ=g.ag(rZ,1E3);
tZ.push(g.ig("navigate",gqa));tZ.push(g.ig("player-unhandled-keydown",hqa));tZ.push(g.ig("watch-list-change",iqa));uZ(goa);uZ(doa)}}},iqa=function(){var a=ZY;
if(a&&a.isReady()){var b=kY();a.updatePlaylist(b)}},kqa=function(a,b){var c=vZ();
if(c){var d=g.Rh.get(""+c,"").split(",");d=(0,g.Gk)(d,function(e){return 0!=e.indexOf(a)&&!!e.length});
4<=d.length&&d.shift();d.push(a+":"+b);g.Sh(c,d.join(","),1814400)}},lqa=function(a){var b=vZ();
if(b){var c=g.Rh.get(""+b,"").split(",");c=(0,g.Gk)(c,function(d){return 0!=d.indexOf(a)});
0==c.length?g.Th(b):g.Sh(b,c.join(","),1814400)}},wZ=function(a){var b=g.kL();
if(b&&b.isReady()){a&&g.Nf("RESUME_COOKIE_NAME",a);a=g.E("VIDEO_ID",void 0);var c=b.getDuration();b=Math.floor(b.getCurrentTime());0==c||120>=b||b+120>=c?lqa(a):kqa(a,Math.floor(b))}},$Y=function(a){xZ(a);
yZ(a.getPlayerState());var b=g.E("RELATED_PLAYER_ARGS",void 0);a&&a.updateVideoData&&b&&a.updateVideoData(b)},aZ=function(a){1==a&&xZ(ZY);
yZ(a);g.H("player-state-change",a)},bZ=function(a){g.H("player-video-progress",a)},xZ=function(a){a=a.getAvailableQualityLevels();
g.H("player-quality-data-update",a)},eZ=function(a){g.H("player-error",a)},dZ=function(a){g.Or();
g.Sh("wide",a?"1":"0",-1);g.H("player-resize",a)},cZ=function(){g.H("player-share")},pZ=function(a){var b=ZY;
b&&b.isReady()&&b.pauseVideo();(b=g.z("watch-checkout-offers"))&&g.Ei(g.$P,new g.$E(b,a))},fZ=function(a){g.H("player-ad-start",a)},lZ=function(a){var b=a.id,c=g.yi(),d=g.wi();
a=a.ve_type;var e=mqa++;a=new g.ri({veType:a,veCounter:e,elementIndex:void 0,dataElement:void 0,youtubeData:void 0});zZ[b]=a;c&&d&&g.zr(c,d,[a])},kZ=function(a){var b=a.csn;
a=a.root_ve_type;if(b&&a&&(g.Ai(b,a),a=g.wi()))for(var c in zZ){var d=zZ[c];d&&g.zr(b,a,[d])}},mZ=function(a){zZ[a.id]=g.vr(a.tracking_params)},nZ=function(a){var b=g.yi();
a=zZ[a.id];b&&a&&g.wr(b,a,void 0,void 0)},oZ=function(a){a=a.ids;
for(var b=g.yi(),c=0;c<a.length;c++){var d=zZ[a[c]];b&&d&&g.yr(b,d)}},dqa=function(){g.H("player-ad-complete")},eqa=function(){g.H("player-ad-skip")},fqa=function(){g.H("player-ad-end")},gZ=function(a){g.H("player-autonav-change-request",a)},hZ=function(a){g.H("player-autonav-pause-request",a)},uZ=function(a){AZ?a():(a=g.ig("player-playback-start",a),tZ.push(a))},hqa=function(a){var b=ZY;
b&&b.handleGlobalKeyDown(a.keyCode,a.shiftKey)},BZ=function(a,b){var c=ZY;
if(c&&(UY?!g.sv(GY):!TY())){var d=null!=b?b:!0;c.seekTo(a,!0);d&&window.scroll(0,0);2==c.getPlayerState()&&c.playVideo()}},rZ=function(){if(ZY&&ZY.isReady()){var a=window.location.hash;
if(a!=CZ){CZ=a;a=g.gr(a);if("t"in a&&a.t!=DZ.t){var b=a.t,c=0;-1!=b.indexOf("h")&&(b=b.split("h"),c=3600*b[0],b=b[1]);-1!=b.indexOf("m")&&(b=b.split("m"),c=60*b[0]+c,b=b[1]);-1!=b.indexOf("s")?(b=b.split("s"),c=1*b[0]+c):c=1*b+c;BZ(c,!1)}DZ=a}}},gqa=function(){g.cg(sZ)},yZ=function(a){AZ||1!=a&&2!=a&&0!=a||(AZ=!0,g.H("player-playback-start"))},vZ=function(){return g.E("RESUME_COOKIE_NAME",void 0)},iZ=function(a){g.JD(void 0,a)},jZ=function(a){g.LD(a.articleId,a.helpContext,a.productData)},qZ=function(a){var b=
g.th("/watch",{v:a.videoId,
list:a.listId},!1);g.rj(b,a.sessionData)},nqa=function(a,b){var c=g.xc("/related_ajax",{continuation:a,
action_more_related_videos:1});spf.load(c,{onDone:b})},oqa=function(a){var b=a.currentTarget.href,c=g.kL();
if(c){var d=g.fr(b).v;if(g.E("VIDEO_ID")==d)if(d=g.F(a.currentTarget,"secondary-video-url"),0==c.getPlayerState()&&d)g.dc(a.currentTarget,d);else{c=Math.floor(c.getCurrentTime());a=a.currentTarget;c={t:c};d=b.split("#",2);b=d[0];var e=1<d.length?"#"+d[1]:"";d=g.gr(e);for(var f in c)d[f]=c[f];if(!g.Wa(d)){f="!"=="#".charAt(1)?"#".substr(0,2):"#";c=g.gr("#");for(var k in d)c[k]=d[k];e=f+g.wc(c)}g.dc(a,b+e)}}},pqa=function(a){var b=a.currentTarget;
a=g.F(b,"action");if(b&&"replace-enclosing-action"==a){EZ(b);a=g.M("service-endpoint-replace-enclosing-action-notification",g.Yo(b));var c=g.CA(b)||b,d=g.P(c,"related-list-item");(b=g.M("related-item-dismissable",d))&&c&&((c=g.M("related-item-dismissed-container",d))&&a&&(g.rd(c),g.Po(c,a)),g.W(b),g.V(c),g.V(a),g.ip(d,!0),d.focus())}},qqa=function(a){a=a.currentTarget;
EZ(a);a=g.P(a,"related-list-item");g.V(g.M("related-item-dismissable",a));g.W(g.M("related-item-dismissed-container",a))},EZ=function(a){var b=g.F(a,"dismissal-token"),c=g.F(a,"feedback-token");
a={itct:g.F(a,"innertube-clicktracking")};var d="";b?(d="action_dismiss_item",a.dismissal_token=b,g.E("DISMISS_THROUGH_IT")&&(a.it=1)):c&&(d="action_give_feedback",a.feedback_tokens=[c],a.wait_for_response=1);d&&g.J("/feed_change_ajax?"+d+"=1",{method:"POST",onSuccess:function(){},
ia:a,ob:!0})},GZ=function(a){return-1!=(FZ.get("dismissedEvents",!0)||[]).indexOf(a)},rqa=function(){var a=HZ;
if(!GZ(a)){var b=FZ.get("dismissedEvents",!0)||[];b.push(a);FZ.set("dismissedEvents",b,void 0,!0)}g.W(IZ);g.R(document.body,"gaming-event-promo-visible")},sqa=function(){var a=g.z("live-chat-iframe");
if(a){var b=new g.lP;b.Ra(a);JZ=b}},wqa=function(){var a=g.z("player-messages"),b=tqa=g.M("mealbar-promo-renderer",a);
if(b){var c=g.sd(b),d=g.z("watch-header")||g.z("watch-metadata-header");d&&d.appendChild(c);g.YG(b);g.gH(b);KZ=new g.GB(b,!1,!1,!0,!0,!0);LZ.push(g.I(g.M("dismiss-menu-choice",b),"click",uqa,!0))}MZ=g.M("mealbar-visibility",a);vqa()},vqa=function(){var a=MZ,b=g.F(a,"trigger-condition");
"TRIGGER_CONDITION_POST_AD"==b?((a=g.F(a,"lact-th"))&&(NZ=parseInt(a,10)),OZ.push(g.ig("player-ad-end",function(){PZ(!0)}))):"TRIGGER_CONDITION_DEFAULT"==b?PZ(!1):"TRIGGER_CONDITION_DELAYED"==b&&(a=g.F(a,"prompt-del-sec"))&&(a=parseInt(a,0),0<a&&(QZ=g.ig("player-video-progress",xqa),RZ=a))},uqa=function(){KZ&&KZ.dismiss("cancel")},PZ=function(a){if(a&&(a=NZ,-1<a&&g.jh()<a))return;
KZ&&KZ.show();g.Q(MZ,"vve-check");g.vw()},xqa=function(a){0<RZ&&a>RZ&&(PZ(!1),g.jg(QZ),RZ=-1)},SZ=function(){this.F=[];
this.C=0;this.F.push(g.ig("page-resize",this.ZC,this));this.F.push(g.ig("player-resize",this.Kl,this));this.F.push(g.ig("player-quality-data-update",this.yD,this));this.F.push(g.ig("watch-queue-remote-connection",this.Iq,this));g.Sk()&&this.Iq(!0);this.tg()},zqa=function(){var a=g.kL();
a&&a.getPlayerState&&1==a.getPlayerState()?g.AE():TZ.push(g.ig("player-state-change",yqa))},yqa=function(a){1==a&&g.AE()},Dqa=function(){jqa();
g.eh()?UZ.push(g.$g(g.Nr)):uZ(g.Nr);var a=g.M("watch-action-buttons"),b=g.M("watch-action-panels");VZ=null;a&&b&&(VZ=new CY(a,b));if(a=g.M("video-metadata-renderer"))WZ=new sX,WZ.Ra(a);if(a=g.M("like-button-renderer"))XZ=new qX,XZ.Ra(a);xpa();if(a=g.M("metadata-updateable-viewership"))YZ=new AX(g.E("VIDEO_ID"),null),YZ.Ra(a);ZZ=new SZ;g.hh();g.Jm("ytglobal.ytUtilActivityCallback_",function(){g.H("USER_ACTIVE")});
g.I(document,"keydown",YY);Aqa();vpa();g.E("SKIP_RELATED_ADS")||(g.eh()?UZ.push(g.ah(aX)):aX());g.M("youthere-data")&&Apa();wqa();Lpa();$Z.push(g.S(g.z("watch7-sidebar"),"click",oqa,"resumable-list"));$Z.push(g.S(document.documentElement,"click",pqa,"dismiss-menu-choice"));$Z.push(g.S(document.documentElement,"click",qqa,"undo-replace-action"));zqa();bqa();g.ym&&(!document.documentMode||8>document.documentMode)&&a_.push(g.S(document.body,"click",Bqa,"video-thumb"));g.vH();sqa();if(IZ=g.z("gaming-event-promo-overlay"))if(HZ=
IZ.getAttribute("data-event-id"))GZ(HZ)?g.W(IZ):(g.V(IZ),g.Q(document.body,"gaming-event-promo-visible")),b_.push(g.I(g.z("gaming-event-promo-cancel-button"),"click",rqa));Cqa();g.TL.init();-1!=g.Tf("service_worker_push_logged_out_prompt_watches")&&uZ(Dpa)},Bqa=function(a){g.op(a.target,"BUTTON")||a.currentTarget.click()},Aqa=function(){var a=g.M("whitelist-alert");
a&&(c_=new g.tL,c_.Ra(a))},Cqa=function(){var a=g.fr(window.location.href);
if(window.history.replaceState&&"time_continue"in a||"disable_polymer"in a)a=g.uh(window.location.href,{time_continue:null,disable_polymer:null}),window.history.replaceState(window.history.state,"",a)},Eqa=function(){var a=["guide"];
d_.guide=g.$f(function(){g.M("guide-module-loading")&&(g.Vg(e_.Nv),f_(a,"time",!1))},3E3)},Fqa=function(a){if(!g.z("watch-sidebar-discussion")){var b=g.z("watch-discussion");
if(g.Zo(b)){g.Q(b,"scrolldetect");g.Jq(b,"scrolldetect-callback","comments-delay-load");var c=(0,g.$c)()+1E3;g.qE({"comments-delay-load":function(){var d=c-(0,g.$c)();d_.comments=g.$f(g.w(f_,a,0<d?"time":"scroll"),d)}})}}},f_=function(a,b,c){var d=g.E("VIDEO_ID",void 0);
d||g.Pa(a,"comments");if(a&&a.length){var e=g.fr(window.location.href);e.v=d;e.tr=b;g.Ma(a,"comments")&&g.E("IS_DISTILLER")&&(e.distiller="1",g.E("COMMENTS_TOKEN")?e.ctoken=g.E("COMMENTS_TOKEN"):g.Pa(a,"comments"));g.VD(a,c,e,g.w(Gqa,a))}},Gqa=function(a){g.Ma(a,"comments")&&(g.TL.init(),(a=g.E("JS_COMMENTS_MODULE_NAMES"))&&spf.script.require(a),g.H("yt-www-comments-page-updated"))},cpa={"AMP-CAROUSEL":"ac",
"AMP-FX-FLYING-CARPET":"fc","AMP-LIGHTBOX":"lb","AMP-STICKY-AD":"sa"},cV=null,$na=[/^https?:\/\/(secure)?pubads\.g\.doubleclick\.net(:\d+)?($|\/)/i,/^https?:\/\/(googleads|adx)\.g\.doubleclick\.net(:\d+)?($|\/)/i,/^https?:\/\/(?!adx)ad.*\.doubleclick\.net(:\d+)?($|\/)/i,/^https?:\/\/(tpc|pagead2)\.googlesyndication\.com(:\d+)?($|\/)/i,/^https?:\/\/www\.googletagservices\.com(:\d+)?($|\/)/i,/^https?:\/\/adservice\.google\.(com?\.)?[a-z]{2,3}(:\d+)?($|\/)/i],Hqa=/^https?:\/\/(\w|-)+\.cdn\.ampproject\.(net|org)(\?|\/|$)/,
coa=[],pV=!1,sV=!1,qV=0,rV="",mqa=1;var g_={},zV=(g_.google_ad_channel="channel",g_.google_ad_type="ad_type",g_.google_ad_format="format",g_.google_color_bg="color_bg",g_.google_color_border="color_border",g_.google_color_link="color_link",g_.google_color_text="color_text",g_.google_color_url="color_url",g_.google_page_url="url",g_.google_allow_expandable_ads="ea",g_.google_ad_section="region",g_.google_cpm="cpm",g_.google_encoding="oe",g_.google_safe="adsafe",g_.google_flash_version="flash",g_.google_font_face="f",g_.google_font_size=
"fs",g_.google_hints="hints",g_.google_ad_host="host",g_.google_ad_host_channel="h_ch",g_.google_ad_host_tier_id="ht_id",g_.google_kw_type="kw_type",g_.google_kw="kw",g_.google_contents="contents",g_.google_targeting="targeting",g_.google_adtest="adtest",g_.google_alternate_color="alt_color",g_.google_alternate_ad_url="alternate_ad_url",g_.google_cust_age="cust_age",g_.google_cust_ch="cust_ch",g_.google_cust_gender="cust_gender",g_.google_cust_interests="cust_interests",g_.google_cust_job="cust_job",
g_.google_cust_l="cust_l",g_.google_cust_lh="cust_lh",g_.google_cust_u_url="cust_u_url",g_.google_cust_id="cust_id",g_.google_language="hl",g_.google_city="gcs",g_.google_country="gl",g_.google_region="gr",g_.google_content_recommendation_ad_positions="ad_pos",g_.google_content_recommendation_columns_num="cr_col",g_.google_content_recommendation_rows_num="cr_row",g_.google_content_recommendation_ui_type="crui",g_.google_content_recommendation_use_square_imgs="cr_sq_img",g_.google_color_line="color_line",
g_.google_disable_video_autoplay="disable_video_autoplay",g_.google_full_width_responsive_allowed="fwr",g_.google_full_width_responsive="fwrattr",g_.efwr="efwr",g_.google_pgb_reactive="pra",g_.google_resizing_allowed="rs",g_.google_resizing_height="rh",g_.google_resizing_width="rw",g_.rpe="rpe",g_.google_responsive_formats="resp_fmts",g_.google_safe_for_responsive_override="sfro",g_.google_video_doc_id="video_doc_id",g_.google_video_product_type="video_product_type",g_.google_webgl_support="wgl",
g_.google_refresh_count="rc",g_),h_={},AV=(h_.google_ad_block="ad_block",h_.google_ad_client="client",h_.google_ad_output="output",h_.google_ad_callback="callback",h_.google_ad_height="h",h_.google_ad_resize="twa",h_.google_ad_slot="slotname",h_.google_ad_unit_key="adk",h_.google_ad_dom_fingerprint="adf",h_.google_ad_width="w",h_.google_captcha_token="captok",h_.google_content_recommendation_columns_num="cr_col",h_.google_content_recommendation_rows_num="cr_row",h_.google_ctr_threshold="ctr_t",h_.google_cust_criteria=
"cust_params",h_.gfwrnwer="fwrn",h_.gfwrnher="fwrnh",h_.google_bfa="bfa",h_.ebfa="ebfa",h_.ebfaca="ebfaca",h_.google_image_size="image_size",h_.google_last_modified_time="lmt",h_.google_loeid="loeid",h_.google_max_num_ads="num_ads",h_.google_max_radlink_len="max_radlink_len",h_.google_mtl="mtl",h_.google_native_settings_key="nsk",h_.google_enable_content_recommendations="ecr",h_.google_num_radlinks="num_radlinks",h_.google_num_radlinks_per_unit="num_radlinks_per_unit",h_.google_pucrd="pucrd",h_.google_reactive_plaf=
"plaf",h_.google_reactive_plat="plat",h_.google_reactive_fba="fba",h_.google_reactive_sra_channels="plach",h_.google_responsive_auto_format="rafmt",h_.armr="armr",h_.google_rl_dest_url="rl_dest_url",h_.google_rl_filtering="rl_filtering",h_.google_rl_mode="rl_mode",h_.google_rt="rt",h_.google_source_type="src_type",h_.google_restrict_data_processing="rdp",h_.google_tag_for_child_directed_treatment="tfcd",h_.google_tag_for_under_age_of_consent="tfua",h_.google_tag_origin="to",h_.google_ad_semantic_area=
"sem",h_.google_tfs="tfs",h_.google_package="pwprc",h_.google_tag_partner="tp",h_.fra="fpla",h_.google_ml_rank="mlr",h_.google_apsail="psa",h_),i_={},BV=(i_.google_core_dbp="dbp",i_.google_lact="lact",i_.google_only_pyv_ads="pyv",i_.google_scs="scs",i_.google_video_url_to_fetch="durl",i_.google_yt_pt="yt_pt",i_.google_yt_up="yt_up",i_);EV.prototype.getUrl=function(a,b,c,d){a=a+"//"+b+c;var e=poa(this)-c.length-d.length;if(0>e)return"";this.C.sort(function(t,y){return t-y});
c=null;b="";for(var f=0;f<this.C.length;f++)for(var k=this.C[f],l=this.F[k],m=0;m<l.length;m++){if(!e){c=null==c?k:c;break}var p=HV(l[m],this.D,",$");if(p){p=b+p;if(e>=p.length){e-=p.length;a+=p;b=this.D;break}this.G&&(b=e,p[b-1]==this.D&&--b,a+=p.substr(0,b),b=this.D,e=0);c=null==c?k:c}}f="";null!=c&&(f=b+"trn="+c);return a+f+d};var j_=null;var UV=g.q.performance,Iqa=!!(UV&&UV.mark&&UV.measure&&UV.clearMarks),SV=g.Sa(function(){var a;if(a=Iqa){var b;if(null===j_){j_="";try{a="";try{a=g.q.top.location.hash}catch(c){a=g.q.location.hash}a&&(j_=(b=a.match(/\bdeid=([\d,]+)/))?b[1]:"")}catch(c){}}b=j_;a=!!b.indexOf&&0<=b.indexOf("1337")}return a});
TV.prototype.disable=function(){this.C=!1;this.events!=this.F.google_js_reporting_queue&&(SV()&&(0,g.B)(this.events,VV),this.events.length=0)};
TV.prototype.start=function(a,b){if(!this.C)return null;var c=RV()||QV();c=new uoa(a,b,c);var d="goog_"+c.label+"_"+c.uniqueId+"_start";UV&&SV()&&UV.mark(d);return c};
TV.prototype.end=function(a){if(this.C&&"number"===typeof a.value){var b=RV()||QV();a.duration=b-a.value;b="goog_"+a.label+"_"+a.uniqueId+"_end";UV&&SV()&&UV.mark(b);!this.C||2048<this.events.length||this.events.push(a)}};XV.prototype.G=function(a,b,c,d,e){e=e||"jserror";try{var f=new EV;f.G=!0;IV(f,1,"context",a);b.error&&b.meta&&b.id||(b=new DV(b,{message:YV(b)}));b.msg&&IV(f,2,"msg",b.msg.substring(0,512));var k=b.meta||{};if(this.F)try{this.F(k)}catch(G){}if(d)try{d(k)}catch(G){}b=[k];f.C.push(3);f.F[3]=b;var l=iV(),m=new hV(g.q.location.href,g.q,!1);b=null;var p=l.length-1;for(d=p;0<=d;--d){var t=l[d];!b&&Hqa.test(t.url)&&(b=t);if(t.url&&!t.kp){m=t;break}}t=null;var y=l.length&&l[p].url;0!=m.depth&&y&&(t=l[p]);
var A=new boa(m,t);A.F&&IV(f,4,"top",A.F.url||"");IV(f,5,"url",A.C.url||"");LV(this.H,e,f,this.D,c)}catch(G){try{LV(this.H,e,{context:"ecmserr",rctx:a,msg:YV(G),url:A&&A.C.url},this.D,c)}catch(O){}}return!0};var JV,ZV,k_,KV=TU(),WV=new TV;
(function(){JV=new qoa;"number"!==typeof KV.google_srt&&(KV.google_srt=Math.random());roa();ZV=new XV;ZV.F=function(b){var c=g.Dd.jerExpIds;if(g.Aa(c)&&0!==c.length){var d=b.eid;if(d){c=[].concat(g.la(d.split(",")),g.la(c));d={};for(var e=0,f=0;f<c.length;){var k=c[f++];var l=k;l=g.Ea(l)?"o"+g.Ga(l):(typeof l).charAt(0)+l;Object.prototype.hasOwnProperty.call(d,l)||(d[l]=!0,c[e++]=k)}c.length=e;b.eid=c.join(",")}else b.eid=c.join(",")}k_&&(b.jc=k_);(c=g.Dd.jerUserAgent)&&(b.useragent=c)};
ZV.D=!0;"complete"==KV.document.readyState?KV.google_measure_js_timing||WV.disable():WV.C&&QU(KV,"load",function(){KV.google_measure_js_timing||WV.disable()});
var a=g.lm.currentScript;k_=a?a.dataset.jc:""})();var rW={pO:0,SK:1,TK:2,aL:8,KO:9,HO:16,DK:17,CK:24,GL:25,bK:26,VJ:27,ot:30,rL:32,uL:40};var wW=728*1.38;g.n(gW,MV);var hW=null,l_={},kW=(l_[8]="google_prev_ad_formats_by_region",l_[9]="google_prev_ad_slotnames_by_region",l_);var mW=navigator,dpa=/^\s*_ga=\s*1\.(\d+)[^.]*\.(.*?)\s*$/,epa=/^[^=]+=\s*GA1\.(\d+)[^.]*\.(.*?)\s*$/,fpa=/^\s*_ga=\s*()(amp-[\w.-]{22,64})$/;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Yl&&g.qd("IFRAME");var Hoa={cK:"google_ads_preview",HK:"google_mc_lab",VK:"google_anchor_debug",UK:"google_bottom_anchor_debug",INTERSTITIAL:"google_ia_debug",pL:"google_scr_debug",tL:"google_ia_debug_allow_onclick",HN:"googleads",ot:"google_pedestal_debug",DO:"google_resize_debug",LO:"google_shoppable_images_debug",MO:"google_shoppable_images_cookie",NO:"google_shoppable_images_forced",EO:"google_responsive_slot_debug",GO:"google_responsive_slot_preview",FO:"google_responsive_dummy_ad"},m_={},Ioa=(m_.google_bottom_anchor_debug=
1,m_.google_anchor_debug=2,m_.google_ia_debug=8,m_.google_resize_debug=16,m_.google_scr_debug=9,m_.googleads=2,m_.google_pedestal_debug=30,m_);var OW={google:1,googlegroups:1,gmail:1,googlemail:1,googleimages:1,googleprint:1},apa=/(corp|borg)\.google\.com:\d+$/;var Coa={13:"<<<LATENCY_REPORTING_FRACTION:j>>>",22:"<<<JS_RNG_EXP_FRACTION:j>>>",24:"<<<ENABLE_CMS_DETECTION_EXP_FRACTION:j>>>",28:"<<<OSD_ACTIVEVIEW_MEASURABLE_FRACTION:j>>>",29:"<<<PAGE_LATENCY_REPORTING_FRACTION:j>>>",60:"<<<REAL_USER_MONITORING_FRACTION:j>>>",66:"<<<REAL_USER_MONITORING_WITH_FLAGS_FRACTION:j>>>",79:"<<<CONTENT_RECOMMENDATION_PEDESTAL_MAX_WIDTH:j>>>",82:"<<<VIEW_OPTIMIZED_MOBILE_SCALING_FACTOR:j>>>",98:"<<<FULL_WIDTH_RESPONSIVE_ELIGIBILITY_FRACTION:j>>>",118:"<<<DISABLE_LAZY_LOAD:j>>>",
126:"<<<ACTIVE_VIEW_MEASUREMENT_STRATEGY_VERIFICATION_FRACTION:j>>>",128:"<<<SHOULD_USE_IAB_CMPS:j>>>",129:"<<<USE_IAB_CMPS_EXP_FRACTION:j>>>",136:"<<<FULL_WIDTH_MANUAL_RESPONSIVE_DISABLED_FRACTION:j>>>",137:"<<<RUM_SCROLL_METRICS_FRACTION:j>>>",149:"<<<AUTO_PAGE_LEVEL_TAG_LAB_MOD_LOWER:j>>>",150:"<<<AUTO_PAGE_LEVEL_TAG_LAB_MOD_WIDTH:j>>>",155:"<<<IMPROVE_COLLISION_DETECTION_HOLDBACK_FRACTION:j>>>",160:"<<<BIG_FORMAT_AD_MOD_LOWER:j>>>",161:"<<<BIG_FORMAT_AD_MOD_WIDTH:j>>>",177:"<<<PAGE_HEIGHT_LOGGING_FRACTION:j>>>",
179:"<<<AUTO_REACTIVE_REQUEST_MOD_LOWER:j>>>",180:"<<<AUTO_REACTIVE_REQUEST_MOD_WIDTH:j>>>"};var xW=null;var n_={},Koa=(n_[16]=4,n_[27]=512,n_[26]=128,n_);var Ooa={nL:5,KK:7,FL:17,fK:41,qO:62,DN:67,BO:82,CO:83,GN:87,vK:89,EK:103,oL:106,kQ:107,XK:108,uJ:124,jQ:126,IJ:128,qL:132,HL:138,FN:139},zW=null,AW=null,BW={};TU();g.Dc("script");/*

 Copyright 2019 The AMP HTML Authors. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS-IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var QW={"image-top":0,"image-middle":1,"image-side":2,"text-only":3,"in-article":4};var RW;g.h=CW.prototype;g.h.Iu=function(a,b){0!=this.C||0!=this.G.length||b&&b!=window?this.Mn(a,b):(this.C=2,this.Ar(new FW(a,window)))};
g.h.Mn=function(a,b){this.G.push(new FW(a,b||this.F));DW(this)};
g.h.BF=function(a){this.C=1;if(a){var b=$V(188,(0,g.v)(this.zr,this,!0));this.D=this.F.setTimeout(b,a)}};
g.h.zr=function(a){a&&++this.H;1==this.C&&(null!=this.D&&(this.F.clearTimeout(this.D),this.D=null),this.C=0);DW(this)};
g.h.MG=function(){return!(!window||!Array)};
g.h.Av=function(){return this.H};
g.h.bH=function(){if(0==this.C&&this.G.length){var a=this.G.shift();this.C=2;var b=$V(190,(0,g.v)(this.Ar,this,a));a.xg.setTimeout(b,0);DW(this)}};
g.h.Ar=function(a){this.C=0;a.mc()};
CW.prototype.nq=CW.prototype.Iu;CW.prototype.nqa=CW.prototype.Mn;CW.prototype.al=CW.prototype.BF;CW.prototype.rl=CW.prototype.zr;CW.prototype.sz=CW.prototype.MG;CW.prototype.tc=CW.prototype.Av;g.ic("var i=this.id,s=window.google_iframe_oncopy,H=s&&s.handlers,h=H&&H[i],w=this.contentWindow,d;try{d=w.document}catch(e){}if(h&&d&&(!d.body||!d.body.firstChild)){if(h.call){setTimeout(h,0)}else if(h.match){try{h=s.upd(h,i)}catch(e){}w.location.replace(h)}}");IW.prototype.read=function(){var a=this.C.get("__gads","");return this.F&&!HW(a)?"Real":a};
IW.prototype.write=function(a){var b=a.getValue();if(this.F){if(!HW(this.C.get("__gads","")))return;HW(b)||(b="Real")}this.C.set("__gads",b,{wl:a.M()-this.D.Date.now()/1E3,path:a.N(),domain:a.Y(),secure:!1})};var Roa=/^\.google\.(com?\.)?[a-z]{2,3}$/,Soa=/\.(cn|com\.bi|do|sl|ba|by|ma|am)$/,JW=g.q,KW,LW;g.Dc("script");var Voa=/^blogger$/,Woa=/^wordpress(.|\s|$)/i,Xoa=/^joomla!/i,Yoa=/^drupal/i,Zoa=/\/wp-content\//,Toa=/\/wp-content\/plugins\/advanced-ads/,Uoa=/\/wp-content\/themes\/genesis/,NW=/\/wp-content\/plugins\/genesis/;for(var o_="margin-left margin-right padding-left padding-right border-left-width border-right-width".split(" "),p_=0;p_<o_.length;p_++);o_="margin-top margin-bottom padding-top padding-bottom border-top-width border-bottom-width".split(" ");for(var q_=0;q_<o_.length;q_++);var PW=/[+, ]/,hpa=/YtLoPri/;var VZ,WZ,XZ,YZ,ZZ,c_,TW,VW;g.h=SW.prototype;g.h.start=function(a){var b={start:0};b.end=a.scrollHeight-a.clientHeight;b.duration=b.end/3;b.yh="linear";this.D=new g.Yv(a,b);this.C=!0;this.F.O(a,"click",this.SH);this.F.O(a,"mouseover",this.VH);this.F.O(a,"mouseout",this.RH);this.F.O(a,"scroll",this.UH)};
g.h.UH=function(){this.G||this.C||(this.D.pause(),this.G=!0)};
g.h.SH=function(){this.D.pause();this.C=!1;this.G=!0};
g.h.VH=function(){this.D.pause();this.C=!1};
g.h.RH=function(){this.C||this.G||(this.D.play(),this.C=!0)};
g.h.dispose=function(){this.F.removeAll();this.G=this.C=!1;this.D=null;this.H=!0};
g.h.qb=function(){return this.H};var jX="",kX="",nX=[],oX=!1,cX=[],WW=null,ZW=!1,pX=0,dX=null,eX=null,fX=null,bX=!1;g.r("yt.www.watch.ads.setAdId",function(a){window.ad_debug=a},void 0);
g.r("yt.www.watch.ads.setCompanion",gX,void 0);g.r("yt.www.watch.ads.showForcedMpu",function(a){var b=hX(a);a=iX(a);gX(b,a)},void 0);
g.r("yt.www.watch.ads.setGutSlotSizes",function(a,b){if(dX){var c=dX.getSizes();g.bn(c);b&&eX&&c.push(eX);a&&fX&&c.push(fX)}},void 0);
g.r("yt.www.watch.ads.handleSetCompanion",function(a){a=a.replace(";dc_seed=",";kmyd=watch-channel-brand-div;dc_seed=");var b=hX(a);a=iX(a);gX(b,a)},void 0);
g.r("yt.www.watch.ads.handleSetAfvCompanionVars",XW,void 0);g.r("yt.www.watch.ads.companionSetupComplete",lX,void 0);g.r("yt.www.watch.ads.pauseVideo",mX,void 0);g.r("yt.www.watch.ads.loadAfc",$W,void 0);g.r("yt.www.watch.ads.isAfcAdVisible",function(){var a=g.z("google_companion_ad_div");return a?(a=g.Wo(a))&&"IFRAME"==a.tagName?g.xb(a.src,"youtube.com%2Fad_frame"):!1:!1},void 0);
g.r("yt.www.watch.ads.checkInit",YW,void 0);g.r("yt.www.watch.ads.initVideoWallCompanionListeners",function(a,b){jX=a;kX=b;window.addEventListener("message",function(c){"companion-setup-complete"==c.data?lX():"pause-video"==c.data&&mX()},!1)},void 0);
g.r("yt.www.watch.ads.getGlobals",function(){return cX},void 0);
g.r("window.google_ad_request_done",window.ZQ,void 0);g.r("yt.www.ads.pyv.pyvWatchAfcCallback",g.jL,void 0);g.r("yt.www.ads.pyv.loadPyvAjax",xV,void 0);g.r("yt.www.watch.ads.restrictioncookie.spr",function(a){g.fj(a+"mac_204?action_fcts=1");return!0},void 0);
g.r("yt.www.watch.ads.isPromotionShelfSlotExist",function(){return null!=g.z("promotion-shelf")},void 0);
g.r("yt.www.watch.ads.promotionShelfClear",function(){var a=g.z("promotion-shelf");a&&(g.Q(a,"hid"),g.rd(a))},void 0);
g.r("yt.www.watch.ads.promotionShelfShow",function(a){var b=g.z("promotion-shelf");b&&(b.appendChild(a),g.R(b,"hid"))},void 0);
g.r("yt.www.watch.ads.addInstreamCompanionWtaUi",function(a){var b=g.z("google_companion_ad_div");if(b){var c=g.M("iv-cards-companion",b)||g.M("iv-website-companion",b)||b;g.Q(b,"companion-with-wta");c.appendChild(a)}else g.Xf(Error("Cannot find google_companion_ad_div"))},void 0);
g.r("setAfvCompanionVars",XW,void 0);g.x(qX,g.X);g.h=qX.prototype;
g.h.Z=function(){qX.V.Z.call(this);this.D=g.M("like-button-renderer-like-button-unclicked",this.K());this.H=g.M("like-button-renderer-like-button-clicked",this.K());this.J=g.M("like-button-renderer-dislike-button-unclicked",this.K());this.G=g.M("like-button-renderer-dislike-button-clicked",this.K());g.F(this.K(),"logged-in")&&(g.Hz(this,"click","like-button-renderer-like-button-unclicked",this.gw),g.Hz(this,"click","like-button-renderer-like-button-clicked",this.yo),g.Hz(this,"click","like-button-renderer-dislike-button-unclicked",
this.ew),g.Hz(this,"click","like-button-renderer-dislike-button-clicked",this.yo));g.ig("new-like-renderer-notification",this.dH,this)};
g.h.Sa=function(){qX.V.Sa.call(this)};
g.h.gw=function(){g.Q(this.D,"hid");g.R(this.H,"hid");g.R(this.J,"hid");g.Q(this.G,"hid");g.H("yt-uix-videolike-liked");g.H("watch-video-liked")};
g.h.yo=function(a){g.R(this.D,"hid");g.Q(this.H,"hid");g.R(this.J,"hid");g.Q(this.G,"hid");g.D(a.target,"like-button-renderer-like-button-clicked")&&g.H("yt-uix-videolike-unliked")};
g.h.ew=function(){g.D(this.D,"hid")&&g.H("yt-uix-videolike-unliked");g.R(this.D,"hid");g.Q(this.H,"hid");g.Q(this.J,"hid");g.R(this.G,"hid")};
g.h.dH=function(a){rX(a.likeCountText,this.D);rX(a.likeCountWithLikeText,this.H);rX(a.dislikeCountText,this.J);rX(a.dislikeCountWithDislikeText,this.G)};g.x(sX,g.X);g.h=sX.prototype;g.h.Z=function(){sX.V.Z.call(this);this.D=this.R("video-metadata-renderer-panel");this.J=g.F(this.Kd(),"video-id");var a=g.M("playlist-header-content",g.z("watch-appbar-playlist"));this.W=a?g.F(a,"full-list-id"):"";g.Hz(this,"click","video-metadata-renderer-button",this.aw)};
g.h.Sa=function(){sX.V.Sa.call(this)};
g.h.X=function(){sX.V.X.call(this);tX(this);this.W=this.J="";this.D=null};
g.h.aw=function(a){a=g.F(a.currentTarget,"action");a in this.N&&(this.T!=a?(this.N[a](),g.V(this.D),this.T=a):(g.W(this.D),this.D&&g.rd(this.D),tX(this),this.T=null))};
g.h.wG=function(){this.Ud||(spa(this),g.Ez("share"))};
g.h.XF=function(){this.H||(g.ij(g.E("REPORTVIDEO_CSS",void 0)),g.mg(g.E("REPORTVIDEO_JS",void 0),(0,g.v)(this.By,this)))};
g.h.By=function(){var a=0,b=g.kL();b&&b.pauseVideo()&&(b.pauseVideo(),a=b.getCurrentTime());a={action_get_report_video_component:1,video_id:this.J,t_mins:Math.floor(a)/60,t_secs:Math.floor(a)%60};"METADATA_LANGUAGE"in g.Mf&&(a.metadata_language=g.E("METADATA_LANGUAGE"));g.J("/watch_ajax",{method:"GET",Ta:a,onSuccess:(0,g.v)(function(c,d){this.H=d.report_html;g.In(this.D,this.H);g.u("yt.www.report.reportvideo.init")(!0)},this),
ob:!0})};var uX=null,wX=0,vX=[];var zX=[];g.x(AX,g.X);g.h=AX.prototype;g.h.Za=function(a){AX.V.Za.call(this,a);this.ha=a};
g.h.Z=function(){AX.V.Z.call(this);this.G||(this.G=new g.$e(this.CF,this.D,this),g.Sd(this,this.G));this.G.start()};
g.h.Sa=function(){this.G.stop();AX.V.Sa.call(this)};
g.h.CF=function(){this.J||(this.J=new g.Yh(void 0));var a=g.ug(this.J);this.H?a.continuation=this.H:a.videoId=this.qa;var b={timeout:3E4};b.onSuccess=(0,g.v)(this.Kx,this);b.onError=(0,g.v)(this.Jk,this);b.Oc=(0,g.v)(this.Jk,this);g.Ag(this.J,"updated_metadata",a,b)};
g.h.Kx=function(a){if(this.ub)if(!a||a.error)this.Jk();else{var b=a.continuation;if(b&&b.timedContinuationData){b=b.timedContinuationData;var c=parseInt(b.timeoutMs,10);this.D=!c||0>c?0:c;this.H=b.continuation||null}else this.H=null,this.D=0;0<this.D&&this.G.start(this.D);if(a=a.actions)for(b=0;b<a.length;b++)if(a[b].updateViewershipAction)a:{c=a[b].updateViewershipAction||null;try{var d=c.viewership.videoViewCountRenderer.viewCount;if(!d&&!c.isEmpty)break a}catch(f){break a}null===this.aa&&(this.aa=
g.L("metadata-updateable-viewership"));BX(this.aa,d||null,!1)}else if(a[b].updateDateTextAction)(c=a[b].updateDateTextAction||null)&&c.dateText&&(c=c.dateText,null===this.N&&(this.N=g.L("metadata-updateable-date-text")),BX(this.N,c,!1));else if(a[b].updateDescriptionAction){if((c=a[b].updateDescriptionAction||null)&&c.description){var e=c.description;if(e||c.isEmpty)null===this.T&&(this.T=g.L("metadata-updateable-description")),BX(this.T,e,!0)}}else a[b].updateTitleAction?(c=a[b].updateTitleAction||
null)&&c.title&&(c=c.title,null===this.W&&(this.W=g.L("metadata-updateable-title")),BX(this.W,c,!1)):a[b].updateSentimentAction&&g.H("new-like-renderer-notification",a[b].updateSentimentAction.sentimentRenderer.likeButtonRenderer)}};
g.h.Jk=function(){this.ub&&(this.na++,3<=this.na?this.D=0:(this.D=Math.max(6E4,2*this.D),this.G.start(this.D)))};var DX,EX,FX,GX,HX,IX,JX,KX,CX,OX,QX,SX=!1,NX=[],LX=[];var dY=[],fY=[],vY=0,aY=null,lY=!1,tY=!1,uY=null,UX=null,VX=null,TX=null,WX=null,XX=null,YX=null,ZX=null,$X="",wY=null,cY=!1;g.x(CY,g.C);g.h=CY.prototype;g.h.X=function(){g.Vg(this.C);this.C.length=0;g.jg(this.G);this.G.length=0;g.cg(this.L);this.H&&this.H.abort();CY.V.X.call(this)};
g.h.Fq=function(){BY(this,"action-panel-share",!1,!0);g.lq(this.F,document.body,!0)};
g.h.Ux=function(){PU(g.Tz.getInstance(),this.J);g.W(this.F)};
g.h.Cq=function(a){a=g.F(a.currentTarget,"trigger-for");a==this.D?g.uv(this.F):DY(this,a,!1,!0);"action-panel-report"==a&&(a=g.kL())&&a.isReady()&&a.pauseVideo()};
g.h.sE=function(){g.W("watch-actions-share-loading")};
g.h.eH=function(a,b,c,d){var e=g.z("watch7-views-info"),f=g.M("likes-count",e);f&&g.N(f,a);(a=g.M("dislikes-count",e))&&g.N(a,b);if(b=g.M("video-extras-sparkbar-likes",e))b.style.width=c+"%";if(c=g.M("video-extras-sparkbar-dislikes",e))c.style.width=d+"%"};var GY,UY,NY,OY,PY,QY,RY,SY,cqa={"play-next":function(){var a=g.E("VIDEO_ID",void 0),b=g.E("LIST_ID",void 0);VY()?g.H("watch-queue-addto-playlist-play-next",b,a):g.H("watch-queue-addto-video-play-next",a)}},HY=[],JY=[];var ZY,tZ=[],AZ=!1,CZ="",DZ={},sZ=0,zZ={};var $Z=[];g.r("yt.www.watch.related.loadMore",function(a){g.W("watch-more-related-button");g.V("watch-more-related");a=g.F(a,"continuation");nqa(a,function(){var b=g.z("watch-more-related");g.H("yt-uix-load-more-success");g.H("yt-dom-content-change",b)})},void 0);
g.r("yt.www.watch.player.getClientPlaybackNonce",function(){var a=ZY;return a&&a.isReady()?a.getVideoData().cpn||"":""},void 0);
g.r("yt.www.watch.player.seekTo",BZ,void 0);g.r("yt.www.watch.player.pause",function(){var a=ZY;a&&a.pauseVideo()},void 0);
g.r("yt.www.watch.player.saveResumeOffset",wZ,void 0);g.r("yt.www.watch.lists.loadThumbnails",iY,void 0);g.r("yt.www.watch.lists.getState",kY,void 0);g.r("yt.www.watch.lists.next",pY,void 0);g.r("yt.www.watch.lists.prev",qY,void 0);var b_=[],IZ=null,HZ=null,FZ=new g.Uh("ytg-eventpromo");var JZ=null;var OZ=[],LZ=[],KZ=null,tqa=null,MZ=null,NZ=-1,QZ=-1,RZ=-1;g.h=SZ.prototype;g.h.dispose=function(){g.bg(this.C);g.jg(this.F);this.F.length=0};
g.h.ZC=function(){this.tg()};
g.h.Iq=function(a){var b=g.z("page");b&&(b=g.D(b,"watch-wide"),a?b&&this.Kl(!1):"1"!==g.Rh.get("wide",void 0)||b||this.Kl(!0))};
g.h.Kl=function(a){a=!!a;var b=g.z("watch7-sidebar"),c=g.z("page");if(g.z("player")&&b&&c){var d=rpa(b);a?(g.Q(c,"watch-wide"),g.H("yt-dom-content-change",b),g.bg(this.C),this.C=g.$f((0,g.v)(function(){this.tg();g.H("yt-dom-content-change")},this),d)):(g.R(c,"watch-wide"),g.Q(c,"watch-non-stage-mode"),g.R(c,"watch-stage-mode"),this.tg(),g.H("yt-dom-content-change"),g.bg(this.C),this.C=g.$f(function(){g.H("yt-dom-content-change",b)},d))}};
g.h.yD=function(a){g.D(document.body,"flexwatch-noupscale")&&((0,g.Ll)(["large","hd720","hd1080"],function(b){return g.Ma(a,b)}),this.tg())};
g.h.tg=function(){g.bg(this.C);var a=g.z("player"),b=g.z("page");if(g.z("watch7-container")&&a){a=g.D(b,"watch-wide");var c=window.matchMedia&&window.matchMedia("screen and (max-width: 656px)").matches;c?b&&(g.R(b,"watch-stage-mode"),g.Q(b,"watch-non-stage-mode")):a&&b&&(g.R(b,"watch-non-stage-mode"),g.Q(b,"watch-stage-mode"));(b=g.kL())&&(b.isReady()?b.setSizeStyle(!c,a):b.addEventListener("onReady",(0,g.v)(this.tg,this)))}};var TZ=[];var UZ=[],a_=[],r_=[];var e_={},d_={};g.aj(g.Ar({name:"www/watch",deps:["www/common"],page:"watch",init:function(){Dqa();g.M("guide-module-loading")&&Eqa();var a=[];g.E("WATCH_COMMENTS_FORCE_DISABLED")||a.push("comments");g.E("DELAY_LOAD_FOOTER")&&a.push("footer");Fqa(a);g.QG();g.VG()},
dispose:function(){VZ&&(g.Rd(VZ),VZ=null);ZZ&&(g.Rd(ZZ),ZZ=null);WZ&&(g.Rd(WZ),WZ=null);XZ&&(g.Rd(XZ),XZ=null);YZ&&(g.Rd(YZ),YZ=null);g.br(document,"keydown",YY);yX();g.ch(nX);nX.length=0;var a=VW;a&&(a.use_gut&&g.ng("//www.googletagservices.com/tag/js/gpt.js"),a.show_afv&&g.ng("//pagead2.googlesyndication.com/pagead/show_companion_ad.js"));null!=window.adModuleLoaded&&g.cr("adModuleLoaded");g.bg(pX);WW&&(WW=null);TW&&(TW.dispose(),TW=null);UW();VW=fX=eX=dX=null;bX=ZW=oX=!1;if(cX.length){for(a=cX.length-
1;0<=a;a--)g.cr(cX[a]);cX.length=0}g.dL();RX();g.jg(OZ);g.jg(QZ);g.Vg(LZ);OZ.length=0;LZ.length=0;g.ZG();g.hH();g.Vg(dY);dY.length=0;a=aY;aY=null;a&&(a.removeEventListener("onCueRangeEnter",rY),a.removeEventListener("onReady",bY),a.isReady()&&(a.removeCueRange("AUTOPLAY_PREFETCH"),a.removeEventListener("onPlaylistNext",pY),a.removeEventListener("onPlaylistPrevious",qY),a.removeEventListener("onPlaylistIndex",sY)));g.jg(fY);fY.length=0;UX&&g.R(UX,"scrolled");tY=lY=!1;ZX=YX=XX=WX=VX=TX=UX=uY=null;$X=
"";wY&&(g.bg(wY),wY=null);g.bh(vY);(a=g.z("guide-container"))&&g.R(a,"branded");if(a=g.z("player"))a.style.background="";$Z&&(g.Vg($Z),$Z=[]);g.jg(TZ);TZ.length=0;g.jg(JY);JY.length=0;g.Vg(HY);HY.length=0;GY&&(UY=!1,SY=RY=QY=PY=OY=NY=GY=null,g.QF());c_&&c_.dispose();g.Vg(a_);a_.length=0;g.jg(r_);r_.length=0;g.ch(UZ);UZ.length=0;(a=ZY)&&a.sendAbandonmentPing&&a.sendAbandonmentPing();vZ()&&wZ();g.cg(sZ);ZY&&(a=ZY,a.removeEventListener("onReady",$Y),a.removeEventListener("onStateChange",aZ),a.removeEventListener("onVideoProgress",
bZ),a.removeEventListener("SHARE_CLICKED",cZ),a.removeEventListener("SIZE_CLICKED",dZ),a.removeEventListener("onError",eZ),a.removeEventListener("onAdStart",fZ),a.removeEventListener("onAutonavChangeRequest",gZ),a.removeEventListener("onAutonavPauseRequest",hZ),a.removeEventListener("onFeedbackStartRequest",iZ),a.removeEventListener("onFeedbackArticleRequest",jZ),a.removeEventListener("onScreenChanged",kZ),a.removeEventListener("onLogClientVeCreated",lZ),a.removeEventListener("onLogServerVeCreated",
mZ),a.removeEventListener("onLogVeClicked",nZ),a.removeEventListener("onLogVesShown",oZ),a.removeEventListener("onYpcContentRequest",pZ),a.removeEventListener("onPlayVideo",qZ));ZY=null;AZ=!1;CZ="";DZ={};g.jg(tZ);tZ.length=0;zZ={};g.AH();g.Rd(JZ);JZ=null;g.hH();g.Vg(zX);for(a=zX.length=0;a<b_.length;a++)g.Vg(b_[a]);document.body&&g.R(document.body,"gaming-event-promo-visible");g.TL.dispose();for(var b in d_)g.bg(d_[b]);d_={};g.Vg(e_.Nv);g.TL.dispose();g.VC(g.SG)}}));})(_yt_www);
