(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var Uya=function(){if(!g.Df)return!1;try{return new ActiveXObject("MSXML2.DOMDocument"),!0}catch(a){return!1}},Wya=function(a){if("undefined"!=typeof DOMParser){var b=new DOMParser;
a=g.up(a);return b.parseFromString(g.Zb(a),"application/xml")}if(Vya){b=new ActiveXObject("MSXML2.DOMDocument");b.resolveExternals=!1;b.validateOnParse=!1;try{b.setProperty("ProhibitDTD",!0),b.setProperty("MaxXMLSize",2048),b.setProperty("MaxElementDepth",256)}catch(c){}b.loadXML(a);return b}throw Error("Your browser does not support loading xml documents");},T9=function(a){a=void 0===a?{}:a;
this.F=a.languageCode||"";this.L=a.languageName||null;this.D=a.kind||"";this.G=a.name||null;this.pb=a.id||null;this.H=a.is_servable||!1;this.isTranslateable=a.is_translateable||!1;this.M=a.url||null;this.J=a.vss_id||"";this.isDefault=a.is_default||!1;this.C=a.translationLanguage||null},U9=function(a){var b=a.L||"",c=[b];
"asr"==a.D&&-1==b.indexOf("(")&&c.push(" (Automatic Captions)");a.G&&c.push(" - "+a.G);a.C&&c.push(" >> "+a.C.languageName);return c.join("")},Xya=function(){this.F=[];
this.C=[]},V9=function(a,b){return b?a.C.concat(a.F):a.C},W9=function(a,b){switch(b.D){case "asr":return Yya(b,a.F);
default:return Yya(b,a.C)}},Yya=function(a,b){return g.Ka(b,(0,g.v)(a.equals,a))?!1:(b.push(a),!0)},X9=function(){g.C.call(this);
this.F=new Xya;this.M=[]},Zya=function(a,b){return g.Ka(V9(a.F,!0),function(c){return c.toString()==b})},$ya=function(a,b,c,d,e){X9.call(this,e||null);
c=c||g.fr(a).hl||"";c=c.split("_").join("-");this.H=g.uh(a,{hl:c});this.G=b;this.L=!!d;this.D={};this.C=null},Y9=function(a,b,c){var d=aza(a,b),e=(0,g.v)(function(f){this.C=null;
c(f.responseText,b)},a);
a.C&&a.C.abort();a.C=g.J(d,{format:"RAW",onSuccess:e,withCredentials:!0})},bza=function(a,b){var c=a.H,d={type:"list",
tlangs:1,v:a.G,vssids:1};a.L&&(d.asrs=1);c=g.uh(c,d);d=(0,g.v)(function(e){this.C=null;if((e=e.responseXML)&&e.firstChild){for(var f=g.ka(e.getElementsByTagName("track")),k=f.next();!k.done;k=f.next()){var l=k.value;k=l.getAttribute("lang_code");var m=l.getAttribute("lang_translated"),p=l.getAttribute("name"),t=l.getAttribute("kind"),y=l.getAttribute("id"),A="true"==l.getAttribute("lang_default"),G="true"==l.getAttribute("cantran");l=l.getAttribute("vss_id");W9(this.F,new T9({languageCode:k,languageName:m,
name:p,kind:t,id:y,is_servable:!0,is_translateable:G,vss_id:l,is_default:A}))}e=e.getElementsByTagName("target");f=e.length;for(k=0;k<f;k++)m=e[k].getAttribute("lang_code"),p=e[k].getAttribute("lang_translated"),t=e[k].getAttribute("lang_original"),y=e[k].getAttribute("id"),A="true"==e[k].getAttribute("lang_default"),m={languageCode:m,languageName:p,languageOriginal:t,id:y,isDefault:A},this.D[m.languageCode]=m.languageName,this.M.push(m)}b()},a);
a.C&&a.C.abort();a.C=g.J(c,{format:"RAW",onSuccess:d,withCredentials:!0})},aza=function(a,b){var c=a.H,d={v:a.G,
type:"track",lang:b.F,name:b.getName(),kind:b.D,fmt:"srv1"};b.C&&(d.tlang=b.C?b.C.languageCode:b.F);return c=g.uh(c,d)},dza=function(){if(g.E("TTS_URL")&&!Z9){var a=g.kL();
a&&(Z9=new cza(a))}},eza=function(a,b,c){this.start=a;
this.append=b;this.text=c},cza=function(a){this.player=a;
this.M=null;this.la=!1;this.G=[];this.L=[];this.D=new $ya(g.E("TTS_URL",void 0),g.E("VIDEO_ID",void 0),null,!0);this.W=null;this.aa=[];this.N=-1;this.T=!1;this.J=this.Y=0;this.C=this.F=null;this.player.addEventListener("captionschanged",(0,g.v)(this.Vz,this))},fza=function(a,b){if(b.translationLanguage){var c=b.translationLanguage.languageCode;
b.translationLanguage.languageName=a.D.D[c]||c}c=new T9(b);return c.isValid()?c:null},$9=function(a,b,c){var d=g.nd("BUTTON",{className:["yt-ui-menu-item yt-uix-menu-close-on-select yt-uix-button-menu-item"],
value:c});c=g.nd("SPAN",{className:"yt-uix-button-content transcript-lang",value:c});b=document.createTextNode(String(b));a.H.appendChild(d);d.appendChild(c);c.appendChild(b)},hza=function(a,b){var c=b.getAttribute("t");
c=c?parseInt(c,10):1E3*parseFloat(b.getAttribute("start")||0);var d=!!b.getAttribute("append"),e=Wya("<html>"+(b.firstChild&&b.firstChild.nodeValue||"")+"</html>");return gza(a,c,d,e.firstChild)},gza=function(a,b,c,d){for(var e=[],f=0;f<d.childNodes.length;f++){var k=d.childNodes[f];
3==k.nodeType?e.push(new eza(b,c||0<f,k.nodeValue)):e=e.concat(gza(a,b,c||0<f,k))}return e},iza=function(a,b){g.cg(a.J);
var c=Math.min(b.offsetTop-a.C.offsetTop,a.C.scrollHeight-a.C.offsetHeight),d=0;a.J=g.ag((0,g.v)(function(){var e=c-this.C.scrollTop,f=Math.round(100*e/(1E3-50*d));Math.abs(e)<=Math.abs(f)||20<d?(this.C.scrollTop=c,g.cg(this.J)):(this.C.scrollTop+=f,d++)},a),50)};var Vya=g.Df&&Uya();var jza={cupcake:1.5,donut:1.6,eclair:2,froyo:2.2,gingerbread:2.3,honeycomb:3,"ice cream sandwich":4,jellybean:4.1,kitkat:4.4,lollipop:5.1,marshmallow:6,nougat:7.1};var a$=g.Qb;a$=a$.toLowerCase();if(g.xb(a$,"android")){var kza=a$.match(/android\s*(\d+(\.\d+)?)[^;|)]*[;)]/);kza&&100>parseFloat(kza[1])||a$.match("("+g.un(jza).join("|")+")")};g.h=T9.prototype;g.h.getId=function(){return this.pb};
g.h.getName=function(){return this.G};
g.h.isServable=function(){return this.H};
g.h.getUrl=function(){return this.M};
g.h.toString=function(){return this.F+": "+U9(this)+" - "+this.J};
g.h.equals=function(a){return a?this.toString()==a.toString():!1};
g.h.isValid=function(){return!(!this.F||this.C&&!this.C.languageCode)};g.n(X9,g.C);X9.prototype.X=function(){this.C&&this.C.abort();g.C.prototype.X.call(this)};var b$;var lza=g.Qb,mza=lza.match(/\((iPad|iPhone|iPod)( Simulator)?;/);if(!mza||2>mza.length)b$=void 0;else{var c$=lza.match(/\((iPad|iPhone|iPod)( Simulator)?; (U; )?CPU (iPhone )?OS (\d+_\d)[_ ]/);b$=c$&&6==c$.length?Number(c$[5].replace("_",".")):0}0<=b$&&0<=g.Qb.search("Safari")&&g.Qb.search("Version");g.n($ya,X9);var Z9=null;g.h=cza.prototype;g.h.dispose=function(){g.Vg(this.G);this.G.length=0;this.L.length=0;g.cg(this.Y);g.cg(this.J)};
g.h.Vz=function(a){var b=fza(this,a);b&&(this.la?(W9(this.D.F,b)&&$9(this,U9(b),b.toString()),Y9(this.D,b,(0,g.v)(this.Zl,this))):this.L.push(a))};
g.h.open=function(a){if(this.la)a();else if(this.M=g.z("watch-transcript-container"),"true"==g.F(this.M,"disabled"))a();else{var b=g.nd("DIV",{className:"yt-uix-menu"}),c=g.nd("DIV",{className:"yt-uix-menu-trigger"});this.F=g.nd("BUTTON",{className:["yt-uix-button yt-uix-button-default hidden"],"button-menu-id":"watch-transcript-track-selector"});this.H=g.nd("DIV",{className:["yt-uix-menu-content yt-ui-menu-content yt-uix-menu-content-hidden"]});this.M.appendChild(b);b.appendChild(c);c.appendChild(this.F);
b.appendChild(this.H);this.C=document.createElement("div");this.C.id="transcript-scrollbox";g.Q(this.C,"yt-uix-scroller");this.G.push(g.I(this.C,"mouseover",(0,g.v)(function(){this.T=!0},this)));
this.G.push(g.I(this.C,"mouseout",(0,g.v)(function(){this.T=!1},this)));
this.M.appendChild(this.C);this.G.push(g.S(this.C,"click",(0,g.v)(this.Uz,this),"caption-line"));bza(this.D,(0,g.v)(function(){a:{for(var d=this.D,e=null,f=0;f<this.L.length;f++)(e=fza(this,this.L[f]))&&W9(d.F,e);var k=V9(d.F,!0);if(0>=k.length)g.V("watch-transcript-not-found");else{f=g.nd("SPAN",{className:"yt-uix-button-content transcript-lang"});var l=document.createTextNode(String(U9(k[0])));this.F.appendChild(f);f.appendChild(l);f=g.nd("IMG",{"class":"yt-uix-button-arrow",src:g.E("DROPDOWN_ARROW_URL",
void 0)});this.F.appendChild(f);g.V(this.F);f=0;for(l=k.length;f<l;f++)$9(this,U9(k[f]),k[f].toString());if(k=g.Cr("CC_ADD_TRANSCRIPT_TITLE"))$9(this,k,"add-cc"),g.dw(6035988,"cc_transcriptions"),g.cw();this.G.push(g.S(this.H,"click",(0,g.v)(this.Gx,this),"yt-uix-button-menu-item"));if(!e&&(e=V9(d.F,void 0)[0],!e))break a;Y9(d,e,(0,g.v)(this.Zl,this))}}a()},this));
this.la=!0}};
g.h.Gx=function(a){if("add-cc"==a.target.value)(a=g.E("CC_ADD_TRANSCRIPT_URL",void 0))&&g.pj(a);else{var b=this.D,c=(0,g.v)(this.Zl,this),d=Zya(b,a.target.value);d&&Y9(b,d,c);this.H&&(this.F.firstChild.innerHTML=a.target.innerHTML)}};
g.h.Uz=function(a){var b=g.F(a.currentTarget,"time");b&&(this.player.seekTo(parseInt(b,10),!0),a.preventDefault())};
g.h.Zl=function(a,b){this.N=-1;var c=[];if("string"===typeof a){c=[];try{var d=Wya(a);if(d&&d.firstChild)for(var e=g.ka(Array.from(d.firstChild.children)),f=e.next();!f.done;f=e.next())c=c.concat(hza(this,f.value))}catch(A){c=[]}}this.W=b;d=c;e=[];g.cg(this.Y);g.rd(this.C);f=document.createDocumentFragment();c=-1;for(var k=0,l=d.length;k<l;k++){var m=d[k];if(m.append){var p=f.getElementById("cp-"+c),t=p.getElementsByClassName("caption-line-text")[0];p=g.mp(t);"string"===typeof m.text&&g.N(t,p.concat(m.text))}else{c++;
p=document.createElement("div");t=m.start/1E3;e.push(m.start);p.id="cp-"+c;p.className="caption-line";g.Jq(p,"time",t+"");f.appendChild(p);var y=document.createElement("div");y.className="caption-line-time";y.innerHTML=Math.floor(t/60)+":"+(10>t%60?"0":"")+Math.floor(t%60);p.appendChild(y);t=document.createElement("div");t.className="caption-line-text";"string"===typeof m.text&&g.N(t,m.text);p.appendChild(t)}}this.F&&g.N(g.M("transcript-lang",this.F),U9(this.W));this.aa=e;this.C.appendChild(f);this.Y=
g.ag((0,g.v)(this.cH,this),500)};
g.h.cH=function(){for(var a=this.player.getCurrentTime(),b=this.aa,c=this.N,d=c;;){var e=0<=d?b[d]/1E3:-1;if(a+.5<e)--d;else if(e=d+1<b.length?b[d+1]/1E3:1E6,a+.5>e)d+=1;else break}d!=c&&(0<=c&&(a=g.z("cp-"+c),g.R(a,"caption-line-highlight")),0<=d&&(a=g.z("cp-"+d),g.Q(a,"caption-line-highlight")),this.N=d,this.T||iza(this,g.z("cp-"+(3<=d?d-3:0))))};g.r("yt.www.watch.transcript.open",function(a){dza();Z9.open(a)},void 0);
g.aj(g.Ar({name:"www/watch_transcript",deps:["www/watch"],page:"watch",init:function(){dza()},
dispose:function(){Z9&&(Z9.dispose(),Z9=null)}}));})(_yt_www);
